temporalio/sdk-go

- test/activity_test.go
- test/integration_test.go
> Fix integration tests

- internal/internal_workflow_testsuite.go
- internal/internal_workflow_testsuite_test.go
- test/integration_test.go
- test/workflow_test.go
Fixed flaky tests in child workflow handling of parent completion.
Fixed testsuite handling of local activity cancellation.
> Fixed flaky tests and local activity cancellation testsuite handling

- go.mod
- go.sum
- internal/client.go
- internal/internal_workflow_testsuite_test.go
Proto enum are changed separately but client has its own corresponding constants.
> Change WorkflowIdReusePolicy default value

- go.mod
- go.sum
- internal/common/metrics/service_wrapper.go
- internal/common/rpc/error_wrapper.go
- internal/common/rpc/error_wrapper_test.go
- test/integration_test.go
This implements the basic interface for PollForWorkflowExecutionRawHistory that was recently introduced into protos https://github.com/temporalio/temporal-proto/commit/8b2a688db9267c155f089b5432be8485b12493c9
> Implement Interface for new PollForWorkflowExecutionRawHistory

- CONTRIBUTING.md
- README.md
- internal/interceptors.go
- internal/worker.go
- test/workflow_test.go
Fixed MD files and `errcheck` and `staticcheck` errors.
> Fix README.md and lint errors

- evictiontest/workflow_cache_eviction_test.go
- go.mod
- go.sum
- internal/context.go
- internal/internal_task_handlers_interfaces_test.go
Incorrect `context` package was used.
> Use correct context package

- go.mod
- go.sum
- internal/common/metrics/service_wrapper.go
- internal/common/metrics/service_wrapper_test.go
- internal/internal_task_handlers.go
- internal/internal_task_pollers.go
- internal/internal_worker_test.go
`service_wrapper.go` is not actually used. I will completely remove it in upcoming PR.
> Rename ID to Id in proto files

- go.mod
- go.sum
- test/integration_test.go
Fix integration tests to match recent proto files changes.
> Rename WorkflowExecutionCloseStatus to WorkflowExecutionStatus

- client/client.go
- go.sum
- internal/common/serializer/jsonpb.go
- internal/common/serializer/serializer.go
- internal/internal_task_pollers.go
- internal/internal_utils.go
- internal/internal_worker.go
- internal/internal_workflow_client.go
- internal/internal_workflow_client_test.go
- internal/workflow.go
Merge from Cadence @ 25e007d45d86bc81bc07870f9cb3b6cab35e4f0e
Note:
- Changes skipped: Feature version increments, fossa script addition to buildkite
- `serializer.go` and `jsonpb.go` are copied from temporal server with minor modifications.
> Merge Cadence at 25e007d45d86bc81bc07870f9cb3b6cab35e4f0e

- Makefile
- internal/internal_task_pollers.go
For some reason race detector wasn't enabled.
> Add race detector to tests

- client/client.go
- internal/client.go
- internal/internal_worker.go
- internal/internal_worker_test.go
- internal/internal_workers_test.go
- internal/internal_workflow_client.go
- internal/internal_workflow_testsuite.go
- internal/worker.go
- mocks/Client.go
- mocks/NamespaceClient.go
- test/integration_test.go
but log error instead. Had to move logger to `ClientOptions` from `WorkerOptions` for this.
> CloseConnection doesn't return error

- evictiontest/workflow_cache_eviction_test.go
- go.mod
- go.sum
- internal/client.go
- internal/common/serializer/serializer.go
- internal/common/util/stringer.go
- internal/context.go
- internal/error.go
- internal/error_test.go
- internal/internal_decision_state_machine.go
- internal/internal_decision_state_machine_test.go
- internal/internal_event_handlers.go
- internal/internal_task_handlers.go
- internal/internal_task_handlers_interfaces_test.go
- internal/internal_task_handlers_test.go
- internal/internal_task_pollers.go
- internal/internal_utils_test.go
- internal/internal_worker.go
- internal/internal_worker_interfaces_test.go
- internal/internal_worker_test.go
- internal/internal_workers_test.go
- internal/internal_workflow_client.go
- internal/internal_workflow_client_test.go
- internal/internal_workflow_testsuite.go
- internal/internal_workflow_testsuite_test.go
- internal/workflow_testsuite.go
- mocks/mock_test.go
- test/bindings_test.go
- test/integration_test.go
- test/workflow_test.go
Simple global replace w/o any logic change.
> Prefix enums with type and convert to upper case

- go.mod
- go.sum
- internal/internal_task_handlers_test.go
This is just to upgrade dependencies and fix one test.
> Add UNSPECIFIED to every enum

- go.mod
- go.sum
- internal/internal_workflow_client.go
- test/integration_test.go
Server will use `STRONG` as default.
> Remove query consistency level from request

- interceptors/workflow_interceptor.go
- internal/interceptors.go
- internal/internal_coroutines_test.go
- internal/internal_event_handlers_test.go
- internal/internal_worker.go
- internal/internal_workflow.go
- internal/internal_workflow_test.go
- internal/internal_workflow_testsuite.go
- internal/worker.go
- internal/workflow.go
- test/integration_test.go
Refactored workflow interceptor to match the interface of the Java SDK. Added ability to intercept workflow goroutine creation.
> WorkflowInterceptor refactoring

- internal/error_test.go
- internal/internal_workflow_test.go
- internal/internal_workflow_testsuite.go
- internal/internal_workflow_testsuite_test.go
- internal/session_test.go
- internal/workflow_testsuite_test.go
Test framework now wraps errors the same way as real implementation does.
> Wrap test framework errors

- go.mod
- go.sum
- internal/internal_workflow_client.go
> Add QUERY_REJECT_CONDITION_NONE

- internal/internal_workflow_testsuite_test.go
Hack was added some time ago and now it is not needed. I don't know who and when fixed it but it seems to be working now.
> Remove race condition hack

- evictiontest/workflow_cache_eviction_test.go
- internal/internal_event_handlers.go
- internal/internal_task_handlers.go
- internal/internal_task_pollers.go
- internal/internal_workflow_client.go
- internal/internal_workflow_testsuite.go
Set `STICKY` for sticky task queues and `NORMAL` for default ones.
> Fix task queue kind

- go.mod
- go.sum
```
$ go get go.temporal.io/api@master
$ go mod tidy
$ go mod verify
```
> Update SDK with the most recent API

- client/client.go
- internal/internal_decision_state_machine.go
Syncs up the SDK with server behavior that returns closed workflows by close time descending
> Updates comment on ListClosedWorkflow method

- test/activity_test.go
- test/integration_test.go
- test/workflow_test.go
GO SDK already has capability to complete activities by business ID.  Added an integration test for this API.
Fixes #129
> Integration test for completing activity by ID

- internal/internal_worker_base.go
> Replace syscall package with os

- internal/version.go
Bumps version to 0.28.1 to address heartbeat timer bug
> Bump SDK version

- README.md
Based on this post by Mark
https://temporalio.slack.com/archives/CTDTU3J4T/p1598463022011500
> Add logging section to README

- internal/grpc_dialer.go
> Set MinConnectTimeout

- go.mod
- go.sum
- internal/version.go
> Release 1.0.0

- worker/worker.go
> Relocate workflow and activity registration functions to separate interfaces

- internal/version.go
`SDKVersion` indicates next release version.
> Bump minor SDKVersion to follow new release process

- converter/default_data_converter.go
- internal/workflow.go
- internalbindings/internalbindings.go
Provides access to lastCompletionResult via accessor for WorkflowEnviroment. Required for PHP-SDK integration.
P.S. Contains another approved PR - #339
> Access last run details

- workflow/doc.go
This pull request updates workflow/doc.go according to the new practices on workflow and activity registration.
> Update workflow package registration notes

- internal/version.go
Bumping hard-coded version after the release.
> Update version to 1.6.0 post release

- internal/internal_task_handlers.go
- internal/workflow.go
Added WorkflowInfo.StartTime field. 
This is to allow workflow code to get time when it was started.
> Added WorkflowInfo.StartTime

- go.sum
- internal/internal_worker_test.go
- internal/workflow.go
- workflow/workflow.go
Tests upgraded to better cover invocation of local activity execution
* Also fix misleading docstring
While investigating https://github.com/temporalio/sdk-go/issues/405 and https://github.com/temporalio/sdk-go/issues/424
1. Closes issue: 
> Upgrade activity invocation test to use local execution as well

- .buildkite/Dockerfile
- .buildkite/docker-compose.yml
- .buildkite/pipeline.yml
- .gitignore
- Makefile
Add fossa scans to buildkite
license checks
1. Closes issue: 
buildkite
> Add fossa scan

- internal/version.go
Update internal version for 1.7.0
> Update version to 1.7.0

- internal/internal_workflow_testsuite.go
- internal/internal_workflow_testsuite_test.go
- internal/workflow_testsuite.go
Unit test to properly handle parent policy of terminate. This is a follow up of https://github.com/temporalio/sdk-go/pull/471
Better handle workflow parent policy in test.
1. Closes 
New unit tests.
No.
> parent_policy_terminate

- internal/client.go
doc string
it was confusing when it mentioned thriftEncoder as everything is migrated to protobuf
1. Closes 
N/A
N/A
N/A
> Correct doc on DataConverter

- internal/version.go
Update internal version to 1.8.0
> Update internal version to 1.8.0

- internal/activity.go
- internal/internal_task_pollers.go
Added missing local activity info into local activity logger and added a trace line.
> Add local activity info into local activity logger/tracer

- internal/internal_retry.go
@yiminc  This PR resolves #502 making default retry behavior less aggressive.
I don't think that initial 20ms with 1.2x backoff made a lot of sense as retries were done in a very rapid succession effectively bombarding the server with too many attempts. See example of default retry attempts:
```
2021/08/02 10:38:07 DEBUG Failing API call for operation: SignalWorkflowExecution call: 0
2021/08/02 10:38:07 DEBUG Failing API call for operation: SignalWorkflowExecution call: 1
2021/08/02 10:38:07 DEBUG Failing API call for operation: SignalWorkflowExecution call: 2
2021/08/02 10:38:07 DEBUG Failing API call for operation: SignalWorkflowExecution call: 3
2021/08/02 10:38:07 DEBUG Failing API call for operation: SignalWorkflowExecution call: 4
2021/08/02 10:38:07 DEBUG Failing API call for …
```
> Reduce retry aggressivness

- .buildkite/pipeline.yml
Added automatic retries to Fossa scans. This should mitigate transient issues.
1. Closes 
> Add automatic retry to fossa scans

- internal/version.go
Update internal version to 1.9.0
> Update internal version to 1.9.0

- internal/interceptors.go
- internal/internal_workflow.go
- internal/workflow.go
- test/integration_test.go
Added inbound interceptors for Signal and Query
We lack ability to intercept signals and queries.
1. Partially resolves issue #515
2. How was this tested: unit tested
No
> Add inbound interceptors for Signal and Query

- .github/CODEOWNERS
- CODEOWNERS
> Add @alexshtin to CODEOWNERS

- internal/version.go
Updating version to the latest.
> Update internal/version.go to 1.10.0

- test/integration_test.go
Add integration test to verify local activity retry behavior.
1. Closes 
> Integration test for local activity retry and workflow heartbeat

- test/activity_test.go
- test/integration_test.go
- test/workflow_test.go
* Also make it go slightly faster
Change the timings in this test to not need to be so exact
Flaky test
> Give this flaky test some room for slight timing mismatches

- test/workflow_test.go
Adjust timeout settings for heartbeat integration test to allow more margin for errors.
Fix flakey integration tests.
1. Closes 
> Adjust timeouts for heartbeat integration test

- test/integration_test.go
- test/workflow_test.go
Added a test (that didn't repro anything)
Protection against possible canceled-after-fired errors
1. Closes 
> Add a test which double checks some cancel-on exit behavior

- worker/worker.go
Removed non-existent parameter from docs.
Referred to non-existent parameter.
1. Closes #618
> Fixed worker.New docs

- .github/CODEOWNERS
Add mmcshane to CODEOWNERS
So I can at least meaningfully give code reviews
1. Closes 
n/a
n/a
No
> Add mmcshane to CODEOWNERS

- internal/activity.go
- internal/activity_test.go
- internal/internal_activity.go
- internal/internal_task_handlers.go
- internal/internal_task_handlers_test.go
Add debug log for all record activity heartbeat errors.
For investigating heartbeat failures.
1. Closes 
> Add debug log for all errors received from RecordActivityHeartbeat

- contrib/opentelemetry/go.mod
- contrib/opentracing/go.mod
- contrib/tally/go.mod
- test/go.mod
This is needed for transitive use
> Updated SDK version in nested modules

- internal/grpc_dialer_test.go
- test/integration_test.go
In some cases, gRPC servers weren't started fast enough and no-cache events came in unexpected orders for tracing. This attempts to address those issues.
Flaking on internal CI runs.
1. Closes #677
> Address TestCustomResolver and TestOpenTelemetryTracing flakiness

- test/integration_test.go
Remove data race and recursively dedupe spans when checking results
#680 did not dedupe spans recursively. There is also a data race in the test interceptor.
> Fix flakiness with OpenTelemetry integration test (attempt 2)

- internal/version.go
Update release version to 1.13.0
For new release
> Update release version to 1.13.0

- internal/grpc_dialer_test.go
Ensure that the test code doesn't race against grpc connection
establishment in a way that results in test failures.
Test failures are bad
1. Closes 
I was able to reproduce a failure in as few as 12 test runs but sometimes it took more
than 2000 runs to reproduce. That said, this test failed in two of the
last four CI runs so it definitely has an impact.
> Address rare custom resolver test race

- contrib/tools/workflowcheck/determinism/checker.go
- contrib/tools/workflowcheck/determinism/testdata/src/a/ignore.go
Made ignore comment work with Godoc
Wasn't working with Godoc
1. Closes #710
> Support workflowcheck ignore comment alongside godoc

- internal/version.go
Bump version to 1.14.0
New release
> Bump version to 1.14.0

- .github/workflows/ci.yml
- .github/workflows/wait_for_server.go
Added GH CI action for building and testing this project (to eventually replace BuildKite)
GH actions are more visible and are easier to contribute to
> GitHub CI action

- contrib/opentelemetry/go.sum
- contrib/opentracing/go.sum
- contrib/tally/go.sum
- go.mod
- go.sum
- test/go.mod
- test/go.sum
Update `go.temporal.io/api` reference.
To include https://github.com/temporalio/api/pull/174 changes.
> Update go.temporal.io/api reference

- internal/interceptor.go
- internal/interceptor_base.go
- internal/internal_command_state_machine.go
- internal/internal_event_handlers.go
- internal/internal_event_handlers_test.go
- internal/internal_worker.go
- internal/internal_worker_base.go
- internal/internal_workflow.go
- internal/internal_workflow_test.go
- internal/internal_workflow_testsuite.go
- internal/workflow.go
- internal/workflow_testsuite.go
- Handler registration by update name
- Event handling update events
- Invocation of user-provided update validators and handlers
- Mapping of update results/errors into commands to return upstream
New feature: synchronous updates
1. Closes 
n/a
Unit tests added for most LoC. Integrations tests will be delivered once server support is in place.
Yes. Samples, sdk-features entry, and product docs all in progress.
> Add workflow update handling

- contrib/opentelemetry/go.sum
- contrib/opentracing/go.sum
- contrib/tally/go.sum
- converter/grpc_interceptor.go
- go.mod
- go.sum
- internal/internal_command_state_machine.go
- internal/internal_event_handlers.go
- internal/internal_event_handlers_test.go
- internal/internal_task_handlers.go
- test/go.mod
- test/go.sum
Update some type names and enums as appropriate. No behavioral changes.
API is in flux, keeping up with latest
1. Closes 
n/a
No behavioral changes
No
> Consume api v1.11.0

- internal/version.go
Update version to v1.16.0
Impending release
> Update version to 1.16

- internal/version.go
Update version for v1.17.0 release
> Release v1.17.0

- internal/common/backoff/retry.go
- internal/common/backoff/retry_test.go
- internal/internal_worker_base.go
Added backoff mimicking server's logic at https://github.com/temporalio/temporal/blob/v1.18.0/common/backoff/retry.go#L198-L208 for resource exhausted. It's obviously not a good algorithm to optionally trigger stateful backoffs and is _not_ the algorithm used by TypeScript at https://github.com/temporalio/sdk-typescript/pull/879. But the goal of this issue was to solve the immediate need without much refactoring. Also to that point, the pollers were not written to have the backoff times easily testable and it was not worth rewriting pollers, so the tests only confirm the secondary retrier works, not whether the poller part does.
Asked to in https://github.com/temporalio/sdk-features/issues/96
If we wanted to do this on non-poll gRPC calls, it would be a completely different (they use the …
> Support backing off more for resource exhausted on pollers

- internal/internal_worker.go
- internal/worker.go
Set default max eager activities to 3
Need to be measured in our rollout of this feature
1. Closes #919
> Set default max eager activities to 3

- internal/version.go
> Version v1.18.1

- internal/schedule_client.go
- internal/workflow.go
- workflow/deterministic_wrappers.go
- workflow/doc.go
Some low effort doc fixes
closes https://github.com/temporalio/sdk-go/issues/925
closes  https://github.com/temporalio/sdk-go/issues/948
related https://github.com/temporalio/sdk-features/issues/182
> Fix some documentation

- internal/schedule_client.go
Noticed a few typos in the schedule docs
> Fix schedule docs

- .github/workflows/ci.yml
Waiting for https://github.com/temporalio/sdk-features/pull/207
> Rename sdk-features to features

- internal/version.go
Ibid
Part of release process
1. Closes 
> Update SDKVersion to 1.21.0

- internal/version.go
> Update SDKVersion to 1.21.1

- internal/internal_update.go
- internal/internal_update_test.go
When replaying, don't send response messages (Accept/Reject/Complete).
These messages are redundant during replay - they should only be sent when not replaying.
1. Closes 
#1057 
3. How was this tested:
Unit test & features test
4. Any docs updates needed?
No
> Suppress update messages during replay

- client/client.go
Remove experimental tag from schedules as discussed.
> Remove experimental tag from schedules

- internal/internal_update.go
Adds message IDs to update messages
This was just missed earlier. The IDs will be necessary to refer to messages by ID in the future.
1. Closes 
> Add message IDs to update messages

- internal/version.go
> Update SDK Version to 1.22.0

- internal/internal_workflow_client.go
Match what we will do in the Java SDK and set the update ID client side if the user does not set one.
> Set Update ID client side

- .github/workflows/ci.yml
Ignore errors from uploading to coveralls
Coveralls is giving 500 errors to this upload for this repository most of the time. There is a bigger refactor to the build also in PR but this one just allows us to land PRs in the interim.
1. Closes 
> Ignore errors from uploading to coveralls

- internal/version.go
> Release v1.23.0

- internal/workflow_testsuite.go
- internal/workflow_testsuite_test.go
> Aligning OnWorkflow with OnActivity and adding unit tests to confirm behavior is coherent

- internal/internal_workflow_client.go
Add retry to UpdateWorkflow call
Same retry as already exists for outcome polling. This was missed in previous changesets.
1. Closes 
New unit tests here
No
> Add retry to UpdateWorkflow call

- internal/version.go
Release Go SDK v1.23.1 in preparation for the next server release
> Release v1.23.1

- client/client.go
> Add missing schedule types

- workflow/doc.go
Add some short docs on update and link to our existing docs.
> Add docs on update

- client/client.go
- internal/client.go
- internal/schedule_client.go
- internal/workflow.go
- workflow/workflow.go
Remove any mention of elastic search or advanced visibility from our go docs and just link to our external docs
closes https://github.com/temporalio/sdk-go/issues/1074
> Remove mentions of elastic search

- .github/workflows/docker/dynamic-config-custom.yaml
- test/worker_versioning_test.go
Enabled worker versioning tests for CI
> Enabled worker versioning tests

- .github/workflows/ci.yml
- go.mod
Update CI to test on both Golang 1.21 and 1.20
> Update CI to Golang v1.21

- README.md
- internal/log/replay_logger.go
- log/with_logger.go
Update readme to recommend users use slog integration.
Also added some interface checks to the loggers
> Update readme for slog

- internalbindings/internalbindings.go
- Create binding for the `UpdateCallbacks` in the `internalbindings` module.
- RoadRunner temporal integration to the `WorkflowDefinition` callback.
1. Closes 
RoadRunner temporal + php-sdk tests
PHP-SDK docs, new section about UpdateWorkflow support.
> chore: create `UpdateCallbacks` binding for the RoadRunner

- internal/workflow_testsuite.go
Corrected a comment and added a missing one.
Clarify behaviour.
> Small docs tweaks.

- converter/composite_data_converter.go
- converter/json_payload_converter.go
- converter/payload_converter.go
Editing of docstrings alone; no code changes.
> Edit docstrings

- workflow/doc.go
> Fix doc typo

- internal/internal_event_handlers.go
- test/replaytests/replay_test.go
- test/replaytests/workflow_with_bad_unknown_event.json
- test/replaytests/workflow_with_unknown_event.json
closes https://github.com/temporalio/sdk-go/issues/1312
> Fail task on unknown event when HistoryEvent.worker_may_ignore is false

- internal/internal_event_handlers.go
- internal/internal_worker_base.go
- internal/internal_workflow_testsuite.go
- internal/internal_workflow_testsuite_test.go
- internal/workflow.go
- internal/workflow_testsuite.go
- internal/workflow_testsuite_test.go
Add support for typed search attributes to the test suite
> Add support for typed search attributes to the test suite

- .github/workflows/ci.yml
> Update CI to Go lang 1.22

- contrib/tools/workflowcheck/workflow/checker.go
Update workflow check with new function added in the SDK
> Update workflow check with new function added in the SDK

- README.md
Update readme badge to github actions instead of buildkite.
> Update readme badge to github action

- internal/version.go
> Release v1.26.1

- test/integration_test.go
Test was flaking I suspect from a race between stopping the worker and sending the update. Fix is to not even attempt to start the worker.
> Fix flake in TestUpdateAdmittedNoWorker

- internal/version.go
> Release v1.27.0

- .github/workflows/ci.yml
Point feature repo back to main
> Point feature repo back to main

- internal/cmd/build/main.go
- internal/internal_nexus_task_handler.go
- internal/nexus_operations.go
- temporalnexus/operation.go
- test/nexus_test.go
This is work done by @pdoerner in #1544 that was lost in the `nexus` feature branch merge.
> Add utility to get metrics handler for a Nexus operation

- .github/workflows/ci.yml
Should fix merge to main omes build
> Use correct branch when not a pull request

- workflow/workflow.go
> Fix UpsertTypedSearchAttributes docs typo

- contrib/datadog/tracing/interceptor.go
- contrib/datadog/tracing/interceptor_test.go
- contrib/opentelemetry/tracing_interceptor.go
- interceptor/tracing_interceptor.go
- internal/interceptortest/tracing.go
- test/activity_test.go
- test/integration_test.go
- test/workflow_test.go
Support updates in tracing interceptor
closes https://github.com/temporalio/sdk-go/issues/1588
> Support updates in tracing interceptor

- internal/internal_workflow_client.go
- test/worker_versioning_test.go
Address TestWorkerVersioningTestSuite/TestReachabilityVersions and TestIntegrationSuite/TestWorkflowExecutionUpdateDeadline.
> Address flaky tests

- temporalnexus/link_converter.go
Mark Nexus link converter functions as experimental
1. Closes 
> Mark Nexus link converter functions as experimental

- internal/version.go
> Release Go SDK v1.29.0

- test/nexus_test.go
Forgot to remove these lines of code before merging #1637.
> Remove DISABLE_NEXUS_TESTS env var from test code

- client/client.go
Expose ScheduleDescription to the public API
Customer asking to use it for unit testing
1. Closes 
> Expose ScheduleDescription

- internal/client.go
> Document Update-with-Start incompatible options

- internal/version.go
> Release Go SDK v1.30.0

- internal/version.go
Bumped SDK version to `1.30.1`
> Bump SDK version to 1.30.1

- internal/version.go
Change SDKVersion for release v1.32.0
> Bump SDKVersion to 1.32.0

- internal/internal_schedule_client.go
- internal/schedule_client.go
- test/integration_test.go
Title
Enabling feature, needed for complete metadata experience
1. Closes 
Upgraded IT
> Expose user metadata fields on scheduling workflows

- internal/internal_task_pollers.go
Changed a warning log to more accurately describe when it's logged
Users were confused why previous log was being logged, based off of its description.
1. Closes 
No code logic changed
> Clarify warning log on local activity deadline

- internal/internal_task_handlers.go
- test/go.mod
- test/integration_test.go
- test/workflow_test.go
Enable speculative workflow task with commands now that CLI 1.2.0 is released
> Enable speculative workflow task with commands

- internal/internal_workflow_client.go
- internal/internal_workflow_client_test.go
A user reported that their UwS requests were error-ing with "context deadline exceeded". This change sets the grpc deadline correctly.
It's a bug.
1. Closes 
> Fix Update-with-Start grpc deadline

- internal/workflow.go
- test/nexus_test.go
Closes https://github.com/temporalio/sdk-go/issues/1476
> Fail Nexus Operation for incompatible input type

- internal/workflow_testsuite.go
- internal/workflow_testsuite_test.go
add in missing ellipses for `args`
All other UpdateWorkflow calls support passing in multiple args
1. Closes 
added test
> Fix UpdateWorkflowByID variadic function

- internal/version.go
> Release Go SDK v1.33.0

- internal/client.go
Fixes https://github.com/temporalio/sdk-go/issues/1757
Remove `WithStartOperation` from docs.
Does not exist anymore.
1. Closes 
> Remove WithStartOperation from docs

- internal/cmd/build/main.go
- temporalnexus/operation.go
- test/nexus_test.go
Basically, revert https://github.com/temporalio/sdk-go/pull/1845.
1. Closes 
> Unblock using conflict policy UseExisting for Nexus WorkflowRunOperation

- workflow/workflow.go
> Fix broken docstring

- internal/client.go
- internal/internal_worker.go
- internal/internal_workflow_client.go
- internal/internal_workflow_client_test.go
closes https://github.com/temporalio/sdk-go/issues/1880
> Make sure GetSystemInfo uses client timeout

- internal/version.go
> Release Go SDK v1.33.1

- internal/version.go
> Release Go SDK v1.34.0

- internal/workflow.go
> Make doc comment name match code name

- internal/internal_task_handlers.go
- internal/internal_task_handlers_test.go
- internal/internal_workflow_testsuite.go
- internal/workflow.go
- test/integration_test.go
- test/workflow_test.go
Add root workflow execution to workflow info
closes https://github.com/temporalio/sdk-go/issues/1848
> Add support for root workflow execution to workflow info

- internal/internal_schedule_client.go
Don't try to encode possibly nil summary fields
1. Closes https://github.com/temporalio/sdk-go/issues/1940
> Fix trying to decode nil summary fields

- temporalnexus/operation.go
Set Nexus links in the callback
All links from the Nexus request must be associated with the Nexus callback.
1. Closes 
> Set Nexus links in the callback

- contrib/tools/workflowcheck/determinism/checker.go
- contrib/tools/workflowcheck/determinism/reason.go
- internal/error.go
- internal/headers.go
- internal/internal_flags.go
- internal/internal_task_handlers.go
- temporal/error.go
- test/integration_test.go
- workflow/context.go
- workflow/doc.go
- workflow/session.go
- improve comments in various packages
- fix typos and correct wording
> Fix grammar in comments

- internal/workflow.go
Mark Nexus operation cancellation type as Experimental.
> Mark Nexus operation cancellation type as Experimental.

- internal/internal_worker_deployment_client.go
- internal/worker_deployment_client.go
> Fix missed spot w/ versioning string

- internal/version.go
> Release Go SDK v1.35.0

- temporalnexus/token.go
- temporalnexus/token_test.go
Omit version token if empty
closes https://github.com/temporalio/sdk-go/issues/1997
> Omit version token if empty
