temporalio/sdk-go

internal/internal_utils.go

Since server is on vanilla gRPC now, YARPC headers are not needed.

Remove YARPC headers

---

go.sum
internal/internal_coroutines_test.go
internal/internal_workflow_testsuite_test.go
internal/workflow.go
workflow/deterministic_wrappers.go

Added `workflow.AwaitWithTimeout` which allows to wait for a condition up to specified timeout.
Added back `TestAwait` and `TestAwaitCancellation` unit tests that got missing during a merge.
Added `TestAwaitWithTimeoutNoTimeout`, `TestAwaitWithTimeoutCancellation` and `Test_AwaitWithTimeoutTimeout` unit test.

Added workflow.AwaitWithTimeout

---

evictiontest/workflow_cache_eviction_test.go
go.mod
go.sum
internal/activity_test.go
internal/client.go
internal/common/metrics/service_wrapper.go
internal/common/metrics/service_wrapper_test.go
internal/common/rpc/error_wrapper.go
internal/common/rpc/error_wrapper_test.go
internal/internal_event_handlers.go
internal/internal_retry.go
internal/internal_task_handlers.go
internal/internal_task_handlers_test.go
internal/internal_worker.go
internal/internal_worker_interfaces_test.go
internal/internal_worker_test.go
internal/internal_workers_test.go
internal/internal_workflow_client.go
internal/internal_workflow_client_test.go
internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
internal/worker.go
test/integration_test.go

1. Updated to latest `temporal-proto` module.
2. Created `workflowServiceErrorWrapper` which converts gRPC status error to service error.
3. Replaced `status.Status` with `serviceerror` everywhere in the code.

Switch to serviceerror package

---

go.mod
go.sum
internal/common/rpc/error_wrapper_test.go
internal/internal_workflow_client_test.go

Renamed in temporal-proto and temporal-proto-go already. This is just to sync these changes.

Rename errordetails to failure

---

internal/internal_worker.go

If `i` is a string already, it should be used as is.

Fix getFunctionName

---

client/client.go
internal/client.go
internal/internal_worker_interfaces_test.go
internal/internal_workflow_client_test.go
internal/internal_workflow_testsuite_test.go
test/integration_test.go

client.StartWorkflowExecution is redundant with client.ExecuteWorkflow and periodically causes confusion of which one should be used.

Removed StartWorkflowExecution

---

evictiontest/workflow_cache_eviction_test.go
internal/client.go
internal/error_test.go
internal/internal_task_handlers.go
internal/internal_worker.go
internal/internal_worker_interfaces_test.go
internal/internal_worker_test.go
internal/internal_workers_test.go
internal/internal_workflow_client.go
internal/internal_workflow_client_test.go
internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
internal/worker.go
internal/workflow_testsuite.go
test/integration_test.go
worker/worker.go

`worker.NewWorker` now depends on `client.Client` interface. It doesn't create/close own gRPC connection but uses client connection instead.
I had to make few short term shortcuts which I described below.

Worker uses client to make a connection

---

docker/buildkite/docker-compose-local.yml

bringing docker-compose-local file up to date with the current image naming convention.

updating temporalio/auto-setup image name in docker-compose-local.yml

---

internal/internal_worker.go
internal/internal_workflow_testsuite_test.go
test/fixtures/activity.cancel.sm.repro.json
test/integration_test.go
test/workflow_test.go

Makes possible the following trick:
```
type Activities struct {
...
}
func (a *Activities) RetryTimeoutStableErrorActivity() error {
...
}
```
And inside the workflow:
```
var a *Activities
err := workflow.ExecuteActivity(ctx, a.RetryTimeoutStableErrorActivity).Get(ctx, nil)
```
This is possible as Go allows nil function receivers.

Added ability to call method activities by function pointer

---

internal/internal_task_handlers.go
internal/internal_task_handlers_test.go
internal/internal_worker.go
internal/internal_worker_test.go
internal/internal_workflow_testsuite_test.go
internal/worker.go
worker/worker.go

The NonDeterministicWorkflowPolicy is confusing as this policy applies to all panics in the workflow code including dereferencing a nil pointer for example.

Renamed NonDeterministicWorkflowPolicy to WorkflowPanicPolicy

---

internal/context.go
internal/interceptors.go
internal/internal_coroutines_test.go
internal/internal_task_handlers_test.go
internal/internal_worker.go
internal/internal_workflow.go
internal/internal_workflow_test.go
internal/internal_workflow_testsuite_test.go
internal/session.go
internal/workflow.go
workflow/deterministic_wrappers.go
workflow/workflow.go

Native Go channels support read only and write only interface.
To match that break `Channel` into `WriteChannel` and `ReadChannel` (naming is up to discussion).
Change `getSignalChannel` to return `ReadChannel` as ability to write and close the signal channel is a common topic for confusion.

Broke channel into WriteChannel and ReadChannel interfaces

---

go.mod
go.sum
internal/error_test.go
internal/headers.go
internal/headers_test.go
internal/internal_workflow.go
internal/internal_workflow_client.go
internal/internal_workflow_client_test.go
internal/internal_workflow_testsuite_test.go
internal/tracer.go
internal/tracer_test.go
internal/workflow.go

Last replacement of `bytes` with `Payload` according to https://github.com/temporalio/temporal/issues/107.

Convert Header message to use Payload

---

encoded/encoded.go
go.mod
go.sum
internal/encoded.go
internal/error_test.go
internal/headers.go
internal/headers_test.go
internal/internal_event_handlers.go
internal/internal_event_handlers_test.go
internal/internal_task_handlers_test.go
internal/internal_workflow.go
internal/internal_workflow_client.go
internal/internal_workflow_client_test.go
internal/internal_workflow_test.go
internal/internal_workflow_testsuite_test.go
internal/tracer.go
internal/tracer_test.go
internal/workflow.go
test/replaytests/version.json
test/replaytests/version_new.json
test/workflow_test.go

`SearchAttributes`, `Memo`, and `Headers` always have single encoded value. There is no reason to use `Payloads` there.

Use Payload for SearchAttributes, Memo, and Headers

---

client/client.go
internal/client.go
internal/grpc_dialer.go

Removing GRPCDialer - we will later introduce an object that settings would be set on and we would apply against our defaults.

Remove GRPCDialer

---

internal/client.go
internal/grpc_dialer.go

This change exposes a new object in ```ClientOptions``` to SDK consumers - ```ConnectionOptions```; this object will be used to support additional connection scenarios, rather than supporting direct creation control of grpc dependencies.
Initially, TLS configuration is the only supported option; this takes in a golang `tls.Config` leaving complete control up to users.

Add ConnectionOptions, Support TLS

---

internal/version.go

This will prevent customer from using old server versions with new SDK.

Bump SDK version

---

internal/session_test.go

Added missing ScheduleToCloseTimeout. Without it test takes very long.

Fixed unit test retry timeout

---

client/client.go
internal/client.go
internal/internal_retry.go
internal/internal_task_pollers.go
internal/internal_worker.go
internal/internal_worker_base.go
internal/internal_workers_test.go
internal/internal_workflow_client.go
internal/worker.go
mocks/Client.go
mocks/NamespaceClient.go
test/integration_test.go
worker/worker.go

1. Rename `CloseConnection` to `Close`,
2. Rename leftover `Shutdown` to `Stop`,
3. Fix comments.

Rename CloseConnection to Close

---

error.go
test/workflow_test.go
workflow/workflow.go

Removed reference from temporal package to workflow. It is needed as RetryPolicy needs to be referenced from workflow package creating cycle.

Moved continueAsNewError to workflow

---

internal/error.go
internal/error_test.go

If error was created from failure this original failure will be stored inside error and then used to serialize back to failure. This will persist fields which go code is not aware about (like `StackTrace` for `ApplicationFailureInfo`).

Store original failure in error

---

Makefile
internal/internal_task_handlers_interfaces_test.go
internal/internal_task_pollers.go

Run `go vet ./...` to detect possible context leaks.

Call cancel on context to prevent memory leak

---

internal/common/backoff/retry_test.go

Test passes on my local machine but fails in CI/CD:
Adding more time to prevent flakiness.

Increase timeout values to prevent test flakiness

---

error.go
internal/error.go
internal/error_test.go
internal/internal_task_handlers.go
internal/internal_task_handlers_interfaces_test.go
internal/internal_task_pollers.go
internal/internal_utils_test.go
internal/internal_worker_test.go
internal/internal_workflow_client_test.go
internal/internal_workflow_testsuite_test.go
internal/session.go
internal/workflow.go
test/activity_test.go

`NewApplicationError` now has `type` argument which allows to specify error type explicitly. Use `temporal.ApplicationErrorType` for default type.
Plus few renames:
1. Field `originalType` -> `errType`
2. Func `OriginalType()` -> `Type()`

Add type argument to NewApplicationError constructor

---

encoded/encoded.go
internal/encoded.go
internal/encoded_test.go

Adds `ToString` to `DataConverter` interface and `defaultDataConverter` so that a caller can get a "prettified" version of the `Payloads` as `string`, which can be useful for things like looking at heartbeat details and logging.

Add ToString to DataConverter

---

internal/internal_utils.go
internal/internal_worker.go
internal/internal_worker_base.go
internal/internal_worker_test.go
worker/worker.go

Following code block:
```
w := worker.New(c, "hello-world", worker.Options{})
err = w.Run()
```
becomes:
```
w := worker.New(c, "hello-world", worker.Options{})
err = w.Run(worker.InterruptCh())
```
and it will wait for `Ctrl+C` or
```
w := worker.New(c, "hello-world", worker.Options{})
err = w.Run(nil)
```
and it will wait for `w.Stop()` call.
Or you can pass any `<-chan interface{}` and `Run` will stop the worker as soon as there is a signal in the channel.
Closes #94.

Extract InterruptCh func

---

client/logger.go
internal/internal_worker.go

If logger is not passed to `WorkflowReplayer` funcs, `DefaultLogger` will be used.

Use DefaultLogger instead of NopLogger in WorkflowReplayer funcs

---

internal/encoded.go
internal/encoded_test.go

It is a way easier to use `ToString()` when it returns just string.

ToString should not return error

---

internal/workflow.go
test/workflow_test.go

- Eliminates the setting of "2" as the default backoff co-efficient as the server does this.
- Updates the ChildWorkflowRetryOnTimeout test as retries now get exhausted when the WorkflowExecutionTimeout lapses (which was not occurring prior to the server fix)

Updates GO SDK to align with fixed Temporal Server Behavior for Child Workflow retries and timeouts

---

internal/internal_task_handlers.go
internal/internal_task_handlers_test.go
test/activity_test.go
test/integration_test.go
test/workflow_test.go

- As part of switching from variables representing time in seconds to time.Duration, we forgot to correctly update the line of code that calculates the interval for sending the next heartbeat. We were multiplying by an extra factor of one billion, which either caused an overflow (so that we were constantly sending heartbeats) or resulted in a large number (where we would never send a heartbeat after the first one).
Testing:
- Modified unit-test to validate that timer is fired and heartbeat is reported at least a second time.
- Added an integration test for a long-running activity with a smaller heartbeat timeout.

Fix regression in Go SDK where Batch Timer interval for heartbeats is overcalculated

---

activity/activity.go
activity/doc.go
client/client.go
internal/activity.go
internal/client.go
internal/context.go
internal/internal_task_handlers.go
internal/internal_task_pollers.go
internal/internal_time.go
internal/internal_worker_test.go
internal/internal_workflow.go
internal/internal_workflow_client.go
internal/internal_workflow_client_test.go
internal/internal_workflow_test.go
internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
internal/session.go
internal/workflow.go
internal/workflow_testsuite.go
temporal/error.go
workflow/context.go
workflow/session.go

Let's use US form everywhere: https://www.dictionary.com/e/canceled-vs-cancelled/.

Rename cancelled to canceled for consistency

---

internal/internal_workflow.go
test/integration_test.go
test/workflow_test.go

Adding integration tests to check if `SignalWorkflow` works for primitive types and proto objects.
https://community.temporal.io/t/sending-proto-messages-directly-over-signal-channels/441/3

Add integration test for SignalWorkflow

---

Makefile
test/workflow_test.go

1) Address flakiness in ActivityHBTimeout Test:
The test was validating that the full 5 seconds of the schedule-to-close time had elapsed before the activity failed.
This is actually incorrect as we will abort the retry early if the current time + current_retry_interval exceeds the schedule-to-close deadline. As a result, this could cause flakiness as the activity would fail after 4+ seconds (not bother doing the last retry since that would exceed the overall deadline). Fixes this to change the threshold to remove the maximum interval
2) Addresses flakiness in overall integration test:
The overall integration test timeout was 2 minutes. We've added new tests since that time and now we are running up against the limit on certain environments. Increasing the timeout to 3 minutes to account …

Fixes flaky integration-tests

---

internal/client.go
internal/grpc_dialer.go
internal/internal_task_pollers.go
internal/internal_utils.go

When connection to server is lost and then restored it might take up to 120 seconds for the client to make a successful request due to internal gRPC reconnect implementation. This PR changes this default to 10 seconds and tunes few other timeouts.

Tune gRPC connection timeouts

---

internal/internal_event_handlers.go
internal/internal_task_handlers.go

- Code to proactively cleanup loaded history during pagination was not actually reducing memory pressure as the underlying slice does not shrink when taking sub-slices.
- Holding onto side effect payloads after they have been processed provides no benefit and just eats memory. We can just delete the entry once we've served the SideEffect value.

Fixes memory leaks found during stress testing

---

internal/internal_worker.go
internal/internal_worker_test.go
internal/worker.go

Issue: This worker option throttles the rate at which we process tasks. Unfortunately, this option does not disambiguate between tasks received from the Worker's task queue and tasks received from the Global queue. As a result, a user setting this to a low value can have the unintended consequence of throttling the wrong type of tasks (throttling sticky tasks is bad since those are significantly cheaper to process as all the state needed to process the workflow task is already in memory).
Long-term, we should introduce two separate knobs (one for the Worker task queue and one for the Global task queue). For now, we will just have this not be configurable by the user and go with a default of 100,000.

Remove WorkerWorkflowTasksPerSecond WorkerOption

---

go.mod
go.sum
internal/client.go
internal/internal_utils.go
internal/version.go

Change GoSDK headers to match with upcoming server change. This change is backward compatible because both old and new servers accept client if headers are missing.

Change client/server version support

---

internal/common/metrics/constants.go
internal/common/metrics/request_scope.go
internal/common/metrics/utils.go
internal/internal_task_handlers.go
internal/internal_task_pollers.go
internal/internal_worker.go
internal/internal_workflow_client.go

Root scope is initialized with all tags needed for rpc calls.  This guarantees 
that any rpc invocation will have all same tags and now we don't have to 
explicitly initialize grpcContext with Empty rpc tags on each invocation.

Initialize root scope with all rpc tags

---

internal/context.go
internal/error.go
internal/error_test.go
internal/internal_event_handlers.go
internal/internal_utils_test.go
internal/internal_workflow_client.go
internal/internal_workflow_client_test.go
internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
temporal/error.go
test/integration_test.go

Remove duplicate information from failure messages and add more context to go error messages.

Improve error messages

---

converter/composite_data_converter.go
converter/default_data_converter.go
internal/client.go
internal/error_test.go
internal/headers.go
internal/headers_test.go
internal/internal_task_handlers.go
internal/internal_task_pollers.go
internal/internal_workflow.go
internal/internal_workflow_client_test.go
internal/internal_workflow_testsuite_test.go
internal/tracer.go
internal/workflow_testsuite.go
test/activity_test.go
test/integration_test.go
test/test_utils_test.go
test/workflow_test.go

This PR fixes bug: when custom context propagators are set, custom tracer stops to work (stops to propagate span headers).
First, I added an integration test for two context propagators to make sure they work together. This test passed fine and didn't discover the problem. Then, after some debugging, I figured out that there was an error during deserialization of tracer headers from headers payload. The proper fix is to store entire tracing data as single header and let opentracing to deal with it content.
Note: because header key is changing, workflows started with previous SDK versions will not propagate trace to this version and vice versa.
Tested manually with local Jaeger installation.

Fix custom tracer header propagation

---

README.md

There isn't an obvious replacement for the broken link so pointed it at the top-level page for the SDK docs.

Update broken link to Go quickstart

---

internal/internal_workflow_testsuite_test.go
internal/workflow_testsuite.go

Add support for mocking activity mock panicking as:
```
env.OnActivity(testActivityHello, mock.Anything, mock.Anything).Panic("mock-panic")
```
Helps to test that activity shouldn't be called.

Added mock Call.Panic

---

go.sum
internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go

`RecordActivityHeartbeat` wasn't able to complete successfully when Activity is running inside `TestActivityEnvironment` due to missing handle registration.

Set activity handle in testWorkflowEnvironment

---

converter/errors.go
converter/json_payload_converter.go
converter/nil_payload_converter.go
converter/payload_converter_test.go
converter/proto_json_payload_converter.go
converter/proto_payload_converter.go
converter/reflect.go
go.sum

When Activity/Workflow parameter is a proto object, it had to be a pointer (because `proto.Message` is implemented on pointer receiver only), and now non-pointers are also supported (thanks to reflection magic):
```
ai := datapb.AccountInfo{...} // not &datapb.AccountInfo{...}
f := workflow.ExecuteActivity(ctx, "MakeTransaction", ai)
var tr datapb.TransactionResult // not *datapb.TransactionResult
f.Get(&tr)
```

Add support for non-pointer proto struct

---

internal/headers.go
internal/headers_test.go

It turned out that `header` can be `nil` on request (for example request which came from `tctl`) and it is a valid case. There is no reason to panic on it but return "missing header" response instead.

Replace panic in headerReader with nil return

---

internal/internal_event_handlers.go
internal/internal_logging_tags.go
internal/internal_task_handlers.go
internal/internal_task_handlers_test.go
internal/internal_worker.go
internal/internal_workflow.go
internal/worker.go
test/integration_test.go
test/replaytests/replay_test.go
test/workflow_test.go

Fail workflow task if a workflow goroutine doesn't yield for a second. This indicates a bug in the workflow code implementation. 
Fixes https://github.com/temporalio/sdk-go/issues/59

Deadlock detector

---

internal/common/util/once_cell.go
internal/common/util/once_cell_test.go
internal/internal_workflow_client.go
internal/internal_workflow_client_test.go

Resolves https://github.com/temporalio/sdk-go/issues/272
I'm not totally sure this is the way we want to go about this, though, so would very much appreciate feedback on the approach. I left some detail in a comment.

Fix GetWorkflow to provide latest run id if none was provided to it

---

internal/internal_task_handlers.go
test/integration_test.go
test/workflow_test.go

Fixes regression introduced by Deadlock Detection PR:
1) A workflow task execution that exceeded 1 second causes a panic.
2) If the task execution was spawned by the completion of a local activity, that would always fail the Workflow.
This fix alters the code to respect the WorkflowPanicPolicy, even in the case where the panic occurs during Local Activity Result completion. It also adds an integration test to exercise this path.

Fixes issue where a deadlock detected via a Workflow Execution resumed from a Local Activity Completion fails the Workflow

---

internal/internal_task_handlers.go
internal/internal_task_pollers.go

1) Increases Local Activity Tunnel size from 1000 to 100,000 to reduce the chance of a deadlock occurring because the thread that go-routine that drains local-activity results is blocked on sending to the local activity tunnel channel. This is a stop-gap solution. A better solution will be followed up with, but this is a single channel for the entire worker, so the extra memory usage should be relatively trivial
2) Adds special case logic for handling heartbeat delay duration being less than zero as the timer.After() channel is not always reliably firing even when duration has reached or gone below zero. Now, we always do a check on the duration before the select statement.

Fixes additional deadlock issues with respect to local activities

---

internal/common/util/util.go
internal/internal_task_handlers.go
internal/internal_utils.go
internal/internal_workflow.go

See this article for an example on when time.After may not be optimal for memory usage purposes: https://medium.com/@oboturov/golang-time-after-is-not-garbage-collected-4cbc94740082
For workflows with a lot of local activities, we will end up unnecessary allocating a whole bunch of timers rather than re-using the same heartbeat one on successive loops. This swaps out time.After() with time.NewTimer() and then explicitly stops the timer when we are done using it.

Replaces time.After() usage with time.NewTimer() to reduce memory pressure due to allocated timers

---

go.mod
go.sum
internal/activity_test.go
internal/internal_task_handlers.go
internal/internal_task_handlers_test.go
internal/internal_task_pollers.go
internal/internal_workflow_client.go
internal/internal_workflow_testsuite.go

Set namespace fields on async task completion and heartbeat requests, so that it could be compared on the server with namespace in the token and/or those calls could be authorized on a namespace basis.

Set namespace field in async task completion and heartbeat requests

---

internal/internal_task_handlers.go
internal/internal_task_handlers_test.go
internal/internal_task_pollers.go
test/activity_test.go
test/integration_test.go
test/workflow_test.go

Depends on https://github.com/temporalio/sdk-go/pull/302 being merged first
Relates to https://www.notion.so/Go-SDK-Nil-Reference-Panic-in-Bench-Test-b240b5f0db3b4d8088e3486939a53e78
~It appears my fix in the MR this one depends on also fixes this item. I wasn't able to repro the issue after a variety of bench runs.~ Not quite. Will require a bit of extra fix.

Fix spurious nil derefs on retrying local activities

---

internal/internal_task_handlers.go
internal/internal_task_pollers.go
test/activity_test.go
test/workflow_test.go

Relates to https://www.notion.so/temporalio/Unexpected-Non-Deterministic-error-when-running-go-cancellation-bench-test-e507f3b686bf41bfa24c3fd6200c570a
The initial fix wasn't working quite right, and could lead to goroutines getting stuck trying to populate the retry channel. This changes initialization to be just like the result channel, fixing that problem.

Retry channel wasn't being initialized properly - fix that.

---

internal/internal_worker.go
internal/internal_worker_test.go
internal/worker.go
test/integration_test.go

Similarly to [this change in Java SDK](https://github.com/temporalio/sdk-java/pull/276) this PR addresses #284 adding ability to set `LocalActivityWorkerOnly` flag in the worker options in order to avoid starting activity and session workers.
This allows running local activity workers only without any overhead for activity polling.

Adding an option to allow starting local activity worker only

---

internal/error.go
internal/error_test.go
internal/internal_task_handlers.go
internal/internal_workflow_test.go
internalbindings/internalbindings.go

Removed unnecessary fields from ContineAsNewError and exposed it through internalbidings package.
This was requested by SDK-PHP project.

Cleanup of ContinueAsNewError

---

internal/internal_workflow.go
test/integration_test.go

Similarly to [this change](https://github.com/temporalio/sdk-java/pull/296) in the Java SDK, we are adding debug mode, which can be activated by setting `TEMPORAL_DEBUG` environment variable.
In this mode deadlock detector will be disabled.

Adding debug mode

---

converter/default_data_converter.go

This PR enabled proto converter by default. This enabled accepting proto payloads on Golang without affecting the ability to serialize proto messages.
Write:
- Only first proto converter will be used, same behaviour as previously.
Read:
- Now Golang SDK can parse payloads sent in proto/binary format while previously it was turned off.

Enable proto converted by default

---

workflow/workflow.go

This adds a helper method to check if it is a continue as new error. I don't see any use cases aside from testing, so happy to close - or happy to put elsewhere. Made this practically copy-paste of temporal.IsCanceledError but I see that this can't exist in `temporal` for cyclic dependency reasons.

[Testing] Add IsContinueAsNewError For Checking Errors in Tests

---

internal/internal_decision_state_machine.go
internal/internal_workflow_testsuite_test.go
test/integration_test.go
test/workflow_test.go

Everyone's favorite bug, back again in a tasty new flavor. Fix was simple, what was happening is in fact acceptable and we just needed to say so.
Closes #343

Fix child workflow cancel invalid fsm transition

---

internal/common/metrics/constants.go

This brings our metric tags in conformance with prometheus naming conventions.

Rename task queue metric tag

---

internal/internal_decision_state_machine.go
internal/internal_decision_state_machine_test.go

This fix handles another cancellation event ordering that can trigger state machine failures.
Fixes https://github.com/temporalio/temporal/issues/1218

Yet further unusual cancellation event ordering fixes

---

internal/internal_worker.go

Without this, an invalid struct can be partially registered in tests or in workers, which can lead to weird failure when activities are missing but unknown as to why they are missing.
Combines with #360 for solving #356.

Panic when Invalid Struct is Registered

---

internal/activity.go

But, seemingly this should not happen at all. Worth investigating why server side may not have populated this.

Fixes a possible panic when server resp is missing workflow type

---

converter/data_converter_test.go
converter/json_payload_converter.go
converter/payload_converter_test.go
converter/proto_json_payload_converter.go

`ToString` is used for debugging and by `tctl`. I recently discovered that default numeric type is `float64` and long ints end up being `1.6137007538525565e+18` in string representation. I believe just raw JSON will suit better here.

Use raw JSON to convert payload to string

---

internal/internal_event_handlers.go

some libs (both grpc and @grpc/grpc-js) fail to process `Payloads` equal to `nil`. This sets `Payloads` to empty array instead of nil

Set Local Activity result to empty not nil

---

internal/client.go
internal/grpc_dialer.go
internal/grpc_dialer_test.go

Adds ability to set `HeadersProvider` on `ClientOptions` during `Client` creation, which will be invoked in the gRPC interceptor on all outgoing calls.
Users can now implement HeadersProvider interface:
```
HeadersProvider interface {
GetHeaders(ctx context.Context) (map[string]string, error)
}
```
and set authorization or any other headers that backend expects to see.
This solution is a slight refinement of #363, in my opinion we should try to not expose gRPC types to the end user because other newer language SDKs (JavaScript and beyond) will not have direct access to the gRPC layer, which will be done in the core rust sdk.
Another option that I've considered was adding ability to set headers on the `ClientOptions` and adding ability to modify them from the `Client`. But I didn't like …

Adding support for custom gRPC headers

---

internal/grpc_dialer.go

Previously workers were getting "stuck" after we upgraded our test cluster.
This could happen if server side dies and doesn't close connection gracefully resulting in client-side connection hanging until TCP times out in 10+ minutes.
This change introduces [keep alive] check into our client, which should help detect orphaned connections faster.

Add keep alive to gRPC connection

---

internal/client.go
internal/grpc_dialer.go

This approach should make it safer for our users and allow us time to test the feature before we enable it by default.

Make keep alive configurable and opt-in

---

internal/internal_decision_state_machine.go
internal/internal_task_handlers_test.go
internal/internal_worker_test.go
internal/internal_workflow_testsuite_test.go

Fixes https://github.com/temporalio/sdk-go/issues/374
When executing a side effect after calling `GetVersion`, command ids could end up ordered incorrectly. This change fixes that issue by ensuring that every time a command is added, some special-case code regarding version markers is run.

Fix panic when handling version & side effect markers together

---

converter/proto_payload_converter.go

What was changed:
Fix proto payload conveter selection logic.
Motivation & Context:
`ProtoPayloadConverter` was wrongly chosen for the types with `Marshal() ([]byte, error)` method.
Run existing tests.

Fix proto payload conveter selection logic

---

internal/client.go
internal/workflow.go

Changed WorkflowRunTimeout default comment to unlimited
The old version of the service used 10 years as default. The new versions of the service use unlimited value.

Fixed WorkflowRunTimeout default value comment

---

internal/activity.go

Updated ActivityOptions.ScheduleToStartTimeout comment to match the current service implementation.

Updated ActivityOptions.ScheduleToStartTimeout comment

---

internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
internal/workflow_testsuite.go

Implements the possibility of querying child workflows by ID in the test workflow environment
missing feature
https://github.com/temporalio/sdk-go/issues/390
basic unit test included
I can't find detailed docs on the exposed Testing framework features and functions at this time

Add QueryWorkflowByID to TestWorkflowEnvironment

---

internal/workflow.go
internal/workflow_testsuite_test.go

The change replicates the behavior of `ExecuteActivity` for `ExecuteLocalActivity` to allow executing local activities by supplying funcs or func names.
In the process, `ExecuteLocalActivity` is using the activity registry to lookup the activity function by name when needed.
~One question I have is that this could be potentially considered a breaking change because right now, it seems local activities executions don't seem to rely on the registry meaning that potentially, you don't have to register local activities in your worker? I still have to test if that is true and if so, if this is a documented behaviour.~ It seems that's indeed the case [when I look at tests](https://github.com/temporalio/sdk-go/blob/master/internal/internal_task_handlers_test.go#L1237-L1239). 
This PR attempts to …

Support executing local activities by name

---

internal/activity.go
internal/workflow.go

What was changed:
Fixed documentation of activity timeouts and workflow task timeout.
Why?
Documentation was outdated and confusing.

Updated Timeout Property Documentation

---

internal/client.go
internal/grpc_dialer.go

Add gRPC Authority connection option.
gRPC Authority is used for routing in certain scenarios. This is a safe change as gRPC enforces that authority can only be overridden in insecure mode.
Integration and unit tests.

Add gRPC Authority connection option

---

go.mod
go.sum

I've updated `go.temporal.io/api` to the latest commit (command below) to bring in a recent schema change introduced in https://github.com/temporalio/temporal/pull/1462 
```
go get -v -u go.temporal.io/api@6f00f7f9837370a4bad2cd9094326cfd71cc7f49
```
This should allow clients to access the new Reason field when encountering a PermissionDenied errors.

Updating api-go to bring in permission denial reasons

---

internal/internal_event_handlers.go
internal/internal_task_handlers_test.go
internal/internal_worker_test.go

This PR addresses a bug described in https://github.com/temporalio/sdk-go/issues/411.
Main issue there is that in case if child workflow fails to start, execution future doesn't get resolved, this means that code like:
```
workflow.ExecuteChildWorkflow(...).GetChildWorkflowExecution().Get(ctx, nil)
```
would block forever, at the same time call on the main future would have succeeded:
```
workflow.ExecuteChildWorkflow(...).Get(ctx, nil)
```
In order to address this we should unblock startedCallback when we receive failed to start error. Trickily enough, this error was misbehaving only in real code, while our test environment [was already invoking this callback](https://github.com/temporalio/sdk-go/blob/429a4a9c4d70a60d7caa52e49484932a8fec702f/internal/internal_workflow_testsuite.go#L2047)

Invoke startedCallback when child workflow failed to start

---

internal/internal_retry.go

Adds `serviceerror.PermissionDenied` to list indicating if an error should not be retried. 
Currently, PermissionDenied errors will be retried until the context times out and clients will not see the true surfaced error.

Adds PermissionDenied service error to list of non-retryables

---

internal/internal_workflow_testsuite_test.go
internal/workflow_testsuite.go

Added to the `MockCallWrapper` a way to specify that we expect Zero calls to the activity.
This can be helpful to test workflows with branches.
1. Closes issue: #427 
2. How was this tested: Unit test added

Ability to verify when an activity should not be called

---

internal/client.go

During creation of the client, if we successfully create a gRPC connection, but cannot validate the health check, we error out without actually closing the gRPC connection. This results in a temporary leak. This PR fixes that leak.

Fixes leak if client is able to open gRPC connection to server, but health check subsequently fails.

---

internal/internal_decision_state_machine.go
internal/internal_event_handlers.go
internal/internal_worker_test.go
internal/internal_workers_test.go

If local activity function doesn't have return value (returns only `errror`) `lar.result` is `nil` and it shouldn't be added to the marker data. 
Closes #421.
Related to #365.

Don't add local activity result to the marker if local activity doesn't have return value

---

internal/internal_activity.go
internal/internal_task_handlers.go
internal/internal_worker.go
internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
internal/workflow.go
test/workflow_test.go

Added ability to call local activity using nil struct pointer:
```go
var activities *Activities
err := workflow.ExecuteLocalActivity(ctx, activities.Function).Get(ctx, nil)
```
It is already supported for normal activities and allows using struct implementation for the local ones.
1. Closes issue: 
https://github.com/temporalio/sdk-go/issues/424
Unit tests updated to cover the legacy and the new way to call local activities.
Yes. The Go SDK needs to be updated to demonstrate this pattern for both normal and local activities.

Added ability to call local activity using nil struct pointer

---

internal/workflow_testsuite.go

Updated docstring
Queries with zero delay to a workflow can't really be performed in a real situation, and aren't supported in the unit testing framework. Make that more clear.
1. Closes issue: 
#433 

Indicate RegisterDelayedCallback with 0 delay does not work with queries

---

internal/common/backoff/retry.go
internal/common/backoff/retry_test.go
internal/common/backoff/retrypolicy.go

Usually, after number of retry attempts, last attempt fails with `DeadlineExceeded` error. It is not informative and actual error reason is in the error occurred on previous attempt. Return this `lastErr` instead of `DeadlineExceeded` error provides a better user experience.

Filter out DeadlineExceeded error in retry

---

internal/internal_worker.go
internal/internal_worker_test.go

Resolves #447 by raising a panic in case if start was attempted after worker was stopped.
To achieve this we don't even need a new variable as we can check if stop channel is still open.
This brings go in compliance with java, which [already has](https://github.com/temporalio/sdk-java/blob/30420212a26283cf7cbe6339512058a3186074e8/temporal-sdk/src/test/java/io/temporal/workerFactory/WorkerFactoryTests.java#L104) this type of check.

Workers should fail to start if they were stopped before

---

internal/client.go
test/bindings_test.go

Resolves #438 by adding configurable healthcheck timeout for the client.
Default value is set to 10 seconds, which means that now client creation would block sending health check requests in case if server is not available.

Health check retry

---

internal/common/metrics/utils.go
internal/internal_task_handlers.go
internal/internal_task_pollers.go

Resolves #449 by tagging several activity related metrics with the task queue
name. This aligns more closely with the behavior of the Java SDK.

Activity metrics should include task queue name

---

internal/internal_task_handlers.go
internal/internal_workflow_client.go

Fix #437 (minus tests) by making `Unavailable` and other transient errors being propagated as a cancelation to the client code.
I've double checked using cancellation sample that this is indeed an error returned when the server goes down.
Adding an integration test for this scenario is a little tricky though.
I've also changed `cancelHandler` to be invoked on all transient errors that's been retried for the duration of heartbeat timeout.

Propagate cancellation to the client if server is unavailable

---

internal/client.go
internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
internal/session_test.go

Add default retry policy for unit test.
Retry policy is optional, server will use a default retry policy if user does not supply one. Also, fields of retry policy are optional, when not set, server would use default for them. The defaults set by server are:
// The default RetryPolicy provided by the server specifies:
// - InitialInterval of 1 second
// - BackoffCoefficient of 2.0
// - MaximumInterval of 100 x InitialInterval
// - MaximumAttempts of 0 (unlimited)
This works when running against temporal server, but won't work for unit test until now.
close#461
Added new unit test to cover the case.
https://docs.temporal.io/docs/go/retries/
The InitialInterval field of retry policy is not required, the default value is 1s.

Ensure default retry policy in test

---

internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
internal/workflow_testsuite.go

Add ParentClosePolicy to unit test
Properly support ParentClosePolicy in unit test.
1. Closes #470 
New unit tests
No.

Add ParentClosePolicy to unit test

---

internal/internal_decision_state_machine.go
test/replaytests/workflow2.json
test/replaytests/workflows.go

I changed the logic of incrementing `nextCommandEventID` when processing `VersionMarker` events to support having multiple subsequent `VersionMarker` events.
This fixes the issue with workflow panics on replay of a workflow that contains multiple subsequent calls to `GetVersion`.
1. Closes #473 
Updated one of the existing replay tests to have two subsequent calls to GetVersion, without the change in `incrementNextCommandEventIDIfVersionMarker` the test is failing.
No

Fix workflow panic when workflow has multiple GetVersion calls

---

internal/internal_coroutines_test.go
internal/internal_event_handlers.go
internal/internal_task_handlers.go
internal/internal_worker.go
internal/internal_worker_base.go
internal/internal_workflow.go
internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
internal/worker.go
test/bindings_workflows_test.go

Made deadlock detection timeout configurable via WorkerOptions. Default value hasn't changed and is equal to 1 second. `TEMPORAL_DEBUG` environment variable can still be used and will set unlimited deadlock detection timeout IF value is not provided in WorkerOptions.
Initially we thought that there were no valid use cases when workflow tasks could take more than 1 second to run. However some users perform heavy, yet deterministic computations which may sometimes take longer. Making this timeout configurable allows for more flexibility on the user end.
1. Closes #404
Unit tests

Make deadlock detection timeout configurable

---

internal/internal_task_pollers.go
test/integration_test.go

Activity failure doesn't result in error, and previously `temporal_activity_execution_failed` metric hasn't been reported for "normal" failures. This PR fixes it by reporting a metric whenever response type was `RespondActivityTaskFailedRequest`.
Metric was incorrect.
1. Closes #457
unit test

Add missing activity failure metric

---

go.mod
internal/internal_workflow_test.go
internal/workflow.go
test/integration_test.go
test/workflow_test.go

Previously, calls to start a child workflow using an already-cancelled context would still start the child and then immediately cancel it. Now, the child isn't started at all and the future immediately resolves w/ cancelled error.
Starting child workflows with a cancelled context is a nonsense operation
1. Closes https://github.com/temporalio/sdk-go/issues/483
Added UT and IT

Do not allow starting child workflows from an already-cancelled context

---

internal/workflow_testsuite.go

Expose Myabe() on MockWrapper so user can setup optional mocks.
This will make it easier to setup test mocks.

Expose Maybe() on mock calls

---

.buildkite/docker-compose.yml

After https://github.com/temporalio/temporal/pull/1740 `temporalio/auto-setup:latest` points to latest release not latest `master` commit.

Change docker hub repo to temporaliotest

---

internal/internal_coroutines_test.go
internal/internal_workflow.go

Added additional locking to avoid data races.
Data race has occurred when deadlock detector was terminating the call.
1. Closes #488
unit test
no

Fix data race due to deadlock detector

---

internal/common/util/stringer.go
internal/common/util/stringer_test.go

Prevent panic from reflect Interface() method. Prevents the symptom of the panic. This bug should probably handled further upstream.

Prevent panic from reflect

---

internal/internal_worker_base.go

backoff 200ms when poller encounter errors.

Poller backoff a bit more in errors

---

internal/error.go
internal/error_test.go

Resolves #496 by adding field getters for ActivityError, see details in the linked issue.
It's an open question if we should add getters for other error types as well.

Add field accessors for ActivityError

---

internal/internal_workflow_test.go
internal/internal_workflow_testsuite.go

Previously workflows that completed with pending go routines would have those go routines blocked forever causing a leak. This change fixes it.

Allow pending goroutines exit after workflow completion

---

internal/error.go
internal/error_test.go

Reverts temporalio/sdk-go#523
References issue #403 
Reverting due to reasoning brought up by @alexshtin: the current Is() implementation is not sufficient to compare error types without a deep equality. The current implementation simply checks whether the types are the same, not whether the underlying error is the same. The error occurs on line 46 of the [errors source code](https://cs.opensource.google/go/go/+/refs/tags/go1.17:src/errors/wrap.go;l=49).

Revert "Add support for errors.Is()"

---

evictiontest/workflow_cache_eviction_test.go
internal/internal_worker.go
internal/internal_worker_test.go

Do not skip worker start when registry is empty.
There are uses cases where registry happen after worker is started, for example in integration tests that you want to start worker as part of test setup where you don't know what to register yet.
This check only make sense when the registry was done via golang's init() func. Now registry is per worker and can be done after worker is started. The current behavior of silently skip worker start is inconvenient.

Start worker even when no workflow/activity registered

---

internal/internal_task_handlers.go
internal/internal_workflow_testsuite_test.go

Fix local activity retry backoff calculation.
Attempt used to start from 0, then it was changed to start from 1, but backoff calculation wasn't updated accordingly.
1. Closes 

Fix local activity retry backoff

---

internal/internal_worker_test.go

Skipped failing Windows test
Test sends manual interrupt signal which fails. Full suite now succeeds on Windows.

Skip failing test on Windows

---

internal/activity.go
internal/internal_workflow_test.go
internal/workflow.go
test/integration_test.go
test/workflow_test.go

Added default retry policy for local activities.
Previously local activities would rely on workflow task retries in case if policy hasn't been specified. Also since no defaults were applied invalid/partial policy would cause it to use no retries within workflow task.
1. Closes #563
Integration tests
Updated javadocs, we should also update public documentation.

Apply default retry policy for local activities

---

test/integration_test.go

Instead of asserting exact invocation count, just asserted minimal since they rise while also trying to keep in the spirit of the changes in https://github.com/temporalio/sdk-go/pull/256/files#diff-8118e44ac15fb5ab2e2ece2ab52fd23062a10b5cc9c55ee5b3620a1242cff27c, https://github.com/temporalio/sdk-go/pull/455/files#diff-8118e44ac15fb5ab2e2ece2ab52fd23062a10b5cc9c55ee5b3620a1242cff27c, and https://github.com/temporalio/sdk-go/pull/479/files#diff-8118e44ac15fb5ab2e2ece2ab52fd23062a10b5cc9c55ee5b3620a1242cff27c
Introducing 50-100ms latency between server and client causes these tests to fail.
Unable to replicate failure for other flaky tests.
1. Closes #556
2. Closes #547
3. How was this tested:
Adding gRPC interceptor that introduces latency (but unreasonable at this time to commit explicit …

Change assertions on slow server

---

internal/internal_task_pollers.go
test/activity_test.go
test/integration_test.go
test/workflow_test.go

Moved local activity panic handler to where it can be used.
Panics were not handled in local activities.
1. Closes #621

Catch panics in local activities

---

internal/internal_workflow.go
internal/internal_workflow_test.go

A bounds check was done to make sure the start is not after the end when trimming stack indexes.
In #624, a panic trace showed that the start passed the end. Despite all attempts to replicate I have not, so we just make sure to limit the bounds.
1. Closes #624

Bounds check stack trace line indexes

---

internal/internal_decision_state_machine.go
test/activity_test.go
test/integration_test.go
test/workflow_test.go

A state machine failure is occurring when anything is done in a workflow after the workflow was canceled which caused activity cancellation. This essentially reverts the activity part of #504 while keeping the timer part in place.
In cases where extra things happened after activity cancellation, a state machine bug occurred.
**While this is not believed to have any effect on history compatibility across versions, reviewers are requested to take a close look and give their own opinion.**
1. Closes #623

State machine issue after activity cancellation

---

internal/internal_workflow_client.go

Added request ID to cancel and signal calls.
They are on other calls, they need to be on these for easier debugging.
1. Closes #627

Add a request ID to cancel and signal calls

---

internal/internal_worker.go
test/activity_test.go
test/integration_test.go
test/workflow_test.go

Properly using the empty nil reflection value with the type instead of trying `reflect.ValueOf` for a nil value.
Workflows that were given too few args have zero values automatically created. However, the zero value automatically created for pointers was nil which couldn't be turned back to the proper value in Go reflection with
This was introduced in #610.
1. Closes #639

Fix issue for zero-values of pointer arguments in workflows.

---

internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
internal/workflow_testsuite.go

Added `TestWorkflowEnvironment.SetDetachedChildWait` that lets test environments not wait on detached (i.e. abandoned or request-cancel) children before finishing workflow.
In #470, we introduced a change that causes a parent `ExecuteWorkflow` to not return until all of its children are completely done. This caused issues for people testing interminable child workflows such as ones started on cron because they never finish.
Alternatively, we could have done something like expose child test workflow environments so people could cancel children themselves. This seems more straightforward however.
1. Closes #614

Add ability to not wait on child workflows in test suite.

---

internal/common/metrics/capturing_stats_reporter.go
internal/common/metrics/constants.go
internal/internal_worker_base.go
test/integration_test.go
test/workflow_test.go

Added worker metric called `temporal_worker_task_slots_available` that shows the remaining available slots for concurrent tasks. This is a "worker" metric as in the internal "worker" concept, not Temporal Workers. This is similar to two other "worker" metrics, `temporal_worker_start` and `temporal_poller_start` in that it has a `worker_type` tag that is either `WorkflowWorker`, `ActivityWorker`, or `LocalActivityWorker`. There are no other meaningful per-worker tags.
Requested by users wanting to see if they are using up their max concurrent tasks and waiting.
1. Closes #594

Add task pool slots remaining metric

---

internal/internal_decision_state_machine.go
test/integration_test.go
test/workflow_test.go

The same change for #382, but to apply to child workflow cancel that does not call the base.
An extra event for cancellation is not being accounted for in event counting when a cancel occurs during un-waited-on child workflow.
1. Closes #644

Fix invalid command ID expectation on child workflow cancel

---

internal/encode_args.go
internal/internal_coroutines_test.go

See #665. Basically calling `Receive` with the same pointer type as `Send` was used with did not work,
1. Closes #665

Support pointer-to-pointer in channel receive

---

internal/internal_workflow_testsuite.go
internal/workflow_testsuite_test.go

Set the workflow execution ID as the given ID if present in the given start workflow options
We do this with `TaskQueue` and other things, can do here too.
1. Closes #661

Set workflow ID from start options in testsuite if given

---

internal/internal_worker.go
internal/internal_workflow_testsuite.go

The debug mode now sets correctly the DeadlockDetectionTimeout after fixing coding error and it uses the same variable to detect the debug mode.
It's a bug and second the package private debugMode variable is set when the program is loaded while the other condition which reads after the new test environment can be inconsistent  if the test calls the `os.SetEnv` just before.
1. Closes 
N/A
Manually.
N/A

Debug mode does not set the DeadlockDetectionTimeout

---

internal/workflow_testsuite.go

Extra doc added for `TestWorkflowEnvironment.OnActivity`
Per #688 and #586, people are trying to use references on a struct instead of references on an instance of a struct.
1. Closes #688

Add note for OnActivity about method references

---

internal/internal_task_handlers.go
internal/internal_task_pollers.go
internal/internal_workflow_client.go
internal/internal_workflow_testsuite.go
test/activity_test.go
test/integration_test.go
test/workflow_test.go

Do not send `RespondActivityTaskCanceledRequest` on return cancel error unless the server initiated the cancel. Also added tests confirming behavior for activities and workflows when manually returning cancellation errors.
See #686. Basically the server has to be expecting the cancellation to handle it.
1. Closes #686

Only respond with activity cancellation when requested by server

---

internal/internal_task_handlers.go

Increase log level of heartbeat errors from debug to warn
Many loggers disable debug, but this is something that should be visible
1. Closes #692

Increase log level of heartbeat errors

---

internal/internal_task_handlers.go
internal/workflow.go
test/integration_test.go
test/workflow_test.go

Set the retry policy for continue-as-new based on the workflow's original value
Currently we set no value for retry policy on continue-as-new.
@yiminc, @mfateev, et al - Any backwards compatibility concerns for people that weren't expecting the retry policy to propagate?
1. Closes #695

Propagate retry policy for continue-as-new

---

internal/internal_worker.go
internal/internal_worker_test.go
internal/worker.go
test/integration_test.go
test/workflow_test.go

Added option to disable workflow worker.
For activity-only workers (such as those used by https://github.com/temporalio/samples-go/pull/166), we need to be able to disable unnecessary workflow worker polling and such.
1. Closes #636

Add ability to disable workflow worker

---

interceptor/tracing_interceptor.go

This PR enables the injection of tracing metadata in the activity logger. This builds on #713 and #655.
This allows tracing implementations to correlate logs for multiple activities and workflows serving a single request.
Tested e2e with our internal tracer implementation.

Support trace logger in workflows & activities

---

contrib/opentelemetry/tracing_interceptor.go
contrib/opentelemetry/tracing_interceptor_test.go
contrib/opentracing/interceptor.go
contrib/opentracing/interceptor_test.go
interceptor/tracing_interceptor.go
interceptor/tracing_interceptor_test.go
internal/interceptortest/tracing.go

* Added a `Time` field to `TracerStartSpanOptions`. This allows tracing implementations to set correct durations for spans that cross process boundaries.
* Added a `temporalActivityID` tag to `RunActivity` spans. This allows filtering for spans that are retries of the same activity within a workflow execution.
After https://github.com/temporalio/sdk-go/pull/714 these should be the last two changes needed for us to cut over our internal tracing implementation to sdk-go's `interceptor` package.
Tested end to end in our environment, but I'm also happy to write some unit tests for this functionality.

Add workflow/activity start time and activity ID to tracing interceptor spans

---

internal/context.go
internal/internal_coroutines_test.go

We lock context fields potentially used by multiple goroutines and we make sure context.cancel is only called once.
Before there were situations (run tests with `-race`) where context variables were accessed concurrently without mutexes which could cause context cancel to run twice unintentionally.
1. Closes #720

Fix context cancellation race condition

---

internal/internal_decision_state_machine.go
internal/version.go

We make sure we remove pending activity cancellations when we receive an activity completion from the server, taking care not to incorrectly alter the event sequence identifier incorrectly.
This has some history I'll try to explain here in a quick set of bullets.
* The existing implementation in Go SDK collects commands for cancellation before it processes events that may make the cancellation moot
* Therefore, in a racy situation, you can get an activity completion after you've queued up an activity cancellation and if you sent that cancellation, the server fails
* This was mostly fixed in #504 but the special code that handled fixing the event counter when removing the no-longer-needed pending cancel had an issue for activities that were sent after it (e.g. cleanup activities)
* This …

Remove pending activity cancellations when activity completion occurs

---

converter/encoding_data_converter.go
converter/encoding_data_converter_test.go

The Remote Encoding protocol is adjusted to take Payloads protobuf, not Payload.
This makes for more efficient HTTP traffic.

Adjust HTTP protocol to take Payloads not Payload.

---

internal/internal_worker.go
internal/internal_worker_test.go
internal/worker.go

Disallow MaxConcurrentWorkflowTaskPollers to be set to 1
Because worker polling is built to require at least 2 due to how stickiness preference is implemented.
1. Closes #719

Disallow MaxConcurrentWorkflowTaskPollers to be set to 1

---

internal/internal_decision_state_machine.go
test/activity_test.go
test/integration_test.go
test/workflow_test.go

Only decrement the in-process cancelled counter during workflow cancel.
In order to keep the event ID expectations correct, we keep a cancellation counter for things cancelled during workflow execution. This cancellation counter, which has been there for timers and reinstated in #726 for activities, is incremented upon cancel and decremented upon removal of the command. But while the increment was done only during workflow cancellation, the decrement was being done always. This makes sure that decrement is only done during workflow cancellation, when the increment occurs.
Whether we should be limiting the increment to only during workflow cancel done way back in #382, I am unsure.
The reason we saw this issue is during session cancellation which is _not_ workflow cancellation was …

Fix activity cancellation race when not cancelling workflow

---

converter/codec.go

Add a ModifyRequest option to remote codec dataconverter.
This allow use cases such as oauth/JWT.

Allow remote codec dataconverter to modify request.

---

.github/workflows/ci.yml
test/bindings_test.go
test/integration_test.go
test/test_utils_test.go

Allow integration tests to use env-var-based cert/namespace and add cloud test to CI for GH action
We need to ensure at least the most basic workflows work on cloud always
Note: Secrets that are needed by this test cannot be accessed by forks. So this test only runs on branches from this repo. Not only do we run it on master push, but we will also amend the release process to ensure the PR updating the version is done from a branch _on the repo_ to ensure this test failing will hold up a release.

Add cloud test to GH action CI

---

contrib/tally/handler.go
contrib/tally/prometheus.go
contrib/tally/prometheus_test.go

Made the suggested sanitize options a var and added a Prometheus scope wrapper to put proper suffixes on names
See #750. We want to match Java SDK naming. Tally unfortunately only lets you sanitize characters with the options so we have to wrap the scope.
Since Prometheus support is an opt-in convention, we changed the documentation on how to do it and will be changing the sample when this is released.
1. Closes #750

Support OpenMetric-style naming

---

internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
internal/workflow_testsuite.go

Added `SetOnActivityHeartbeatListener` on `TestActivityEnvironment` same as `TestWorkflowEnvironment`
Need to be able to mock heartbeat calls to server
1. Closes #768

SetOnActivityHeartbeatListener on TestActivityEnvironment

---

converter/data_converter.go
internal/internal_workflow.go
internal/workflow.go
internal/workflow_deadlock.go
internal/workflow_deadlock_test.go
workflow/workflow.go

Added `workflow.DataConverterWithoutDeadlockDetection` to create data converters without deadlock detection. Also reworked deadlock detection internally so it can be paused and resumed.
Some data converters need to do advanced things
1. Closes #769

Allow data converters to be created without deadlock detection

---

contrib/tools/workflowcheck/determinism/reason.go
contrib/tools/workflowcheck/workflow/checker.go
contrib/tools/workflowcheck/workflow/testdata/src/a/workflow.go

Prevent recursion on outputted lines in `workflowcheck`
While Go does not usually allow cross-package recursion, a special case is being triggered by the `text/template` package
1. Closes #767

Fix template recursion in workflowcheck

---

client/client.go
workflow/workflow.go

* Made clear on `workflow.GetLastError` and `workflow.GetLastCompletionResult` that the former doesn't carry over and the latter does
* Updated `client.Client.ListWorkflow` to say that some queries do not require ElasticSearch (while _intentionally_ not documenting all the details of which ones do/don't at the moment).
1. Closes #786
2. Closes #742

Minor doc fixes

---

contrib/opentelemetry/go.sum
contrib/opentracing/go.sum
contrib/tally/go.sum
converter/grpc_interceptor.go
go.mod
go.sum
internal/internal_workflow_testsuite.go
test/go.mod
test/go.sum

Remove `namespace` field from `ScheduleActivityTaskCommandAttributes` message.
See https://github.com/temporalio/api/pull/174.
**TODO**
`go.temporal.io/api` in `go.mod` needs to be updated as soon as above PR is merged.

Remove namespace field from ScheduleActivityTaskCommandAttributes message

---

contrib/tools/workflowcheck/determinism/determinism_test.go
internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go

* Fix issue where child workflow execution info was not propagated into activity info in test suite
* Fix issue where activity heartbeats were not handling cancellation in test suite
* Fix issue where activity was executing even if `ExecuteActivity` was called with cancelled context in test suite
* Suppress large output on `workflowcheck` test (unrelated to rest of issue)
Multiple issues with how activities interact with cancellation and child workflows. The first of which was discovered as part of #778.
While our unit tests pass, this technically changes (fixes) some things about activity info and heartbeats that could break existing tests that rely on the broken behavior. Also, this relies on our tests having decent coverage of our own test suite.

Fixes for activities in test suite

---

internal/internal_task_handlers.go
test/integration_test.go
test/workflow_test.go

Made sure that the workflow execution context state was cleared on non-cached workflows
Workflows can start many coroutines which may hang waiting for server interaction. Currently we only clear that up on workflow completion or in the worker finalizer on cache eviction. But query-only poll responses (i.e. where the legacy `PollWorkflowTaskQueueResponse.query` is non-nil) do not cache. So they were not exiting the context which didn't clean up goroutines and other items.
Before this fix, you could query a started-but-not-finished workflow over and over and the memory would continually grow.
1. Relates to #774

Fix goroutine/memory leak on query-only poll responses

---

client/client.go
contrib/opentelemetry/go.sum
contrib/opentracing/go.sum
contrib/tally/go.sum
go.mod
go.sum
internal/client.go
internal/internal_task_handlers.go
internal/internal_worker_base.go
internal/internal_worker_test.go
internal/internal_workflow_client.go
test/bindings_test.go
test/go.mod
test/go.sum
test/integration_test.go

`NamespaceNotFound` is used instead of general `NotFound` in case of missing namespace.
See https://github.com/temporalio/temporal/pull/2785 and https://github.com/temporalio/api/pull/179 for details.
To react on `NamespaceNotFound` differently.

Use NamespaceNotFound error

---

client/service_proxy.go
contrib/opentelemetry/go.sum
contrib/opentracing/go.sum
contrib/tally/go.sum
converter/grpc_interceptor.go
go.mod
go.sum
internal/cmd/generateinterceptor/main.go
test/go.mod
test/go.sum

Update api to get new schedule-related RPCs and messages.
This isn't used directly yet but I need to update this first to make the corresponding update in the temporal repo.
make check

Update go.temporal.io/api dependency

---

Makefile

Add `make update-go-sum` to propagate go.sum changes into other modules. It just does `go get ./...` in each module.
Also have the for-each-module loops in the Makefile echo the directory they're running in, which would have saved me a few minutes of confusion.
developer experience
1. Closes 
manually

Add update-go-sum target

---

internal/internal_event_handlers.go

Added ignore for event type `EVENT_TYPE_WORKFLOW_EXECUTION_TERMINATED`
Replay was logging an error when this event was received (but it was not stopping/erroring replay)
1. Closes #815
2. How was this tested: This was not tested. Today this only emits a log when this event is received (it doesn't harm running programs), and even then it's only on non-replay which I have struggled to simulate this event type during non-replay.

Ignore termination event

---

client/client.go
internal/internal_worker.go
internal/internal_worker_test.go
worker/worker.go

Added `client.HistoryFromJSON` helper to load history
Other forms of obtaining history JSON need to be supported beyond what's in the replayer
1. Closes #808

Helper for loading history from JSON

---

internal/internal_worker.go
test/integration_test.go

Add interceptors to replayer options
Interceptors may do things that affect commands so they need to run during replay too
1. Closes #828

Add interceptors to replayer options

---

internal/internal_workflow_testsuite_test.go
internal/workflow_testsuite.go

Changed param from `map[string]interface{}` to `interface{} on `OnUpsertSearchAttribute` to support `mock.Anything` or other mock matchers.
Current version only supports matching a specific map.
1. Closes #810

Allow any value in the OnUpsertSearchAttribute mock

---

activity/activity.go
converter/data_converter.go
converter/value.go
internal/activity.go
internal/internal_workflow_client.go
internal/workflow.go
internal/workflow_testsuite.go
workflow/workflow.go

* Added note that unmarshalling on top of existing object can have unexpected behavior
* Added note that some mock callbacks are not thread-safe
1. Closes #843
2. Closes #844

Concurrency and serialization documentation notes

---

internal/internal_event_handlers.go
internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
internal/workflow.go
internal/workflow_testsuite.go
test/integration_test.go
test/workflow_test.go

Added `workflow.GetInfo(ctx).GetCurrentHistoryLength()` and a helper to set during unit tests
So people can use it to make continue-as-new determinations
1. Part of #628

Add workflow.GetInfo(ctx).GetCurrentHistoryLength()

---

README.md

The "git clone ..." command was returning a permission-denied error
The "go get ..." command was deprecated
Updated links for cloning the repository
Provided commands weren't working
1. Closes 

Links updated

---

internal/internal_eager_activity.go
internal/internal_eager_activity_test.go

Work with nil response
Sometimes `RespondWorkflowTaskCompleted` errors and we didn't properly account for that when unreserving reserved slots
1. Closes #860

Properly handle absent WFT response for eager activities

---

internal/internal_task_handlers.go
internal/worker.go
test/activity_test.go
test/integration_test.go
test/workflow_test.go

Stop timing out the RPC context for recording heartbeat before it can even record
Really short timeouts were preventing calls from being made properly
1. Closes #859

Support really short heartbeat throttling interval

---

internal/internal_workflow_testsuite_test.go

Updated a unit test to compile with Go 1.19
Go 1.19 (correctly) notices that the following is basically useless as
it tests that an error can be converted to the error interface (which is
always the case).
```
err := NewWorkflowError(...)
target := errors.New("...")
errors.As(err, &tarter)
```
The broken test further broken in that it expected the base Go error to
make it through the failure conversion machinery intact when in truth
the expectation is that it gets converted to an instance of
ApplicationError.
1. Closes 
n/a
n/a
No

Unit test fix for Go 1.19

---

client/client.go
internal/client.go
internal/common/metrics/grpc.go
test/integration_test.go

* Added `NewClientFromExisting` function to create a new client with the same connection but different client options
* Made sure to support the different namespaces in the gRPC interceptor metrics
Users want to use the same connection for multiple namespaces
1. Closes #861

Share connection across different clients

---

internal/internal_workflow.go
internal/internal_workflow_test.go

Spawn update coro directly through dispatcher
Calling Go/GoNamed with a context from outside the workflow will fail
because the context doesn't have a handle to dispatcher state.
1. Closes 
n/a
Defect found via sdk-features test for update which will land soon
No

Spawn update coro directly through dispatcher

---

internal/workflow.go
workflow/workflow.go

I don't imagine this `otherwise...` code block was intentional:

Fix doc formatting

---

workflow/workflow.go

The code samples in the docs for `workflow.SideEffect` where missing `ctx` as the first argument. This PR fixes that.
To help developers use the code correctly

Fix code samples for workflow.SideEffect

---

internal/internal_worker_base.go

Remove poll failures on when worker is stopped
1. Closes #882

Stop logging poller errors after stop

---

client/service_proxy.go
contrib/opentelemetry/go.sum
contrib/opentracing/go.sum
contrib/tally/go.sum
converter/grpc_interceptor.go
go.mod
go.sum
internal/cmd/generateinterceptor/main.go
test/go.mod
test/go.sum

Batch operations were added in API in https://github.com/temporalio/api/pull/197.
This PR syncs generated files affected by API changes.
Unblock other changes that depends on recent API changes.
`make`

Sync batch operations api

---

client/client.go
internal/client.go
internal/internal_workflow_client.go
internal/internal_workflow_client_test.go
test/integration_test.go

Use a counter to make sure only the last `Close()` of a shared-connection set of clients applies.
1. Closes #886

Handle Client.Close on cloned clients

---

client/client.go
internal/client.go
internal/internal_workflow_client.go
mocks/Client.go

Added `Client.OperatorService` that returns an operator service client on the same gRPC connection
1. Closes #896

Expose OperatorService client

---

internal/internal_worker.go
internal/internal_workers_test.go

Need to make worker `Stop()` safe for a second call
We call stop internally on fatal error, so a user's stop call should do nothing
1. Closes #903

Make Worker.Stop reentrant

---

.github/CODEOWNERS

Update `CODEOWNERS` to `temporalio/sdk` team.
Not to depend on specific persons and remove myself from SDK owners.

Update CODEOWNERS to temporalio/sdk team

---

client/service_proxy.go
contrib/opentelemetry/go.sum
contrib/opentracing/go.sum
contrib/tally/go.sum
converter/grpc_interceptor.go
go.mod
go.sum
internal/interceptor.go
internal/interceptor_base.go
internal/interceptortest/proxy.go
internal/internal_command_state_machine.go
internal/internal_command_state_machine_test.go
internal/internal_event_handlers.go
internal/internal_event_handlers_test.go
internal/internal_task_handlers.go
internal/internal_task_handlers_test.go
internal/internal_worker_base.go
internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
internal/workflow.go
internal/workflow_testsuite.go
test/go.mod
test/go.sum
test/integration_test.go
test/workflow_test.go
workflow/workflow.go

Adding an API for `UpsertMemo`. It merges with current memo and creates a command `ModifyWorkflowProperties` with the updated memo.
This change depends on https://github.com/temporalio/api/pull/218.
Feature request: https://github.com/temporalio/sdk-features/issues/119
- Created new tests.

Add UpsertMemo API

---

test/integration_test.go

Skip upsert memo integration tests because of a bug in temporal server 1.18.0.
N/A

Skip upsert memo integration tests

---

interceptor/tracing_interceptor.go
interceptor/tracing_interceptor_internal_test.go

This PR adds a new `IdempotencyKey` field to `TracerStartSpanOptions` and sets this field on spans created from the `WorkflowInboundInterceptor` tracing implementation.
This option can be used to compute a deterministic span ID automatically for tracing implementations which support specifying an explicit span ID. This is being proposed as an alternative to the way we're computing the `RunWorkflow` span ID in #921.
This approach might also be used to provide a safe interface for handling custom spans created by end users in workflow code.
1. Closes
N/A
3. How was this tested:
See new unit test for creating idempotency keys. There are no existing tracing implementations in tree which support explicit spans, but we may be able to add additional tests in #921 if this is merged.
4. Any docs …

Add IdempotencyKey start span option

---

interceptor/tracing_interceptor.go

This PR skips setting `IdempotencyKey` for query spans. Followup to #931.
Queries aren’t included in workflow history, so the counter can be reset in between workflow replays and we can end up with an idempotency key collision with another query or signal.
1. Closes 

Do not set idempotency key for HandleQuery

---

internal/common/metrics/constants.go
internal/common/metrics/grpc.go
internal/grpc_dialer_test.go

Added `temporal_request_resource_exhausted` and `temporal_long_request_resource_exhausted` counter metrics w/ `cause` tag in addition to tags already on `X_request_failure` metrics.
By request at https://github.com/temporalio/sdk-features/issues/144

Add resource exhausted metric with cause

---

internal/internal_workflow_client.go
internal/internal_workflow_client_test.go

Don't use data converter if search attribute value is of `Payload` type.
`WorkflowInfo` contains search attributes with values encoded in `Payload`. To start child workflow with same search attributes, workflow code needs to decode them and then set it back. To do this, it must know all name and types which is not always possible. This is small workaround which allows to copy search attributes from current workflow to child.

Don't use data converter if search attribute value is of Payload type

---

README.md

Updated the README with a more helpful logging example.
The current example did not make it clear how to "feed the logger" into Temporal.  Grabbed the better example from https://docs.temporal.io/go/how-to-set-clientoptions-in-go/#logger.
1. Closes 
n/a
n/a
Done

Provide better custom logger example in README

---

.github/workflows/docker/dynamic-config-custom.yaml
internal/internal_eager_activity.go
internal/internal_eager_activity_test.go
internal/internal_worker.go
internal/worker.go

* Removed default limit on `MaxConcurrentEagerActivityExecutionSize`
* Added default limit of 3 eager activities per workflow task
My original concern was overloading the worker with lots of eager activities. Others' concerns are only overloading a worker in the rare case of more than 3 activities per task. I think my concern is limits eager activity scope better, but I'm doing what others want here.
1. Closes #950

Max eager activities per task

---

internal/internal_schedule_client.go
internal/internal_schedule_client_test.go
internal/schedule_client.go
test/integration_test.go

Fix a few issues @cretz found in the schedules API:
- clean up documentation on schedule ID and workflow ID
- standardize on taking a pointer type for `ScheduleWorkflowAction`
closes:
* https://github.com/temporalio/sdk-go/issues/958
* https://github.com/temporalio/sdk-go/issues/957
Note: This is a breaking change since users can no longer pass a struct for `ScheduleWorkflowAction` to avoid this we could  allow users to pass a pointer or a struct.

Schedule fixes

---

.github/workflows/ci.yml

Draft until https://github.com/temporalio/sdk-features/pull/162 is merged

Add ci trigger for sdk-features

---

internal/common/metrics/constants.go
internal/common/metrics/tags.go
internal/internal_task_pollers.go
test/integration_test.go

Closes https://github.com/temporalio/sdk-go/issues/854
Implements the `num_pollers` metric for Go
NOTE:
Once released we need to update the docs to include Go here
https://docs.temporal.io/references/sdk-metrics#num_pollers

Add num_pollers metric

---

internal/common/metrics/constants.go
internal/internal_task_pollers.go

add local_activity_execution_failed to align with java
for https://github.com/temporalio/sdk-features/issues/167

Add local_activity_execution_failed metric

---

internal/internal_task_handlers.go
test/integration_test.go
test/workflow_test.go

Certain, previously constant now mutable fields, in the workflow info are not reset when a stale context is reset leading to them leaking into replays and causing non deterministic behaviour if those fields were used to make decision in the workflow that effected history.
closes https://github.com/temporalio/sdk-go/issues/970

Reset SA and memos if execution context is stale

---

internal/version.go

1.19.0 Release
sdk-feature and go-canary tested locally

Version v1.19.0

---

internal/internal_event_handlers.go
internal/internal_task_handlers.go
internal/internal_task_handlers_test.go
internal/internal_worker.go
internal/internal_worker_test.go
test/fixtures/activity.cancel.sm.repro.json
test/integration_test.go
test/replaytests/bad-continue-as-new-2.json
test/replaytests/bad-continue-as-new.json
test/replaytests/bad-empty-workflow.json
test/replaytests/bad-history-2.json
test/replaytests/bad-local-activity-2.json
test/replaytests/bad-local-activity.json
test/replaytests/bad-search-attribute-2.json
test/replaytests/bad-search-attribute.json
test/replaytests/bad-upsert-memo-workflow-2.json
test/replaytests/bad-upsert-memo-workflow.json
test/replaytests/continue-as-new.json
test/replaytests/local-activity.json
test/replaytests/replay_test.go
test/replaytests/search-attribute.json
test/replaytests/side-effect.json
test/replaytests/test-workflow.json
test/replaytests/upsert-memo-workflow.json
test/replaytests/workflows.go

Fix a few bugs causing false positives and false negatives when replay histories
* Remove protobuf json binary comparisons because they are not deterministic
* Check history during a replay even if the workflow is complete
* Remove dead code around strictMode
Note on backwards compatibility: This PR will cause some histories to fail the replayer that didn't use to, but they always should have so I don't consider this a breaking change, just a bug. It could also cause some histories to pass that used to fail if the non determinism was from the workflow execution complete payload. I tried hard to preserve the error message of any workflow that would have failed before
resolves: https://github.com/temporalio/sdk-go/issues/983, https://github.com/temporalio/sdk-go/issues/876 and …

Fix history replayer

---

internal/internal_worker.go
internal/internal_worker_test.go
worker/worker.go

Add an option to the replayer to set workflow ID and run ID
* closes https://github.com/temporalio/sdk-go/issues/994
* closes https://github.com/temporalio/sdk-go/issues/865

Add option to override replayer execution info

---

contrib/tally/handler.go

Add doc links in package `contrib/tally` following godoc improvements in Go 1.19. See https://go.dev/doc/comment
Improve godoc for package contrib/tally by adding doc links.
See https://go.dev/doc/comment.
Link to upstream tally package from this package documentation.

contrib/tally: improve godoc with links

---

internal/internal_worker.go
internal/schedule_client.go
internal/worker.go

Fix the count in `ScheduleListEntry`
Disallow setting `MaxConcurrentWorkflowTaskExecutionSize` to one because it doesn't work
>Looks like we limit the number of pollers to `MaxConcurrentWorkflowTaskExecutionSize ` so the worker will only be polling on the sticky queue, so it will never pick up work. So the root cause is the same reason we need 2 workflow task pollers
Note: Technically we do create `maxConcurrentWorkflowTaskPollers ` number of pollers , but only really start `MaxConcurrentWorkflowTaskExecutionSize `
`MaxConcurrentWorkflowTaskExecutionSize` should never be less than `MaxConcurrentWorkflowTaskPollers `
We call this out here https://docs.temporal.io/application-development/worker-performance#invariants but say it only applies to java which is not true it also applies to the …

Some documentation fixes

---

internal/internal_task_handlers.go

In some server tests the race detector noticed that SetPreviousStartedEventID can race with cache removal which happens on the cache eviction thread.
Data races bad
1. Closes 

Prevent cache eviction race

---

internal/internal_message.go
internal/internal_message_test.go
internal/internal_task_handlers.go
internal/internal_task_handlers_test.go

Here we switch to delivering all messages dependent on events IDs less than or equal to the current event ID.
We don't run WFTScheduledEvent instances through standard event handling so we were missing messages dependent on events of that type
1. Closes 
Unit & features

Deliver messages even when events are skipped

---

internal/internal_workflow_client.go
internal/internal_workflow_client_test.go

Match the behavior of Future, which is to return the error value (which
is likely nil) in such cases and not to try to assign to nil.
Consistent with Future and allows for updates that do not return a value. 
1. Closes 
Unit test and features test
No

Correct updateHandle.Get when passed nil pointer

---

internal/internal_worker.go

This PR enables setting `ContextPropagators` on workflow replay options, which can currently only be set on `client.Options` passed to a worker.
Context propagators can extract information from workflow headers and modify workflow contexts. This is important for workflow replay in some cases, because information in a `workflow.Context` may be used to modify workflow behavior, eg. workflow code that performs role based access control based on claims in workflow headers.
How was this tested:
This was tested in our internal environment where workflow replay was previously failing due to missing context propagators.

Add ContextPropagators option for replay tests

---

activity/doc.go

Resolves https://github.com/temporalio/sdk-go/issues/1010

Fix headings on activity docs

---

internal/internal_worker.go

Use the task queue if it is available in the history rather than "ReplayTaskQueue" so replay is closer to real execution.
See also: https://github.com/temporalio/features/issues/114

On replayer use task queue from history

---

internal/internal_workflow_client.go

Use the getter that protects against that situation.
If there is an error returned, the response here will be nil and we'll panic unless we protect against dereferencing.
1. Closes 
Found by features test.
No

Protect against nil defref in update resp handling

---

internal/internal_update.go
internal/internal_update_test.go
internal/internal_workflow.go

Adds a conditional yield point during update processing to allow the scheduler to do other things like registering update handlers.
If the first WFT includes an update we can have a problem because the workflow function itself hasn't run yet to register update handlers and the update will be rejected. Adding this yield allows the scheduler to execute the workflow function up to the first blocking point, at which point the handler(s) will be registered by user code.
1. Closes 
Unit test here and I was able to remove all the time.Sleep(1*time.Second) from the features tests.
No

Workaround for updates delivered in first WFT

---

internal/session.go
internal/session_test.go
internal/workflow.go
test/integration_test.go
test/workflow_test.go
workflow/session.go

Expose session state to users so they can understand if their activity failed because the session worker failed.
resolves:https://github.com/temporalio/sdk-go/issues/1021

Expose session state

---

internal/internal_command_state_machine.go
internal/internal_worker_test.go
test/integration_test.go
test/workflow_test.go

User reported this issue where I believe they tried to cancel a workflow that had a child workflow and it resulted in the parent workflow getting stuck panicing on invalid state transition on the `ChildWorkflowExecutionCanceled` because it didn't expect it to be in `CanceledAfterStarted`. I don't see why we would treat `CanceledAfterInitiated` differently than `CanceledAfterStarted` so I allowed the state transition.
Previously the SDK would consider this an invalid state transition and panic, now the SDK handles it as a canceled child workflow.

Handle CanceledAfterStarted in CanceledEvent

---

Makefile

Pin staticcheck to v0.3.3
The latest version of staticcheck (0.4.0 as of 3 Feb 2023) scans dependencies (?) and incorrectly detects that the
proxy.WorkflowServiceProxyOptions.Client field is unused in api-go. We will pin to the previous version for now but be advised this version is known not to work with go1.20.
1. Closes 

Pin staticcheck to v0.3.3

---

internal/common/backoff/retry.go
internal/common/backoff/retrypolicy.go
internal/internal_worker_base.go
internal/internal_workers_test.go
test/integration_test.go

Retry "non retryable" errors for a period of time like core. This helps handle some know edge cases where proxies may way rewrite grpc timeouts when a server fails over and cause an error from the server. This aligns the go sdk with core. The retry period was picked at 2 minutes because it is greater than the long poll interval so in the proxy failure mode we still retry at least once.
See also:
https://github.com/temporalio/features/issues/218

Retry "non retryable" error on worker long poll

---

contrib/tools/workflowcheck/determinism/ident_refs.go
contrib/tools/workflowcheck/determinism/testdata/src/a/calls.go

resolves: https://github.com/temporalio/sdk-go/issues/980

workflowcheck: mark some fmt functions as deterministic

---

.github/workflows/ci.yml
Makefile
internal/common/backoff/retry.go

Currently CI tests 1.17 that has been EOL for 6 months.  I would also be OK with adding a test for 1.19 as well, but seems slightly unnecessary.

Update CI to test golang 1.20

---

internal/internal_schedule_client.go
internal/schedule_client.go
test/integration_test.go

Align with python and typescript SDKs and use sensible defaults for ScheduleCalendarSpec to help users.
Defaults are taken from the python SDK.
Note: This is a breaking change because we are changing defaults, but schedules is marked as experimental and users have been asking for this

Use sensible defaults for ScheduleCalendarSpec

---

internal/internal_command_state_machine.go
internal/internal_event_handlers.go
internal/internal_worker.go
test/replaytests/mutable-side-effect-legacy.json
test/replaytests/mutable-side-effect.json
test/replaytests/replay_test.go
test/replaytests/workflows.go
test/workflow_test.go
worker/worker.go

Track how many times a mutable side effect is called to distinguish multiple `MutableSIdeEffect` calls in the same WFT.
I'll note this PR wont help existing histories that executed multiple `MutableSIdeEffect` in the same WFT. If we also use the `CommandID` to help distinguish multiple calls. The could help certain histories replay correctly. The trade off is an even more complex implementation. There will always be some histories that we cannot save because the SDK did not write enough information to history
Resolves: https://github.com/temporalio/sdk-go/issues/1014

Track mutable side effect calls

---

internal/internal_task_handlers.go
internal/internal_task_handlers_test.go

Include lookahead message inference on this path to workflow state rebuilding
Without inference, updates are not replayed
1. Closes 
#1044 
New unit test here.
No

Lookahead to infer messages on all replay paths

---

internal/internal_command_state_machine.go
internal/internal_event_handlers.go
internal/internal_flags.go
internal/internal_task_handlers.go
internal/internal_task_handlers_interfaces_test.go
internal/internal_worker.go
test/integration_test.go
test/replaytests/replay_test.go
test/replaytests/version-loop-workflow-10.json
test/replaytests/version-loop-workflow-256.json
test/replaytests/version-loop-workflow-legacy-10.json
test/replaytests/version-loop-workflow-unkown-version-flag.json
test/replaytests/workflows.go
test/workflow_test.go

Reduce SA bloat on GetVersion. This PR implements 3 new features to the Go SDK.
1. Adds capability visibility to workflow and activity task execution.
2. Adds sdk flags based off the core API to allow internal SDK versioning
3. Uses sdk flags to no longer upsert search attributes on `GetVersion` if that search attribute would exceed the default size limit

Reduce SA bloat on GetVersion

---

internal/internal_event_handlers.go
internal/internal_flags.go
test/integration_test.go
test/replaytests/duplicate-child-workflow.json
test/replaytests/replay_test.go
test/replaytests/workflows.go
test/workflow_test.go

Pass errors to the child workflow execution future. I had to version this because the change is technically non deterministic, I don't know if anyone would hit is, but I also don't understand why people launch duplicate child workflows so I am playing it safe.
resolves: https://github.com/temporalio/sdk-go/issues/1041

Pass errors to the child workflow execution future

---

Makefile
testsuite/devserver_test.go

- Included testsuite/*_test.go in UT_DIRS (`make unit-test`), and
- Ignored error returned by Stop() until https://github.com/temporalio/cli/issues/175 is addressed.

Fix DevServer tests

---

testsuite/devserver.go
testsuite/devserver_test.go

Added a new `FrontendHostPort` method to `testsuite.DevServer` that returns the `host:port` to the dev server, similar to Temporalite ([here](https://github.com/temporalio/temporalite/blob/2df426ad3426fb6ecc91d3b2e03274018bf14721/server.go#L158-L164)).
This would be useful when the client.Client can't be shared with the unit being tested, e.g. a Command struct that only accepts os.Args, environment strings or other form of configuration.

Add FrontendHostPort method to DevServer

---

internal/internal_task_handlers.go
internal/internal_task_handlers_test.go

Infer messages on an additional workflow context rebuild path - namely, a cache miss on the worker side.
Need to replay messages on all rebuild paths for correctness
1. Closes 
Unit test

Message inference for more WF ctx reset paths

---

internal/internal_worker.go
test/replaytests/replay_test.go
test/replaytests/update.json
test/replaytests/workflows.go

Remove a place where we infer messages from an event set.
With the recent fixes to infer messages on all context reset/reload paths, this call to inferMessages has become superfluous. In fact, this call is causing us to add messages to the phony WFT twice, resulting in replay failures.
Tests in the features repo confirm the brokenness and the fix. The reason this wasn't caught as part of the PR feature tests is that update is disabled by default so update tests skip themselves.
1. Closes 
All update tests in the features repo

Prevent inferring messages twice

---

internal/version.go

Doing a point release to fix https://github.com/temporalio/sdk-go/pull/1083

Update SDK Version to 1.22.1

---

internal/worker_version_sets.go
internal/worker_version_sets_test.go

https://github.com/temporalio/api/pull/272

Remove version_set_id from CompatibleVersionSet

---

internal/internal_worker.go
test/replaytests/local-activity.json

resolve: https://github.com/temporalio/sdk-go/issues/1091

Allow unknown fields while parsing json history

---

client/client.go
converter/codec.go
internal/client.go
internal/interceptor.go
internal/interceptor_base.go
internal/internal_workflow_client.go
internal/internal_workflow_client_test.go
mocks/Client.go

Adds support for async updates
- A WorkflowUpdateHandle implementation that runs a poll RPC as part of the call to Get
- Add PollWorkflowUpdate to the client and the interceptor layers
- The ability to "rehydrate" an update reference into a handle 
Planned feature
1. Closes 
Unit tests here and a succeeding feature test that is waiting on this PR and an server PR

Async Update Polling

---

internal/context.go
workflow/context.go

Minor capitalization change so that the example code actually correctly executes.
The example code causes a compile error otherwise.
YES. but only the SDK docs: https://pkg.go.dev/go.temporal.io/sdk/workflow#NewDisconnectedContext 
Nothing on docs.temporal.io

Fix typo in NewDisconnectedContext docs.

---

internal/internal_task_handlers.go
internal/workflow.go

This pull requests address issue #1087 to expose additional fields from the WorkflowExecutionStartedEvent into the SDK
It was a missing feature that the Java SDK already implemented, and that is implemented in Cadence.
- [] Add unit tests
1. Closes #1087 
Not tested
Comments describing the fields should be good

Exposing WorkflowExecution Started Event attributes on the Workflow Info

---

internal/internal_worker.go
internal/internal_worker_test.go

Check for workflow context usage within activity arguments as this is usually developer error (accidental and misunderstanding). Note that this would likely fail later on anyways when executing the function.
Prevent accidental errors.
1. Closes #1061 
2. How was this tested: Added unit tests for new behavior, existing tests should verify current behavior. 
3. Any docs updates needed? No as this is not stated as an allowed behavior (nor will it even work).

Error on Registering Activity with Workflow Context

---

log/with_logger.go

I found the previous wording confusing, as the use of "prepend" suggests a position of the key-value pairs that was different than what I observed in the output.
I reworded a comment that appears in the generated documentation. 
The comment previously said, "With returns Logger instance that prepend every log entry with keyvals. If logger implements WithLogger it is used, otherwise every log call will be intercepted."
I interpret the use of "prepend" to mean that the key-value pairs I supply will appear first in the output. However, I found that they are the last things to appear. After further experimentation, I found that the KV pairs supplied to `With` appear after both the KV pairs in the parent logger and the string that I provided in the log statement, although they do appear before …

Clarify description of With function

---

internal/error_test.go
internal/failure_converter.go

Fix a discrepancy between failure encoded and decoded. On decode the `failureHolder` stored the decoded failure, on encoded it assumed the `failureHolder` had an encoded failure.

Properly store the original failurepb on decode

---

converter/payload_converter_test.go
converter/proto_json_payload_converter.go

We would like to use the temporal data converters for encoding/decoding payloads, but the proto JSON converter doesn't expose the unmarshalling option to ignore unknown fields. This adds that option, but maintains the current behaviour for anyone wanting it that way
We don't want unknown fields in proto JSON to cause decode errors
1. Closes 

Add option to ignore unknown fields when protojson unmarshalling

---

internal/internal_update.go
internal/internal_update_test.go

Remove panic recovery guards around invoking user update code. These panics will now escape the handler and bubble up, eventually being processed by the workflow's panic handling policy. 
This makes update execution consistent with other workflow code.
1. Closes 
Features tests to be landed after this PR
No

Allow update panics to bubble up

---

internal/internal_task_handlers.go
internal/internal_task_handlers_interfaces_test.go
test/replaytests/replay_test.go
test/replaytests/workflow_loop_task.json
test/replaytests/workflows.go

@mmcshane Said SDK flags were not working in the Go SDK. On investigation I found `NextCommandEvents` was returning the flags from a `WorkflowTaskCompletedEvent` one workflow task ahead.
This is a backwards compatible change because the bug was on replay not on writing the flags.

Make sure SDK flags are applied to the correct WFT

---

internal/internal_flags.go
internal/internal_flags_test.go
internal/internal_task_handlers.go

Write sdk flags directly during replay
If flags are found for a task via lookahead we want those flags to be written directly into the current flagset and not the new/pending flagset as residence in the latter is not visible to subsequent callers of sdkFlags.tryUse.
1. Closes 
This is needed for a subsequent PR that enables CommandProtocolMessages for Update and uses SDKFlags to check for whether or not the command should be sent.

Write sdk flags directly during replay

---

.github/workflows/ci.yml
Makefile

Switch to the official coveralls uploader. Also took the opportunity to update some dependencies.
If it breaks at least were on a supported action rather than some random executable. Also took the opportunity to update some dependencies.
1. Closes 

Switch to the official coveralls uploader

---

internal/internal_update.go
internal/internal_update_test.go

Recover panics from update validation by converting to PanicError - this will fail the update but not the WFT and will not trigger the WorkflowPanicPolicy. Panics from update execution still propagate out and will be handled by the task processing loop in accordance with the WorkflowPanicPolicy.
Consistent with query error behavior. Doesn't run afoul of pending updates when PanicPolicy is FailWorkflow. Consistent with java sdk
1. Closes 
unit test here & pending changes to task_failure features tests 

Update panic handling

---

README.md

Last update was 2020. 
https://coveralls.io/github/temporalio/temporal-go-sdk?branch=master
Alternatively, we could keep it if we can get it updated, and preferably if it shows 80+% (yellow) or 90+% (green).

Remove coveralls link

---

contrib/tools/workflowcheck/determinism/checker.go
contrib/tools/workflowcheck/workflow/checker.go
contrib/tools/workflowcheck/workflow/testdata/src/a/workflow.go

Allows `//workflowcheck:ignore` to work on workflow function registration sites

Allow ignoring function ref issues

---

testsuite/devserver.go
testsuite/interrupt_nonwindows.go
testsuite/interrupt_windows.go

Starting killing the dev server process on Windows since sending signals (and SIGTERM or os.Interrupt) is not supported 
Ensuring the dev server is stopped and doesn't leave hanging
1. Closes 
Added test

Fix stopping dev server on Windows 

---

internal/internal_task_handlers.go
internal/internal_task_handlers_interfaces_test.go
internal/internal_task_handlers_test.go
internal/internal_worker.go
internal/internal_worker_interfaces_test.go

Draft solution to fix the issue seen during load testing update.
```
process event for temporal-bench [panic]:
go.temporal.io/sdk/internal.panicIllegalState(...)
/Users/quinnklassen/go/pkg/mod/go.temporal.io/sdk@v1.23.0/internal/internal_command_state_machine.go:456
go.temporal.io/sdk/internal.(*commandsHelper).handleActivityTaskScheduled(0x14000cb7a40, {0x1400077a32a, 0x3}, 0x0?)
/Users/quinnklassen/go/pkg/mod/go.temporal.io/sdk@v1.23.0/internal/internal_command_state_machine.go:1039 +0xec
go.temporal.io/sdk/internal.(*workflowExecutionEventHandlerImpl).ProcessEvent(0x1400102b8d8, 0x14000c9e740, 0x3?, 0x0)
/Users/quinnklassen/go/pkg/mod/go.temporal.io/sdk@v1.23.0/internal/internal_event_handlers.go:1068 +0x210
go.temporal.io/sdk/internal.(*workflowExecutionContextImpl).ProcessWorkflowTask …
```

Change message look ahead

---

internal/internal_update.go
internal/internal_update_test.go

Leave the AcceptedRequest and RejectedRequest fields nil on the Acceptance and Rejection messages respectively. Server has been updated to not look at these fields.
Giving up on reconstituting lost ephemeral update state from this information and thus the server does not look at these fields. Save the bytes for now and add back if we resurrect the server behavior.
1. Closes 
Unit tests here and features tests

Do not send original request msg back to server

---

internal/worker_version_sets.go
internal/worker_version_sets_test.go
test/worker_versioning_test.go

Two minor fixes before release

Fix inconsistent BuildID field name & empty TQ in intent check

---

testsuite/devserver.go
testsuite/interrupt_windows.go
testsuite/process_nonwindows.go
testsuite/process_windows.go

Isolated the Ctrl + break event to dev server
Stopping dev server with `devserver.Stop()` would result in the origin process to be interrupted instead of just the devserver. Ex. Go tests with devserver preemptively exited with RC `1`
1. Closes 
tested with e2e tests in https://github.com/temporalio/cli/pull/257

Isolate Ctrl+Break to dev server instead of console

---

internal/internal_command_state_machine.go
internal/internal_event_handlers.go
test/go.mod
test/replaytests/replay-tests-version-and-mutable-side-effect.json
test/replaytests/replay_test.go
test/replaytests/workflows.go

Use getNextID() when handling mutable side effects
Using `nextCommandEventID` directly does not account for version markers leading to non determinism on replay
1. Closes 
close https://github.com/temporalio/sdk-go/issues/1144
Added a test based on the users reproduction

Use getNextID() when handling mutable side effects

---

internal/internal_task_handlers.go
internal/internal_task_handlers_interfaces_test.go

Make the Go SDK more robust to empty pages from the server when running `IsNextWorkflowTaskFailed`.
I saw without the change to `IsNextWorkflowTaskFailed` the unit test `TestEmptyPages` would return different events and messages if I used the `MockHistoryIterator` to return empty pages every other request or not.

Fix history paging on looking for WFT Fail

---

activity/doc.go

Document exactly when the activity context is cancelled. There is some duplication with what is talked about in `Activity Cancellation`. I am leaving both in so users don't miss anything.

Document when the activity context is cancelled

---

.github/workflows/docker/dynamic-config-custom.yaml
internal/internal_update.go
internal/internal_update_test.go
internal/internal_workflow.go
internal/internal_workflow_test.go
internal/workflow.go
test/integration_test.go
test/workflow_test.go

Prevent modifying workflow state in read only contexts. Track the current execution state in the `dispatcher`
An alternative approach would be to check the state when the command is being recorded, I didn't like that option because workflow state can be modified without a command being generated (like reading from a channel) so it needs to be more generic.
closes https://github.com/temporalio/sdk-go/issues/1000

Prevent modifying workflow state in read only contexts

---

internal/interceptor.go
internal/interceptor_base.go
internal/internal_event_handlers.go
internal/internal_event_handlers_test.go
internal/internal_update.go
internal/internal_update_test.go
internal/internal_worker_base.go
internal/internal_workflow.go
internal/internal_workflow_test.go
internal/internal_workflow_testsuite.go
internal/workflow.go
internal/workflow_testsuite.go
test/integration_test.go
test/workflow_test.go
workflow/workflow.go

Add support for update info to allow update handlers and validators to know their update ID.

Add support for update info

---

internal/interceptor.go
internal/interceptor_base.go
internal/interceptortest/proxy.go
internal/workflow.go

add interceptors for `Await` and `AwaitWithTimeout`
closes: https://github.com/temporalio/sdk-go/issues/1155

Add interceptors for Await and AwaitWithTimeout

---

internal/internal_workflow_testsuite.go
internal/workflow_testsuite_test.go

Update the runningWorkflows map with the specified ID if set
closes: https://github.com/temporalio/sdk-go/issues/1160

Reassign runningWorkflows workflow ID in test environment

---

.github/workflows/ci.yml

Removing the ref and head_ref from the workflow logs.
Directly using this user-modifiable information without setting it as a variable first is considered an injection vulnerability. However, since it's not really useful, just remove it.
How was this tested:
Just did the static analysis and unit tests.

Remove unused info in CI workflow logs

---

interceptor/interceptor.go
internal/interceptor.go

`UpdateInput` that the interceptor uses is not exposed out of `internal`, also the interceptor was not marked as experimental.

Expose update interceptor input

---

internal/internal_worker.go

During replay, the no-op metrics handler is hardcoded in the worker execution parameters.
Previously `MetricsHandler` was always nil. This caused "No metrics handler configured for temporal worker" logs to be emitted during replay, which could get noisy and cause confusion about whether this was due to some sort of misconfiguration.
1. Closes
N/A
Manually verified the log line is removed during replay.
No

Hardcode noop metrics handler during replay

---

activity/activity.go
internal/activity.go
internal/activity_test.go
internal/internal_activity.go
test/activity_test.go
test/workflow_test.go

Expose `IsLocalActivity` in activity info
closes https://github.com/temporalio/sdk-go/issues/648

Add IsLocalActivity to ActivityInfo

---

internal/interceptor.go
internal/internal_workflow_client.go
test/integration_test.go

Make `QueryWorkflowWithOptions` go through the interceptor. Originally `QueryWorkflowWithOptions` was called by the interceptor which is wrong.
closes https://github.com/temporalio/sdk-go/issues/991

Make QueryWorkflowWithOptions go through interceptor

---

internal/activity.go
test/integration_test.go
test/workflow_test.go

Clarify our activity options and align the language used with the docs a bit more https://docs.temporal.io/dev-guide/go/features#activity-timeouts
Closes https://github.com/temporalio/sdk-go/issues/675

Clarify ScheduleToStartTimeout in ActivityOptions

---

internal/internal_public.go
internal/internal_task_handlers.go
internal/internal_task_handlers_interfaces_test.go
internal/internal_task_handlers_test.go
internal/internal_task_pollers.go
internal/internal_task_pollers_test.go
internal/internal_worker.go
internal/internal_worker_test.go

Lifted the workflow context lock out of WFTaskHandler.ProcessWorkflowTask up into the surrounding Poller. Having the lock managed at this higher level allows us to include the RespondWorkflowTaskCompleted call and the (potential) reset of the expected next event ID into the same atomic block.
Failure to hold this lock while responding to a workflow task allows in-flight tasks to race past each other which has led to history corruption in the case where responses are not deduplicated. Furthermore the correctness of resetting the event level while not holding this lock is unclear at best.
1. Closes 
New unit test here plus some time in the bench-go rig

Expand WF context locking to cover WFT responses

---

internal/version.go

Release Go SDK v1.24.0
Draft release: https://github.com/temporalio/sdk-go/releases/tag/untagged-4125c75251b0ddc509ce

Release v1.24.0

---

internal/activity.go
internal/internal_activity.go
internal/internal_event_handlers.go
internal/internal_task_handlers.go
internal/internal_task_pollers.go
internal/internal_workflow_testsuite.go
test/activity_test.go
test/integration_test.go
test/workflow_test.go

This PR fixes a few issues with local activities in Got
- `ScheduleToCloseTimeout` was overriding `StartToCloseTimeout` if both were set
- The docs in `LocalActivityOptions` were not accurate
- If a local activity did timeout it would always be considered a `SCHEDULE_TO_CLOSE` timeout and that is not retry able
- `ActivityInfo` in local activities was missing some fields

Fix LA start to close timeout

---

internal/client.go
internal/error.go
internal/schedule_client.go
internal/session.go

Fixed spelling in code comments
Fix spelling errors
N/A
1. Closes 
N/A
N/A
N/A

fixing spelling errors in comments

---

internal/internal_worker.go
internal/internal_worker_base.go
test/integration_test.go

Fix race condition in eager WF start reported by `roadrunner`
https://github.com/roadrunner-server/rr-e2e-tests/actions/runs/5790984816/job/15695006300#step:10:963
removed checking `isWorkerStarted` because  `pollerRequestCh` will not have any slots if the worker has not started, also moved when the worker is registered to after it is started instead of when it is created.

Fix race condition with eager workflow start and close

---

internal/internal_eager.go
internal/internal_eager_activity.go
internal/internal_eager_activity_test.go
internal/internal_eager_workflow.go
internal/internal_eager_workflow_test.go
internal/internal_worker_base.go

Fix a race condition on the `WaitGroup` in `baseWorker` with eager dispatch (activity and workflow) on worker shutdown.
In Go `WaitGroups` have confusing concurrency rules https://pkg.go.dev/sync#WaitGroup.Add:
```
Note that calls with a positive delta that occur when the counter is zero must happen before a Wait. Calls with a negative delta, or calls with a positive delta that start when the counter is greater than zero, may happen at any time. Typically this means the calls to Add should execute before the statement creating the goroutine or other event to be waited for. If a WaitGroup is reused to wait for several independent sets of events, new Add calls must happen after all previous Wait calls have returned. See the WaitGroup example.
```
Here is the situation
1. Eager executor …

Fix race condition in eager dispatch

---

activity/activity.go

Saw this multiple times in the past month were users are using `RecordHeartbeat` incorrectly

Add note on heart beating and async activities

---

test/integration_test.go

Fix flaky `TestAsyncActivityCompletion` test. The issue is there is a race between when the server says an activity is started vs when the worker appends a value to `ts.activities.invoked()`
Example failure https://github.com/temporalio/sdk-go/actions/runs/5829018433/job/15807779883

Fix flaky TestAsyncActivityCompletion

---

internal/internal_event_handlers.go
internal/internal_workflow_testsuite.go
internal/workflow.go
internal/workflow_testsuite.go

Add continueAsNewSuggested and currentHistorySize to workflow info

Add new fields to workflow info

---

workflow/doc.go

Seen this come up from internal and external users of Temporal get confused when they try to return a result and an error. Clarify this is not  supported.

Clarify what happens if an error and result are returned

---

test/integration_test.go

Fix flake in `TestQueryOnlyCoroutineUsage`. I believe the issue here is the coroutine is cleaned up after the query response is returned to the server so the test can assert before the last goroutine is cleaned up. 
Before my change the test would fail ~10% of the time locally. Not it does not fail after 1000 iterations
example failure: https://github.com/temporalio/sdk-go/actions/runs/5933076179/job/16087965782

Fix flake in TestQueryOnlyCoroutineUsage

---

internal/internal_task_handlers.go
internal/internal_task_handlers_interfaces_test.go

Finally doing a long asked for refactor of `NextCommandEvents` from 5 return values to a struct. The logic of the code still isn't great, but it is a bit better now. 
Doing now because I know I'll touch this code more when I do: https://github.com/temporalio/sdk-go/issues/1194

Refactor NextCommandEvents

---

Makefile
internal/internal_workflow.go
internal/workflow.go
test/integration_test.go
test/workflow_test.go

Fix race condition during cache eviction
see https://github.com/temporalio/sdk-go/issues/1209 for more details

Fix race condition during cache eviction

---

test/replaytests/child-workflow-cancel-with-update.json
test/replaytests/replay_test.go
test/replaytests/workflows.go

@alexshtin Reported a non determinism in bench-go. The failings workflow event history was very long, but the section that failed was similar to `child-workflow-cancel-with-update.json`. Specifically the sequence of events `WorkflowTaskCompleted `,`RequestCancelExternalWorkflowExecutionInitiated`, `WorkflowExecutionUpdateAccepted`, `ActivityTaskScheduled` was causing non determinism about activity ID mismatch. The root cause was a Go SDK counting bug because the SDK was not accounting for the command that resulted in `RequestCancelExternalWorkflowExecutionInitiated` because the command was not being generated when the workflow was cancelling.
I already, unintentionally, fixed this bug in this [commit](https://github.com/temporalio/sdk-go/commit/30c8ca297514dae65f8b7003489f67cdef7180ac). …

Add test for child wf cancel and update

---

internal/internal_event_handlers.go
internal/log/replay_logger.go
log/logger.go
log/slog.go
log/slog_test.go
log/with_logger.go
test/logger_test.go

Add an adapter for the new `slog` and add support for an optional interface `Logger` can implement to skip caller stacks.
Marking as draft because the adapter and skip feature need unit tests and I need to read how to test `slog`
closes https://github.com/temporalio/sdk-go/issues/1158
closes https://github.com/temporalio/sdk-go/issues/685
closes https://github.com/temporalio/sdk-go/issues/960

Add slog adapter

---

internal/internal_worker.go
test/replaytests/deadlocked-workflow.json
test/replaytests/replay_test.go
test/replaytests/workflows.go

This PR adds a new field `DisableDeadlockDetection` to `WorkflowReplayerOptions`. Setting this to `true` disables deadlock detection during replay.
The `TEMPORAL_DEBUG` environment variable is intended to serve a similar purpose, but can be [tricky to configure](https://github.com/temporalio/sdk-go/issues/329#issuecomment-1464894075) and is a global setting.
Deadlock detection can be disabled programmatically using `DeadlockDetectionTimeout` on `worker.Options`. It makes sense to support something similar in `WorkflowReplayerOptions` since attaching a debugger is such a common use case when replaying workflows.
Please see included unit test.
The updated godoc is probably enough, though this would be a useful feature to mention in tutorials about workflow debugging.

Add replay option to disable deadlock detection

---

client/client.go
internal/client.go

This fixes the documentation around using `ListWorkflow` for querying open workflows.
The comment appeared to be incorrect, at least WRT temporal cloud.  `CloseTime = missing` doesn't appear to be a valid query, whereas `CloseTime is null` seems to do what you'd expect.
1. Closes 
This is just a change to a comment. I tested the accuracy of the documentation via trial and error (also via the Temporal Cloud web UI).

Fix the documentation of ListWorkflow for querying open workflows

---

workflow/workflow.go

Clarify GetLastCompletionResult works with schedules as well as cron

Clarify GetLastCompletionResult works with schedule

---

workflow/deterministic_wrappers.go

Misc minor doc comment improvements in `deterministic_wrappers.go`.

Edit doc comments in deterministic_wrappers.go

---

.github/workflows/ci.yml

Switch to our regular `sdk-ci` namespace instead.
The `tinycicd` namespace is going away.
2. How was this tested: Testing in GHA via this PR
3. Any docs updates needed? No

Stop using the tinycicd namespace for tests

---

contrib/opentelemetry/tracing_interceptor.go
contrib/opentelemetry/tracing_interceptor_logger_test.go

Hello :)
This PR adds the TraceID and the SpanID to the logger fields.
From the [opentelemetry spec](https://opentelemetry.io/docs/specs/otel/logs/#log-correlation):
> It is a standard practice to record the execution context (trace and span ids as well as user-defined context) in the spans. OpenTelemetry extends this practice to logs where possible by including [TraceId](https://opentelemetry.io/docs/specs/otel/logs/data-model/#field-traceid) and [SpanId](https://opentelemetry.io/docs/specs/otel/logs/data-model/#field-spanid) in the LogRecords. This allows to directly correlate logs and traces that correspond to the same execution context. It also allows to correlate logs from different components of a distributed system that participated in the particular request execution.
2. How was …

feat(contrib/opentelemetry): add TraceID and SpanID fields to the logger

---

activity/doc.go
client/client.go
contrib/tally/handler.go
interceptor/interceptor.go
interceptor/tracing_interceptor.go
temporal/doc.go
worker/worker.go
workflow/deterministic_wrappers.go
workflow/doc.go
workflow/workflow.go

I backfilled doc links throughout our user-facing APIs. I didn't touch the internal package as those aren't supposed to be for external consumption.
While here I cleaned up a few things, like adding links to referenced code samples and removing a doc comment in a spot where they're unsupported; you can't add links in the comments on interface methods or struct members.
Linking readers to referenced APIs saves them time when trying to understand how to use temporal.
This was tested by running godoc locally and inspecting the rendered docs. Note that [cross-package doc links still don't work](https://github.com/golang/go/issues/56683) so cannot be verified locally.

Add doc links throughout our user-facing APIs

---

internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
internal/workflow_testsuite.go

This extends the `TestWorkflowEnvironment` to expose a new `SetContinuedAsNewRunID` API to set the workflow under test `ContinuedAsNewRunID` field in its `WorkflowInfo`.
When building some workflows ("actors" like ones are a good example), you sometimes want to be able to distinguish when a workflow is starting and when it's being continued as new. This allows you to execute different behavior like restoring some state from an external system.
One way to check if your current workflow execution has been continued as new is to inspect the workflow info `ContinuedAsNewRunID` field. When it's set, then you now you are not starting fresh. It is nice because you don't need any special field in your workflow inputs to detect such cases.
Example:
```golang
func MyWorkflow(ctx workflow.Context, …
```

Expose SetContinuedAsNewRunID in the TestWorkflowEnvironment

---

test/integration_test.go

Decrease iterations of TestVersionLoopWorkflow because the current number can sometimes cause a deadlock detection in CI
closes https://github.com/temporalio/sdk-go/issues/1236

Decrease iterations of TestVersionLoopWorkflow

---

internal/internal_worker.go
internal/internal_worker_test.go
internal/worker.go

Disable running sessions and versioned workers together because they are not currently compatible
closes https://github.com/temporalio/sdk-go/issues/1234

Disable running sessions on a versioned worker

---

internal/client.go
internal/internal_workflow_client.go
test/integration_test.go

Expose StartDelay in StartWorkflowOptions. I didn't test the server behaviour since I didn't want to duplicate the server tests and timing tests in the SDK have proven to be flaky
closes https://github.com/temporalio/sdk-go/issues/1243

Expose StartDelay in StartWorkflowOptions

---

internal/internal_event_handlers.go
internal/internal_task_handlers.go
internal/internal_task_handlers_interfaces_test.go
internal/version.go
test/integration_test.go

Add SDK name and version to the SDK metadata on WFT complete. Only write if this is the first time or a change.
closes https://github.com/temporalio/sdk-go/issues/1194

Add SDK version and name to history

---

internal/client.go
internal/internal_eager_workflow.go
internal/internal_eager_workflow_test.go
internal/internal_workflow_client.go

Don't register a versioned worker for eager workflow start.
closes https://github.com/temporalio/sdk-go/issues/1250

Don't register a versioned worker for eager start

---

internal/internal_command_state_machine.go
internal/internal_event_handlers.go
internal/internal_event_handlers_test.go
internal/internal_task_handlers.go
internal/internal_task_handlers_test.go
internal/internal_update.go
test/integration_test.go

Fix a bug found during internal testing where the workflow state machine was panicing, but because the panics were not recovered properly the worker never responded and the task timed out.
added some unit tests, I couldn't come up with an integration test to test this because the server should never cause the update protocol state machine to panic. 
closes https://github.com/temporalio/sdk-go/issues/1252

Convert panics in update protocol state machine to errors

---

.github/workflows/docker/dynamic-config-custom.yaml
client/client.go
internal/client.go
internal/internal_workflow_client.go
internal/worker_version_sets.go
mocks/Client.go
test/worker_versioning_test.go

Add task reachability API `GetWorkerTaskReachability` to Go.
closes https://github.com/temporalio/sdk-go/issues/1237

Add TaskReachability API

---

internal/client.go
internal/internal_eager_workflow.go
internal/internal_eager_workflow_test.go

After internal discussion it appears the consensus around eager workflow start and versioning is to accept and document that eager workflow start and worker versioning do not interact.
effectively reverts https://github.com/temporalio/sdk-go/pull/1251

Allow eager workflow start on versioned worker

---

internal/version.go

Release Go SDK v1.25.0
Draft release: https://github.com/temporalio/sdk-go/releases/tag/untagged-573dc8f1278b19aeffad

Release v1.25.0

---

internal/internal_workflow_testsuite.go
internal/workflow_testsuite.go
internal/workflow_testsuite_test.go

closes https://github.com/temporalio/sdk-go/issues/1263

Add UpdateWorkflowByID to TestWorkflowEnvironment

---

internal/log/logger_test.go
internal/log/memory_logger.go
internal/log/replay_logger.go
log/with_logger.go
log/with_logger_test.go

Fix a regression introduced in https://github.com/temporalio/sdk-go/pull/1219 that caused loggers wrapped with `withLogger` to log key values as a slice 
another option is to remove `WithCallerSkip` from `withLogger`
closes https://github.com/temporalio/sdk-go/issues/1266

loggerWith.WithCallerSkip expand keyvals

---

internal/version.go

Release Go SDK v1.25.1
https://github.com/temporalio/sdk-go/releases/edit/untagged-2ae75360b50773575f0b

Release v1.25.1

---

contrib/opentelemetry/tracing_interceptor.go
test/activity_test.go
test/integration_test.go
test/workflow_test.go

This PR updates the OTEL tracing interceptor implementation to allow [OTEL Baggage](https://opentelemetry.io/docs/concepts/signals/baggage/) to be propagated.
This seems to be an omission from the existing OTEL tracing interceptor implementation, and should be included so that Temporal doesn't break baggage propagation. For my particular use-case, this allows for spans to add baggage as attributes in the `SpanStarter` func.
1. Closes 
The existing unit tests were used to ensure this didn't break existing functionality. Though, there doesn't seem to be a way to include context (for the purpose of including baggage) in the emulated test environment. As such, I'm looking for guidance on how to best test this MR.
No

Propogate Baggage in OTEL tracing interceptor

---

internal/error.go
temporal/error.go

Fix error documentation typos and enum values. Also sync internal and exported documentation.
Fix out of date documentation.

Fix error documentation typos and enum values

---

converter/proto_json_payload_converter.go

I added options to be passed to marshaler code for Proto/JSON.
Automatic OCaml deserialization of JSON-encoded Protobuf does not work if empty (nil) fields are not present.
1. Closes 
I observed in my own code the expected result, i.e. JSON-encoded Protobuf now contains nil fields.

Add more marshaler options for ProtoJson converter

---

internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go

Add context propagators when executing a local activity in a test environment.
Fix for the linked issue
1. Closes #1290 
A unit test was added
Nope

Add context propagators to local activity executions through test environments

---

temporal/error.go

Fix some typos in the example for handling errors
Fix some typos on the documentation about error handling
This change was done for two reasons:
1. It was unsatisfying to see
2. If someone copies the example and uses it as a base for their own error handling the example should be working.
This only includes some changes to comments so no executable code is affected. Therefor it is untested

fix typo in documentation

---

.github/workflows/ci.yml

sdk-go now uses the official features repo, not my fork.
This needed to point at my fork temporarily so that I could release a new version of that repo (which relies on the go SDK).

Use the official features repo

---

internal/workflow_testsuite.go
internal/workflow_testsuite_test.go

This PR adds a `NotBefore` method to the `testsuite.MockCallWrapper`.
It indicates that a mock call must not happen before the given set of other mocks have been called as expected.
The actual functionality for this is already implemented in `github.com/stretchr/testify/mock`.
The new function forwards to the `.NotBefore()` method on the wrapped `mock` object.
This change further improves the testability of workflows.
It allows to specify the exact sequence that activities and child-workflow executions must happen.
For example, "call activity abc, then execute child-workflow xyz"
1. Closes:
No issue found. 
Added an additional unit test.
1. Any docs updates needed?:
Go docs should update automatically.

Add `NotBefore` function to `testsuite.MockCallWrapper`

---

.github/workflows/ci.yml
contrib/datadog/go.mod
contrib/datadog/go.sum
contrib/opentelemetry/go.mod
contrib/opentelemetry/go.sum
contrib/opentracing/go.mod
contrib/opentracing/go.sum
contrib/tally/go.mod
contrib/tally/go.sum
go.mod
go.sum
internal/cmd/build/go.mod
internal/cmd/build/go.sum
test/go.mod
test/go.sum

I upgraded our api-go dependency
Marshaling for binary/null payloads was completely broken, and while there Chad and I decided that shorthand marshaling should be opt-in rather than opt-out.

Bump api-go version to fix Payload marshaling

---

internal/client.go
internal/grpc_dialer.go

Enabled keep alive by default.
https://github.com/temporalio/sdk-go/issues/1248

Enable keep alive by default

---

test/integration_test.go
test/workflow_test.go

`TestWorkflowIDReuseIgnoreDuplicateWhileRunning` was failing because the workflow `WaitSignalReturnParam` was exiting before receiving the second signal.
Fixes https://github.com/temporalio/sdk-go/actions/runs/7040203549/job/19160706031

Fix race in WaitSignalReturnParam

---

.github/workflows/ci.yml

Run cloud tests in series to avoid workflow ID conflict. When running parallel integration tests against the same cloud namespace it is possible if the same test runs at the same time the workflow IDs will conflict causing test failure.
example:
https://github.com/temporalio/sdk-go/actions/runs/7049993619/job/19189705118
Note: this isn't a perfect, the only way to properly fix is to run in separate namespaces or modify all the tests to add a UUID to every workflow and child workflow ID.

Run cloud tests in series to avoid wfID conflict

---

internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go

Don't run workflowCancelHandler in test harness on completed workflows. If a workflow is completed nothing else in the workflow function should run.
closes https://github.com/temporalio/sdk-go/issues/1287

Don't run workflowCancelHandler in test harness

---

test/integration_test.go

Fix assertion is TestNonDeterminismFailureCauseHistoryMismatch. Can cause one or more task failures, depending on the exact timing, the test was incorrect to assert more then one.
https://github.com/temporalio/sdk-go/actions/runs/7089287292/job/19293691402

Fix flaky test

---

converter/codec.go

- Split `remoteDataConverter` into separate `PayloadCodec` and `DataConverter`
- This change is used to fix bugs in and simplify the `temporal` CLI: https://github.com/temporalio/cli/pull/384
1. How was this tested: https://github.com/temporalio/cli/pull/384
2. Any docs updates needed?
No. The change is backwards compatible.

Make remoteDataConverter implement PayloadCodec

---

internal/context.go

Cleaned up dead code in context pkg and replaced incorrect use of go routine in `propogateCancel` with a panic msg
Clean tech-debt from context pkg
1. Closes #1270 
local test-suites
4. Any docs updates needed?
No

Cleanup dead code and incorrect use of go routine in context pkg

---

internal/internal_update.go
internal/internal_update_test.go
internal/internal_workflow_test.go
test/integration_test.go
test/workflow_test.go

Failed Read-Only check causes a WFT failure in validator
closes https://github.com/temporalio/sdk-go/issues/1272

Failed Read-Only check causes a WFT failure in validator

---

internal/internal_update.go

Include update state machine fields in panic. This will help debug update issues by making it easier to interpret the panics message.

Include update state machine fields in panic

---

internal/workflow.go
internal/workflow_test.go
workflow/workflow.go

Add deterministic range over map helpers for ordered and unordered maps.
Ideally this would be implemented with [range over func](https://github.com/golang/go/wiki/RangefuncExperiment), but it is only experimental in golang 1.22 so we would have to wait over a year to use it assuming it is stabilized in 1.23.
Closes https://github.com/temporalio/sdk-go/issues/359

Add deterministic range over map helper

---

internal/internal_workflow_client.go

Doc string improvement - 😓 
Describe behavior of `WorkflowRun.Get` in the doc string.
This is a contract some folks might rely on, so it's good to encode it via a comment.
1. Closes 
No formal tickets
3. How was this tested:
Comment
4. Any docs updates needed?

Update WorkflowRun.Get Doc String

---

go.mod
go.sum
internal/client.go
internal/cmd/build/go.mod
internal/cmd/build/go.sum
internal/common/retry/interceptor.go
internal/grpc_dialer.go
internal/internal_workflow.go
internal/internal_workflow_client.go
internal/internal_workflow_client_test.go
internal/internal_workflow_testsuite_test.go

go 1.19 introduced atomic types
https://tip.golang.org/doc/go1.19#atomic_types
sync/atomic is already being used here. I intend to update dependencies so that `go.uber.org/atomic` can also be removed as an indirect dependency

Replace go.uber.org/atomic with sync/atomic

---

internal/internal_task_pollers.go
internal/internal_task_pollers_test.go

Evict workflow from cache on RespondTaskCompleted failure
closes https://github.com/temporalio/sdk-go/issues/1357

Evict workflow from cache on RespondTaskCompleted failure

---

internal/internal_worker.go
internal/internal_workers_test.go
internal/worker.go

Currently server does not properly rate limit eager activities. Disabling for now until the Server can address this.

Disable eager activities if tq rate limits is set

---

internal/internal_coroutines_test.go
internal/internal_worker_base.go
internal/internal_workflow.go

Run coroutine exit in sequence to avoid race detector errors on defers in coroutines.
closes https://github.com/temporalio/sdk-go/issues/1235

Exit coroutine in order

---

internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
internal/workflow_testsuite.go

Splitted activity and workflow mocks so you're able to use same names to mock workflows and activities, but the logic of all exported functions kept the same
To be able to use same workflow and activity function names when they are struct methods (avoid tautology, etc.)
1. Closes 
#887 
Added `Test_SameWorkflowAndActivityNames` function that uses same workflow and activity name
No

Fix testing suite name conflict for workflow and activity (#887)

---

internal/client.go
internal/interceptor.go
internal/interceptor_base.go
internal/internal_event_handlers.go
internal/internal_schedule_client.go
internal/internal_search_attributes.go
internal/internal_search_attributes_test.go
internal/internal_worker_base.go
internal/internal_workflow.go
internal/internal_workflow_client.go
internal/internal_workflow_client_test.go
internal/internal_workflow_testsuite.go
internal/schedule_client.go
internal/workflow.go
internal/workflow_testsuite.go
temporal/search_attributes.go
test/integration_test.go
test/test_utils_test.go
test/workflow_test.go
workflow/workflow.go

Implementation of [typed search attributes](https://github.com/temporalio/proposals/blob/master/sdk-typed-search-attributes.md). Specifically:
* Added `TypedSearchAttributes` to `client.StartWorkflowOptions` and deprecated `SearchAttributes`
* Added several new things to `temporal` package including:
* `SearchAttributes` collection with methods and constructor
* `SearchAttributeKey` and `SearchAttributeUpdate` interfaces
* `SearchAttributeKeyX` types and constructors for typed keys
* Added `TypedSearchAttributes` to `client.ScheduleWorkflowAction` and 💥removed `SearchAttributes` and added `UntypedSearchAttributes` (needed until https://github.com/temporalio/temporal/issues/4787 is fixed)
* Added `TypedSearchAttributes` to `client.ScheduleOptions` and deprecated `SearchAttributes`
* Added …

Typed Search Attributes

---

internal/internal_workflow_client.go
internal/internal_workflow_client_test.go

Avoid passing a `nil` to `EncocedValue.Get`. This matches the behaviour of other `Get` calls in the SDK

Handle nil valuePtr case in update handler Get

---

internal/internal_worker_cache.go

Add lock/unlock to `desiredWorkflowCacheSize` in `func NewWorkerCache() *WorkerCache`.
Prevent data race.
1. Closes https://github.com/temporalio/sdk-go/issues/1375
2. How was this tested: Run the test in ticket description to verify.
3. Any docs updates needed? No

Fix data race on desiredWorkflowCacheSize

---

internal/client.go
internal/grpc_dialer.go

The default values for keep-alive were mistakenly assigned earlier. This PR brings the alignment with the server other SDKs:
Java:
https://github.com/temporalio/sdk-java/blob/master/temporal-serviceclient/src/main/java/io/temporal/serviceclient/ServiceStubsOptions.java#L333-L334
TS:
https://github.com/temporalio/sdk-typescript/blob/main/packages/client/src/connection.ts#L130-L131
Keep the default gRPC keep-alive consistent with server and other SDKs.

Rectify the default values for keep-alive timeout

---

client/client.go

closes https://github.com/temporalio/sdk-go/issues/1372

Document GetSearchAttributes is not supported on cloud

---

internal/internal_search_attributes.go
internal/internal_workflow_testsuite_test.go
internal/workflow_testsuite.go

Clarify `OnUpsertTypedSearchAttributes` does not expect the actual args to `workflow.UpsertTypedSearchAttributes` , but the result `temporal.SearchAttributes`. We can't take the actual args since we can't have mock asserts on functions.

Clarify OnUpsertTypedSearchAttributes

---

internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
internal/workflow_testsuite.go

Added a function in `TestWorkflowEnvironment` to allow canceling arbitrary workflows, in line with `SignalWorkflowByID` and `QueryWorkflowByID`
This makes it possible to cancel child executions and test the behavior of doing so.

Make it possible to cancel workflows by ID when testing

---

internal/error.go

Add a note NextRetryDelay is not supported on the server yet so users shouldn't expect it to work. We debated a few option internally, since we don't know what version of the server will support it the options are comment the option out or add a comment. I chose to add a comment since when the Server does add support users won't need to upgrade their SDKs, but I am open to other options.

Add note NextRetryDelay is not supported on the server

---

internal/internal_event_handlers.go
internal/internal_task_handlers.go
internal/internal_task_pollers.go
internal/internal_workflow.go
internal/internal_workflow_client.go
test/integration_test.go
test/workflow_test.go

Only set `SDKPriorityUpdateHandling` if workflow update is being used. Previously `SDKPriorityUpdateHandling` was set at the start of every workflow, this made it difficult to roll back the Go SDK to a previous version that did not understand `SDKPriorityUpdateHandling` without workflows getting stuck . Now rollback will only be blocked if a user was using workflow update.
Using workflow update in a workflow execution means:
* Registered an update handler
* Received any update requests
I also changed the type of an unknown SDK flag error to be treated as non deterministic to align with the behaviour of a missing workflow version call since SDK flags are basically internal SDK version calls.
* So all new workflow executions would always use the new correct update behaviour.
* Because that …

Only set SDKPriorityUpdateHandling if workflow update is being used

---

internal/internal_flags.go
test/replaytests/replay_test.go
test/replaytests/workflow_with_SDK_priority_flag_set.json

Recognize, but do not handle SDKPriorityUpdateHandling flag to avoid unknown flag error. This will allow for safe downgrade  for workers using SDK version between  `1.25.1` and `1.26.0-RC.2` that set this flag unconditionally.

Recognize SDKPriorityUpdateHandling flag

---

test/activity_test.go
test/integration_test.go
test/workflow_test.go

This PR adds an integration test to validate that we allow invalid UTF-8 data in strings.
You will need to run the server locally as of https://github.com/temporalio/temporal/pull/5476, then execute the integration tests.
This test has been manually verified as passing on SDK version 1.25.0 and server version 1.22.5, so we should remain compatible with our pre-google/protobuf behavior
1. Ready this for review once the server and CLI support this

Add a test to validate behavior when invalid UTF-8 data is present

---

client/client.go
internal/client.go
internal/grpc_dialer.go
internal/grpc_dialer_test.go

* Added `client.Credential` interface (cannot be implemented by users for now)
* Added `client.NewAPIKeyCredentials` and `client.NewAPIKeyCallbackCredentials` calls to create credentials
* These don't accept "options" structures for future proofing like some other calls, that ok? We can add as many of these calls as needed later.
* We chose to overwrite any existing authorization headers so there is no ambiguity (e.g. it is confusing to say "creds overwrites header provider, but context overwrites creds" IMO, they should just not set the creds if they need to overwrite). This ok?
* Added `client.NewMTLSCredentials` to simplify TLS config for client key/cert only
Yes, all of this is mostly trivial for users to do themselves (or just call `ctx = metadata.AppendToOutgoingContext(ctx, …

API key support via credentials abstraction

---

internal/client.go
internal/grpc_dialer_test.go

To match other SDK implementations coming with API keys and in general, we decided that user-provided headers/metadata can override the client-level API key setting instead of the inverse.

Override API key with user metadata

---

client/client.go
internal/client.go
internal/grpc_dialer_test.go
internal/internal_schedule_client.go
internal/internal_worker.go
internal/internal_workflow_client.go
internal/internal_workflow_client_test.go

This PR exposes new `DialContext` and `NewClientFromExistingWithContext` APIs that take a context as input and propagates it down the stack until all synchronous server calls so timeout and cancellation can be controlled by the callers.
The PR also replaces `grpc.Dial` call by `grpc.DialContext` and propagate user defined context down to the grpc dial call properly. Doing so means when users use `grpc.WithBlock()` dial option, they will be in control of the dial timeout
When clients use `Dial` or `NewClientFromExisting` APIs to start, they connect to the server and try to load capabilities synchronously. However, clients have no control over the timeouts and cancellation of such requests. They can't extend timeouts to accommodate slow networks or appropriately cancel those calls.
1. …

Make client Dial context controlable by callers

---

.github/workflows/ci.yml

Switch github runner to macos-14 (m1). Currently `macos-latest` runs on `macos-12` on intel. Reading some docs at some point github will change `macos-latest` to point at `macos-14`, but we can update our CI sooner.
https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/

Switch github runner to macos-14 (m1)

---

internal/client.go

Removed the experimental flag from Start Delay option
To properly indicate the current state of the Start Delay workflow option

Remove experimental flag from Start Delay

---

.gitignore
client/client.go
internal/client.go
internal/internal_workflow_client.go
internal/worker_versioning_rules.go
internal/worker_versioning_rules_test.go
mocks/Client.go
test/worker_versioning_test.go

This is the first installment of supporting the new versioning rules in the go sdk. It provides
support for updating and listing both assignment and redirect rules.
It does not include reachability info yet.
1. Closes 
Nothing to close yet
Added unit and system tests. To pass system tests use a versioning-2 server branch as target.

Support Update and Get for the new versioning rules

---

client/client.go
internal/client.go
internal/internal_workflow_client.go
internal/worker_versioning_rules.go
internal/worker_versioning_rules_test.go
mocks/Client.go
test/worker_versioning_test.go

Change the response of UpdateWorkerVersioningRules to match GetWorkerVersioningRules as suggested by @cretz 
Eliminates unnecessary round-trips to the server, simpler API...

Change UpdateWorkerVersioningRules response to match GetWorkerVersioningRules

---

workflow/deterministic_wrappers.go

I updated the description of `workflow.Now`, which appears in the Go SDK API documentation, to clarify that the value it returns during replay is the same as it did before. 
The original wording was confusing and could be misinterpreted as suggesting that, during replay, it returned the current time instead of the time that was current when that task was initially started.
1. Closes N/A
I discussed this with members of the SDK team. They confirmed my understanding that the value returned by this function didn't change during replay. The wording I propose here was suggested by Chad Retz.
This is a change to the Go SDK API documentation. I don't believe that any other changes are necessary.

Clarified description of workflow.Now

---

client/client.go
internal/worker_versioning_rules.go
test/worker_versioning_test.go

The api is renaming insert_compatible_redirect_rule to add_compatible_redirect_rule to reflect that there can only be one rule
active per source. 
This trivial PR just renames types to be consistent with the new api, and uses the new go proto stubs.

Rename insert_compatible_redirect_rule to add_compatible_redirect_rule in api

---

internal/internal_event_handlers.go
internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
internal/workflow.go
test/integration_test.go
test/workflow_test.go

Fix support for typed search attributes in child workflow options
Specifying `TypedSearchAttributes` on `ChildWorkflowOptions` does not propagate search attributes to the child workflow.
1. Closes
n/a
- Added unit test
- Tested against local temporal server
n/a

Fix support for typed search attributes in child workflow options

---

internal/common/metrics/grpc.go
internal/common/metrics/grpc_test.go

Ensure that all rpc metrics have a `namespace` label, by setting it to `_unknown_` if it can't be derived from the request.
This was mentioned here: https://github.com/temporalio/sdk-go/issues/861#issuecomment-1191524477 and the resolution was to derive the `namespace` label from the request, which is great, but it should be consistent.
Many observability systems don't like the same metric to be emitted with different label sets.
1. Closes 
updated unit test

Ensure consistent labels for rpc metrics

---

internal/cmd/build/main.go
test/integration_test.go

When doing tests with the about-to-be-released CLI, we discovered that the dev server there disallows invalid UTF8 but the traditional server still allows it. We want to disallow it in the CLI dev server, so, we are just disabling tests that confirm invalid UTF8 is ok when using the dev server.

Disable UTF8-invalid tests when running CLI dev server

---

internal/internal_task_handlers.go

Improve error message for missing body in update message, without the ID it would be very annoying to debug if this ever does happen.

Improve error message for missing body

---

testsuite/devserver.go
testsuite/process_nonwindows.go
testsuite/process_windows.go

Add a `Stdout` and `Stderr` options to `DevServerOptions` that if it's not `nil` will redirect the spawned server stdout and stderr to them.
Option to redirect devserver stdout/stderr to different streams.
Add a `Stdout` and `Stderr` options to `DevServerOptions` that if it's not `nil`
will redirect the spawned server stdout and stderr to this file.
We're embedding the dev server in out app, and when we close it we get huge amount of logs from the underlying dev server.
1. Closes 
Ran the current tests.
Maybe https://docs.temporal.io/dev-guide/go/testing, not sure.

Option to redirect devserver stdout/stderr to a file

---

internal/internal_update.go
internal/internal_update_test.go

Require update handler to have a context as the first parameter.
Note this is a breaking change
closes: https://github.com/temporalio/sdk-go/issues/1455

Require update handler to have a context

---

internal/error.go
internal/internal_task_handlers.go
internal/internal_workflow_testsuite.go
internal/internal_workflow_testsuite_test.go
test/activity_test.go
test/integration_test.go
test/workflow_test.go

Add support for NextRetryDelay for local activities and the test suite
closes https://github.com/temporalio/sdk-go/issues/1454

Add support for NextRetryDelay for local activities

---

internal/internal_workflow_client.go
test/integration_test.go
test/workflow_test.go

Actually pass through QueryRejectCondition on QueryWorkflowWithOptions
closes https://github.com/temporalio/sdk-go/issues/1460

Fix QueryRejectCondition parameter in QueryWorkflowWithOptions

---

internal/worker.go
test/bindings_test.go
test/integration_test.go

Remove DisableStickyExecution, this flag has done nothing for 4 years and is time to remove since it causes confusion.

Remove DisableStickyExecution

---

internal/worker_version_sets.go
internal/worker_version_sets_test.go
internal/worker_versioning_rules_test.go
temporal/build_id_versioning.go

Added `InheritBuildID` and `UseAssignmentRules` to `VersioningIntent` enum, replacing (now deprecated) `Default` and `Compatible` options, respectively.
New options follow new versioning terminology and are more to-the-point. The old option can be confusing when used with new versioning rule concepts:
- `Compatible` could be seen as to have to do with using/not-using `CompatibleRedirectRule`s, while this option is not about redirect rules and solely means keep the same build ID as the parent/previous wf instead of selecting an independent build ID.
- `Default` is not clear because there is no more a "default version set" concept that this could refer to, instead the build ID has to be chosen based on the assignment rules. Moreover, the existence of the concept of "default build ID" (as …

Add new VersioningIntent options

---

internal/client.go
internal/common/metrics/constants.go
internal/common/metrics/grpc.go
internal/common/metrics/grpc_test.go
internal/common/metrics/tags.go
internal/grpc_dialer.go
internal/grpc_dialer_test.go
test/integration_test.go

Added error code labels to request failure metrics w/ an option to disable.
Go part of https://github.com/temporalio/features/issues/144
1. Closes https://github.com/temporalio/features/issues/144
Added IT
For the option

Add request failure code label to metrics

---

testsuite/freeport.go

- When assigning ephemeral ports for use by the Temporal Server, on all platforms except MacOS and Windows, immediately open a connection to that port, and force the connection into `TIME_WAIT` state. This avoids various race conditions that could happen due to the port being reallocated between the moment the port is obtained and the moment the server actually binds to that port. See temporalio/cli#564 for details.

get-free-port: prevent duplicate ports on Linux

---

internal/internal_task_pollers.go
test/integration_test.go

closes https://github.com/temporalio/sdk-go/issues/1465

Only record activity_succeed_endtoend_latency on success

---

converter/grpc_interceptor_test.go
internal/client.go
internal/common/metrics/grpc_test.go
internal/grpc_dialer.go
internal/grpc_dialer_test.go

calls to `grpc.Dial()` have been replaced with `grpc.NewClient()`
`grpc.Dial()` is deprecated
1. Closes 

Replace grpc.Dial with grpc.NewClient

---

.github/workflows/ci.yml
client/client.go
internal/client.go
internal/interceptor.go
internal/interceptor_base.go
internal/internal_update.go
internal/internal_workflow_client.go
internal/internal_workflow_client_test.go
mocks/Client.go
test/integration_test.go
test/workflow_test.go

This PR makes multiple changes to the client experience around update:
* Merge `UpdateWorkflowWithOptions` and `UpdateWorkflow` to a single api 
* Makes `WaitForStage` a required parameter in update
* Create a Go SDK enum for update lifecyle
*  Updated start update polling to poll until stage reached or ACCEPTED. If more polling needed, switches to result polling.
closes https://github.com/temporalio/sdk-go/issues/1414
closes https://github.com/temporalio/sdk-go/issues/1449
closes https://github.com/temporalio/sdk-go/issues/1411
since this has multiple breaking changes feature tests are expected to fail until I make a separate branch

Workflow update client API refactor

---

internal/internal_workflow_testsuite.go
internal/workflow_testsuite_test.go

Follow up to #1484, fixing a couple of issues with using a custom failure converter:
1. We weren't correctly threading the failure converter down to activities and child workflows, so they were still using the default converter.
2. The `NonRetryable` flag on the protobuf failure type wasn't being honored for custom errors.
I tested this change against our app's test suite, but it could probably use a case in the SDK's test suite itself. I'd be happy to add that if you're happy with this approach generally.

Fix bugs when using a custom `FailureConverter` in tests

---

log/logger.go
log/with_logger.go

1. Move `WithLogger` interface close to others (same package, different file)
2. Add skip 1 for default `WithLogger` implementation
1. Moving  `WithLogger` interface allow user to see all available interfaces in one place. It increase user experience
2. Adding `Skip` function to the `withLogger` constructor functions allows to skip `with_logger.go` from the stack
1. How was this tested: All existing tests passed, local using replaced package
1. Any docs updates needed? nope

Minor logger improovments

---

test/integration_test.go

Remove `sleep` and use `eventually` to make the test more robust.

Make backfill tests more robust

---

client/service_proxy.go

Manually copy proxy options instead of using type conversion. This allows API library options to be added to independently of SDK and users SDKs won't break when added (noticed when working on https://github.com/temporalio/api-go/pull/167).

Manually copy proxy options

---

testsuite/devserver.go
testsuite/devserver_internal_test.go

**Background:**
testsuite.StartDevServer accepts a context.Context
meant to indicate how long the caller is willing to wait for the result.
This context is used when downloading the Temporal CLI,
but is not considered when trying to dial to the server in
`waitServerReady`.
**Change:**
This changes `waitServerReady` to respect the timeout configured in the
context--checking in on it after each attempt, and returning early
if the context has expired.
Similarly, the `Dial` attempt now uses `DialContext` so that if the context
expires, the dial operation also returns early if it can.
Without this, if an attempt to start the server failed
(e.g. because of an invalid `--log-format` argument),
`waitServerReady` will block the test for 1 minute
before giving up and returning an error.
This is a …

testsuite.StartDevServer: Respect timeout during dial

---

internal/interceptor.go
internal/interceptor_base.go
internal/internal_update.go
internal/workflow.go
test/workflow_test.go
workflow/workflow.go

Change GetUpdateInfo to GetCurrentUpdateInfo and include the update name as part of `UpdateInfo`
Based on the similar python PR: https://github.com/temporalio/sdk-python/pull/544

Change GetUpdateInfo to GetCurrentUpdateInfo

---

internal/internal_task_handlers.go
internal/internal_task_handlers_interfaces_test.go
internal/internal_task_handlers_test.go
internal/internal_task_pollers_test.go

Allow SDK to handle speculative WFT with command events. Originally I thought this change was going to be quite bad, but I realized I didn't need to touch the cacheing logic and could keep it all in the history iteration.

Allow SDK to handle speculative WFT with command events

---

.github/workflows/ci.yml
client/client.go
internal/client.go
test/worker_versioning_test.go

Delete the checks that made some versioning tests run only against a docker ubuntu image.
CLI 0.13 has just been released and it provides a server with versioning support.

Always run all the versioning tests

---

test/integration_test.go
test/workflow_test.go

Add integration test for reset with update events.

Add integration test for reset with update events

---

.github/workflows/ci.yml

Some minor improvements to our CI action:
* Don't fail fast to avoid cancelling tests if one run fails
* Use oldstable and stable to target Go releases to keep CI up to date

Improve CI action

---

internal/error.go

Clean up docs for `NextRetryDelay`. Add missing doc strings and clarify when `NextRetryDelay` is respected.

Clean up docs for NextRetryDelay

---

internal/internal_workflow_testsuite.go
internal/nexus_operations.go
internal/workflow_testsuite.go
temporalnexus/operation.go
test/nexus_test.go

Test environment now supports Nexus Operations.
I've added a partial `Client` implementation for the test env to support what I predict will be the most frequently used methods.
Specifically `WorkflowRunOperation` and `SyncOperation` can use the client to signal and query workflows.
Users can register arbitrary Nexus Operation handlers if they want to mock the operation completely.
This PR is stacked on top of the other two Nexus PRs and completes the basic functionality.

Add test environment support for Nexus Operations

---

interceptor/interceptor.go
internal/client.go
internal/error.go
internal/failure_converter.go
internal/interceptor.go
internal/interceptor_base.go
internal/internal_command_state_machine.go
internal/internal_event_handlers.go
internal/internal_logging_tags.go
internal/internal_nexus_task_poller.go
internal/internal_nexus_worker.go
internal/internal_task_handlers.go
internal/internal_worker_base.go
internal/internal_workflow.go
internal/internal_workflow_testsuite.go
internal/nexus_operations.go
internal/workflow.go
internal/workflow_testsuite.go
temporal/error.go
temporalnexus/operation.go
test/nexus_test.go
workflow/nexus_example_test.go
workflow/workflow.go

Added the ability to execute nexus operations from a workflow.
This PR is stacked on top of https://github.com/temporalio/sdk-go/pull/1466.

Execute nexus operation from a workflow

---

client/client.go
internal/client.go

Update some docs around grpc Dial options because `grpc-go` deprecated `grpc.Dial` so we switched to `grpc.NewClient` that doesn't support some of these dial options because they are anti patterns not recommended by the gRPC team.
https://github.com/grpc/grpc-go/blob/master/Documentation/anti-patterns.md 
Another thing we could do is add a flag to use the old deprecated client options to help who did rely on these options.

Update some docs around grpc Dial options

---

internal/grpc_dialer_test.go
internal/internal_workflow_client.go

Use grpc context for `GetSystemInfo` so proper version info headers are set on `GetSystemInfo`.

Use grpc context for GetSystemInfo.

---

README.md
converter/proto_json_payload_converter.go
test/replaytests/gogoproto-payload-workflow.json
test/replaytests/replay_test.go
test/replaytests/workflows.go

Add option to handle scream snake case enums. This allows handling payloads serialized with GoGoProto after the message type changes. This could happen if the user is using our payloads in their workflows.

Add option to handle scream snake case enums.

---

internal/internal_workflow.go
internal/workflow.go
test/integration_test.go
test/workflow_test.go
workflow/deterministic_wrappers.go

Add workflow safe Mutex and Semaphore. Based on Go standard [Mutex](https://pkg.go.dev/sync) and [Semaphore](https://pkg.go.dev/golang.org/x/sync/semaphore). Notable difference for the `Mutex` is our mutex supports cancellation of a lock request. I did this to match `Semaphore` and most other Go SDK primitives.

Add workflow safe Mutex and Semaphore

---

internal/internal_update.go
internal/internal_workflow.go
internal/protocol/registry.go
internal/workflow.go
internal/workflow_testsuite_test.go
workflow/workflow.go

Warn on unhandled updates and add a function to wait for all update handlers to finish.

Warn on unhandled updates

---

internal/internal_coroutines_test.go
internal/internal_workflow.go
internal/workflow.go

- Added `Name` method to `SendChannel` and `ReceiveChannel` interface
- Added tests to assert `Name`returns back the same given name.
- We have custom wrappers around signalling receive and send calls so that we can attach OpenTelemetry to our signal payload. Since we want our spans to contain the signal name and happen before calling into the underlying `channel.Send` method, ideally we could simplify our API to not require a redundant sending of the channelName again.
- ie. `telemetrytemporal.ChannelSend[T](ctx workflow.Context, channel workflow.SendChannel, channelName string, payload T)`
Closes #1304
- Added "TestChannelName" in `internal/internal_coroutines_test.go` which creates named channels and asserts that the `Name` method returns back the same name you …

add Name method to ReceiveChannel and SendChannel interface

---

client/client.go
internal/worker_version_sets.go
internal/workflow_testsuite.go
mocks/Client.go
temporal/build_id_versioning.go

Fix some misformatted `Deprecated` go docs comments

Fix some Deprecated go docs

---

internal/internal_workflow_testsuite.go
internal/workflow_testsuite_test.go

`updateWorkflowByID` was not targeting the correct workflow handle. This caused updating a child workflow to fail.

Fix bug in updateWorkflowByID

---

internal/internal_schedule_client.go
internal/schedule_client.go
test/integration_test.go

Add support for query parameter when listing schedules
1. Closes https://github.com/temporalio/sdk-go/issues/1539
Added integration test cases

Add support for query parameter when listing schedules

---

internal/version.go

Forgot to bump the version in `version.go` before cutting the `1.28.0` release.

Update SDK version

---

internal/internal_schedule_client.go
internal/schedule_client.go
test/integration_test.go

Add support for managing schedule search attributes when when updating a schedule
1. Closes https://github.com/temporalio/sdk-go/issues/1561 
Added new integration test

Add support for managing schedule search attributes when when updating a schedule

---

internal/client.go
internal/internal_workflow.go
internal/internal_workflow_client.go
test/integration_test.go
test/workflow_test.go

Added `WorkflowIdConflictPolicy` to ExecuteWorkflow and SignalWithStart.
_NOTE: I haven't seen any `WorkflowIdReusePolicy` validation inside of `testsuite.WorkflowTestSuite` (except for child workflows), so I didn't add any for the `WorkflowIdConflictPolicy` either._
Closes https://github.com/temporalio/sdk-go/issues/1447

Support for WorkflowIdConflictPolicy

---

internal/internal_task_handlers.go
internal/internal_task_handlers_test.go

Protect against legacy queries when workflow execution is destroyed. Previously the SDK would panic since legacy queries against a cached execution have no history. 
closes https://github.com/temporalio/sdk-go/issues/1567

Protect against legacy queries when state is destroyed

---

test/integration_test.go
test/workflow_test.go

Test duplicate rejected updates. Test that an update ID can be reused if it was rejected. I noticed this was broken in the Java SDK so adding a test here as well.

Test duplicate rejected updates

---

internal/internal_workflow.go
internal/workflow_testsuite_test.go

Do not warn on unfinished handlers if workflow failed
closes https://github.com/temporalio/sdk-go/issues/1580

Do not warn on unfinished handlers if workflow failed

---

internal/workflow.go
internal/workflow_testsuite_test.go

Improve docs and tests for HandlerUnfinishedPolicy

Improve docs and tests for HandlerUnfinishedPolicy

---

internal/client.go

Removing wording saying a signal will ignore start delay
closes: https://github.com/temporalio/sdk-go/issues/1591

Removing wording saying a signal will ignore start delay

---

interceptor/interceptor.go
internal/interceptor.go
internal/interceptor_base.go
internal/workflow.go
test/nexus_test.go

I missed this when doing the initial implementation.
Note that for cancelation requests we do not yet support attaching headers, it's not available on the command / event and may be added if there's demand for it.

Allow workflow interceptors to add nexus headers

---

activity/activity.go
internal/activity.go

Minor grammar improvements for docstrings in activity.go
Saw a note somewhere that our docstrings could use some grammar corrections. Thought I'd take a small stab at activity.go while I perused the file. Not a commitment to fix all of our docstring's grammar :), but this should be a small improvement.
1. Closes 
Only docstrings updated, no code changes

Minor docstring grammar updates in activity.go

---

internal/internal_versioning_client.go

Remove a comment about task add and dispatch rate metrics that could mislead users.
```
"Activity tasks always go to normal queues ~so their reported rate is accurate.~"
```
Activities do not go to sticky queues, but because they are dispatched eagerly by default the rates are still inaccurate.
1. Closes 

Minor correction to TQ stats docs

---

interceptor/interceptor.go
internal/interceptor.go
internal/internal_workflow_client.go
temporal/error.go

closes https://github.com/temporalio/sdk-go/issues/1612

Expose QueryRejectedError

---

internal/internal_versioning_client.go

Counterpart to this API PR: https://github.com/temporalio/api/pull/452
Refining the definition of AllActive flag to align it to what server actually returns.
The AllActive options essentially returns all build IDs that are loaded in the server. Besides receiving recent tasks and polls, a build ID would be loaded/active if it was the subject of server APIs such as DescribeTaskQueue.
1. Closes 

Improve active build ID definition

---

test/worker_versioning_test.go

Changing a test assert based off of changed behavior from 1.25.0 server release. Test now checks for either no ramp or percentage is 100%
1.25.0 server release caused this test to start failing. Server was changed so we can specify a 100% ramp as equivalent to no ramp.
1. Closes 
Test passes locally

Fix Version test failure due to 1.25.0 server release

---

internal/internal_nexus_task_handler.go
test/nexus_test.go

- Handle `serviceerror`s, `ApplicationError`s, and other expected client errors returned from Nexus handlers.
- Also now exposing internal errors by default to match activity and child workflow behavior. We'll have to revisit hiding details from the caller when we start targeting cross org use cases.
Better out of the box developer experience.
Added integration tests.

Nexus handler error translation

---

.github/workflows/ci.yml
.github/workflows/docker/docker-compose.override.yaml
.github/workflows/docker/dynamic-config-custom.yaml
internal/cmd/build/main.go
test/nexus_test.go

Addressing a TODO I put in the code when working on Nexus while it wasn't available in a stable server / CLI release.
Also:
- Use dashes instead of underscores in the test endpoint names since that logic changed since the server RC was cut.
- [Enable 1.25.0 tests with docker-compose](https://github.com/temporalio/sdk-go/pull/1637/commits/719c86a665adcee0f7cb3f1acae74b2c4bcd4453)

Use stable CLI for tests

---

internal/internal_workflow_testsuite.go
test/nexus_test.go

Fix Nexus test env to respect `ScheduleToCloseTimeout` and return operation time out error.
Users can test the `ScheduleToCloseTimeout` when writing their tests.
1. Closes 

Fix Nexus test env to respect ScheduleToCloseTimeout

---

internal/internal_task_pollers.go
internal/internal_task_pollers_test.go

Evict the workflow from cache if their is a panic in the SDK. previously if their was some panic in the SDK code the SDK would not evict the workflow from cache and leave the workflow in a potentially bad state

Evict the workflow from cache if their is a panic in the SDK

---

internal/client.go
internal/internal_workflow_client_test.go

When the request for the update operation's handle times out, it now returns a more specific error if the operation was never actually executed as part of a MultiOperation.
It's easy to forget to specify `WithStartOperation` (happened to me when I worked on a Go sample). This signals more clearly to the user that they forgot to run it. However, IMO the error cannot be more specific than that, since there _could_ be other reasons why the operation was never executed.
1. Closes 

Error for unused Update operation

---

internal/internal_task_handlers_test.go
internal/internal_task_pollers.go
internal/internal_worker.go

Remove history truncation. As far back in the Go SDK as I can find we have this code to try to truncate any events past `atWorkflowTaskCompletedEventID`. It is not clear what the point of this code is and it has a number of bugs. Some of the issues are:
* It can panic if `h.Events[0].GetEventId() > atWorkflowTaskCompletedEventID`
* It is trying to check if the last event in history after truncation is a `EVENT_TYPE_WORKFLOW_TASK_COMPLETED`, but `atWorkflowTaskCompletedEventID` is from the workflow tasks `GetStartedEventId` so it should be a `EVENT_TYPE_WORKFLOW_TASK_STARTED`.
* If history does go beyond `GetStartedEventId` then that indicated this workflow task is stale and will be rejected by the server anyway
Note: The cadence team also pointed out the strangeness of this code …

Remove history truncation

---

internal/internal_event_handlers.go
internal/internal_task_pollers.go
internal/internal_workflow.go

Ensure the WorkflowTaskExecutionFailureCounter metric always has a tag set included.
Prometheus returns an error when you try incrementing the same counter if one instance has a tag set and the other didn't.
I validated that Prometheus is okay with different tag sets (in this case if we happen to call one instance with `WorkflowError` and the other with `NonDeterminismError` tag sets). I'm not sure there's a scenario where we increment this counter from different sources, but if there is, this shouldn't be an issue with Prometheus.
1. Closes #1450

Ensure WorkflowTaskExecutionFailureCounter is called with a tag

---

temporalnexus/operation.go

Not testing this since server 1.25.0 didn't get support for links.

Nexus: Fix link not being attached to a workflow started via a Handler function

---

internal/internal_logging_tags.go
internal/workflow.go
internal/workflow_testsuite_test.go
workflow/workflow.go

Include updateID and updateName in update logger.
closes https://github.com/temporalio/sdk-go/issues/1648

Include updateID and updateName in update logger

---

internal/internal_task_handlers_test.go
internal/internal_task_pollers.go

Error if history contains unexpected events after the StartedEventId

Error if history contains unexpected events after the StartedEventId

---

test/integration_test.go

Stop checking for specific error for QueryWorkflow that we expect to fail.
Sometimes we hit `Context deadline exceeded`, and sometimes we hit `query timed out before a worker could process it`, which is the server hitting `context deadline exceeded`.
1. Closes #1441 

Fix TestNonDeterminismFailureCauseReplay integration test

---

internal/internal_nexus_task_poller.go
internal/internal_task_handlers.go
internal/internal_task_pollers.go
internal/internal_versioning_client.go
internal/internal_versioning_client_test.go
internal/internal_worker.go
internal/worker.go
test/worker_versioning_test.go

Deployment Names are a new way to group task queues, based on Build IDs, to simplify rollouts in versioning-3.
In this PR we just add a new Worker Option for it, propagate  it during polling, and include it with task completion responses.

Add Deployment Names to Worker options 

---

internal/internal_worker.go
internal/internal_workflow_testsuite.go
internal/workflow_testsuite.go
test/nexus_test.go

Support mocking Nexus operation using `nexus.OperationReference`.
The user won't need to create a dummy implementation of Nexus operation to mock it.
1. Closes 

Support mocking Nexus operation with operation reference

---

internal/internal_worker.go
internal/internal_workflow_testsuite.go
internal/workflow_testsuite.go
test/nexus_test.go

Support for mocking nexus operations in the test framework.
The user can mock using either the `nexus.Operation` itself, or using `nexus.OperationReference` through the `nexus.NewOperationReference` helper. See the docs in the `OnNexusOperation` for description and example.
Be able to mock nexus operation without needing to have access to the operation implementation itself or creating dummy operations.
1. Closes 

Support for mocking nexus operations

---

internal/internal_task_handlers.go
internal/internal_worker.go
internal/internal_worker_test.go
internal/internal_workflow.go
internal/worker.go
internal/workflow.go
test/integration_test.go
test/worker_versioning_test.go
test/workflow_test.go
worker/worker.go
workflow/workflow.go

This PR supports providing a default versioning behavior in Worker Options, and a programmatic API to override these defaults:
For example:
``` go
workflow.SetVersioningBehavior(ctx, workflow.VersioningBehaviorPinned)
```
called  during the first workflow task sets the versioning mode for that workflow to `Pinned`, eliminating the need of patching.
And 
```go
w := worker.New(c, ts.taskQueueName, worker.Options{
DeploymentOptions: worker.DeploymentOptions{
BuildID:                   "1.0",
UseBuildIDForVersioning:   true,
DeploymentName:            "deploy-test1",
DefaultVersioningBehavior: workflow.VersioningBehaviorAutoUpgrade,
}
})
```
sets the default versioning behavior to `AutoUpgrade`. Note that `DeploymentName`, `UseBuildIDForVersioning` and `BuildID` need to be set to enable …

Support annotations for versioning behavior

---

.github/workflows/ci.yml

Update mac os runner to mac os 13 since mac os 12 is deprecated.

Update mac intel runner to macos-13

---

internal/internal_task_handlers.go
internal/internal_worker.go
internal/workflow.go
test/integration_test.go

Provides an alternative mechanism to provide a default versioning behavior per workflow type using workflow registration options.
```go
w.RegisterWorkflowWithOptions(ts.workflows.Basic, workflow.RegisterOptions{
VersioningBehavior: workflow.VersioningBehaviorPinned,
})
```
The programmatic  API to set Versioning Behavior is brittle because it needs to be called during the first workflow task.
1. Closes 
#1698 
An integration test using gRPC interceptors

Annotate versioning behavior per Workflow type

---

internal/activity.go
internal/error_test.go
internal/internal_activity.go
internal/internal_command_state_machine.go
internal/internal_command_state_machine_test.go
internal/internal_event_handlers.go
internal/internal_workflow.go
internal/workflow.go
internal/workflow_test.go
test/integration_test.go
test/workflow_test.go

Support user metadata on activities and child/scheduled workflows
closes https://github.com/temporalio/sdk-go/issues/1673

Support user metadata on activities and child/scheduled workflows

---

contrib/datadog/tracing/interceptor.go
contrib/datadog/tracing/interceptor_test.go

Added a `SpanFromWorkflowContext` function to allow access to the DataDog span object from within a workflow.
This allows users to access the Span from within a workflow to (for example) add custom tags on the span.
1. Closes #1701 
2. How was this tested: New unit test added
3. Any docs updates needed? Would be nice, please let me know where I could add these if this is desired.

Added SpanFromWorkflowContext function

---

client/client.go
internal/client.go
internal/internal_task_pollers.go
internal/internal_worker.go
internal/internal_worker_test.go
internal/internal_workflow_client.go
internal/internal_workflow_execution_options.go
internal/internal_workflow_execution_options_test.go
internal/nexus_operations.go
internal/worker.go
mocks/Client.go
test/integration_test.go
test/worker_versioning_test.go
worker/worker.go

The new versioning-3 introduces a config override API that enables external tools to change versioning behavior of
specific existing workflows. See #1712 for details. 
This PR exposes that API with a new client method:
```go
UpdateWorkflowExecutionOptions(ctx context.Context, options UpdateWorkflowExecutionOptionsRequest) (WorkflowExecutionOptions, error)
```
and relies on 
```go
DescribeWorkflowExecution(ctx context.Context, workflowID, runID string (*workflowservice.DescribeWorkflowExecutionResponse, error)
```
as getter.
1. Closes 
#1712 
There is currently no server implementation that supports this API. Integration tests will be added later, before merge into main. Only a basic protobuf unit test is included.

Update workflow execution options (versioning)

---

internal/internal_workflow_test.go
internal/workflow_testsuite.go
internal/workflow_testsuite_test.go
testsuite/testsuite.go

Added default implementation `TestUpdateCallbacks` for basic test scenarios
so tests don't need to implement `UpdateCallbacks` themselves. To make testing a little easier
1. Closes #1639
existing unit tests that were effected still pass

Improve Update Workflow testing UX

---

internal/internal_workflow.go

When evicting workflows from cache make sure all go routines are evicted serially.

When evicting workflows from cache make sure all go routines are evicted serially

---

internal/error.go

Added public accessors for `ChildWorkflowExecutionError`
Someone would like to react to maximum attempts of child workflow https://community.temporal.io/t/reacting-to-maximum-attempts/15366
1. Closes #1725

Add accessors for ChildWorkflowExecutionError fields

---

internal/client.go
internal/internal_schedule_client.go
internal/internal_workflow_client.go
internal/internal_workflow_client_test.go
internal/internal_workflow_execution_options.go
internal/schedule_client.go

Add a new option `VersioningOverride`  to `StartWorkflowOptions`. Enable this option too for `Schedule` and `SignalWithStart`.
The goal is to launch canary tests with specific versioning options without disrupting existing workflows.
This is part of the new versioning-3 API.
See #1715 for details
1. Closes 
#1715 
Two unit-tests. A system test will follow when a capable server becomes available.

Add versioning override to start workflow request

---

contrib/resourcetuner/resourcetuner.go
internal/internal_worker.go
internal/tuning.go
test/integration_test.go

There's now a separate slot supplier for session activities. Turns out this was also broken before in a different way, since previous to the slot suppliers change, session activity workers would have their own independent max concurrent, equal to the normal activity setting. Hence users using sessions could easily exceed the max number they thought they set.
Without it, pollers for the session TQ can starve the normal activity TQ of slots
1. Closes https://github.com/temporalio/sdk-go/issues/1732
Added integ test
Need to add some Go specific changes to docs on slot suppliers

Introduce separate slot supplier for session activities

---

internal/internal_workflow_testsuite.go
internal/workflow_testsuite.go
internal/workflow_testsuite_test.go

`WorkflowTestSuite.UpdateWorkflow` now aligns with the client and generate an update ID if none is set

WorkflowTestSuite.UpdateWorkflow generate an update ID if none is set

---

internal/deployment_client.go
internal/internal_deployment_client.go
internal/internal_task_handlers.go
internal/internal_worker.go
internal/internal_workflow.go
internal/workflow.go
test/integration_test.go
test/workflow_test.go
workflow/workflow.go

Remove programmatic SetVersioningBehavior API, and fail workflow registration when behavior missing.See #1739 for details.
1. Closes 
#1739 
One system test

Fail registration without versioning behavior

---

contrib/datadog/go.mod
contrib/datadog/go.sum
contrib/opentelemetry/go.mod
contrib/opentelemetry/go.sum
contrib/opentracing/go.mod
contrib/opentracing/go.sum
contrib/resourcetuner/go.mod
contrib/resourcetuner/go.sum
contrib/tally/go.mod
contrib/tally/go.sum
go.mod
go.sum
internal/cmd/build/go.mod
internal/cmd/build/go.sum
internal/internal_workflow_testsuite.go
internal/workflow_testsuite.go
internal/workflow_testsuite_test.go
test/go.mod
test/go.sum

Upgrading testify to `v1.10.0`.
Adding an InOrderMockCalls(calls ...*MockCallWrapper) helper method to setup mock calls in order. It implements a similar helper that was recently added and released in to https://github.com/stretchr/testify. 
I had opened a similar PR in the past: https://github.com/temporalio/sdk-go/pull/1623 but was canceled because the helper methods implemented in temporal are similar to the ones offered by "testify", and it was already added to "testify".
A more intuitive and cleaner way to define mock calls in order. For example:
```
env.InOrderMockCalls(
env.OnActivity(namedActivity, mock.Anything, "call1").Return("result1", nil),
env.OnActivity(namedActivity, mock.Anything, "call2").Return("result2", nil),
env.OnActivity(namedActivity, mock.Anything, …
```

mock: in order mock calls using new testify mock.InOrder() method

---

internal/internal_workflow_client.go
internal/internal_workflow_client_test.go

Tweak error reporting of Update-with-Start.
Communicate errors better to user.
1. Closes 

Tweak Update-with-Start error reporting

---

test/nexus_test.go

Add Nexus links tests
1. Closes 

Add Nexus links tests

---

test/nexus_test.go

The behavior changed in server 1.26.2 and we no longer support canceling an not-yet-started operation.

Remove Nexus OpCanceledBeforeStarted test

---

internal/internal_nexus_task_handler.go
internal/internal_nexus_worker.go
internal/internal_worker.go
internal/internal_workflow_testsuite.go
internal/nexus_operations.go
temporalnexus/operation.go
test/nexus_test.go

This is similar to how child workflow name resolution works. Without this, we don't properly support alias based registration.

Resolve workflow name alias in Nexus WorkflowRunOperation

---

contrib/tools/workflowcheck/determinism/testdata/src/a/ignore.go
internal/internal_workflow_execution_options.go
internal/workflow_test.go
mocks/Client.go
test/deployment_test.go

The current implementation for versioning override fails for AutoUpgrade
because it uses an empty Deployment struct instead of a nil pointer.
See #1764 for details.
Also missing `gofmt` of some unrelated files corrected.
This is a blocker for the new versioning-3 implementation.
1. Closes 
#1764 
Integration test

Fix versioning override with AutoUpgrade behavior

---

client/client.go
internal/activity.go
internal/client.go
internal/internal_public.go
internal/internal_workflow_client.go

Fixing intellisense docstring hovers.
It conforms to Go's standards: https://tip.golang.org/doc/comment#lists and doesn't harm Godoc because it is rendered verbatim: https://pkg.go.dev/go.temporal.io/sdk/client#Client
Before:
After:

docs: fix bullets in intellisense

---

.github/workflows/ci.yml
.github/workflows/docker/dynamic-config-custom.yaml
test/deployment_test.go
test/integration_test.go

Server 1.26.2 is already enabled in `docker-compose` and we no longer need to disable
new versioning tests for docker container test.

Remove docker flag that disables versioning tests

---

internal/internal_task_pollers.go
workflow/doc.go

small docs/rendering fixes

---

internal/cmd/tools/doclink/doclink.go
internal/error.go
internal/interceptor.go
internal/nexus_operations.go

- Removed duplicate "Exposed as" comments
- added ability to detect/delete stale aliases
- handle edge case where gofmt reorders the doc comment (i.e. `UpsertSearchAttributes` from workflow.go)
Unintended behavior
1. Closes #1774
Manually added and removed aliases

Fix doclink tool's duplicate docstring generation issue

---

test/deployment_test.go

Server 1.26.2 creates a test flake because the SetCurrent API is eventually consistent.
This was fixed in https://github.com/temporalio/temporal/pull/6978 but unfortunately it is not available
in any OSS release just yet.
Disabling the test TestPinnedBehaviorThreeWorkers()  for now

Disable TestPinnedBehaviorThreeWorkers() test

---

internal/interceptor.go
internal/internal_workflow_client.go
internal/nexus_operations.go
temporalnexus/operation.go
test/nexus_test.go

Added a new type of synchronous Nexus operation for sending signals.
Convenience and request ID + links handling.
1. Closes 
New functional tests

Add Nexus SignalWorkflowOperation

---

internal/grpc_dialer.go
internal/grpc_dialer_test.go
internal/internal_workflow_client.go

Set Temporal-Namespace header on every namespace-specific gRPC request.
closes https://github.com/temporalio/sdk-go/issues/1458

Set Temporal-Namespace header on every namespace-specific gRPC request

---

internal/workflow_testsuite.go
internal/workflow_testsuite_test.go

Ensure UpdateWorkflowNoRejection is correctly triggered with one or variadic arguments.
It's a bug in unit test.
1. Closes
2. How was this tested

Expand arguments in UpdateWorkflow call when args equal one

---

internal/internal_utils.go
internal/internal_worker.go
internal/internal_worker_test.go
internal/workflow.go
temporalnexus/operation.go
temporalnexus/operation_test.go
test/integration_test.go
test/workflow_test.go

Prevent users from using `__temporal_` across workflows, activities, nexus operations/services, and signals.
Queries and updates already reserve the `__` prefix 
We want to reserve a prefix to throw any special behavior under.
1. Closes  #1779 
Added tests

Reserve "__temporal_" prefix 

---

testsuite/devserver.go

Add option to override UI port
closes: https://github.com/temporalio/sdk-go/issues/1788

Add option to override UI port

---

contrib/datadog/go.mod
contrib/datadog/go.sum
contrib/opentelemetry/go.mod
contrib/opentelemetry/go.sum
contrib/opentracing/go.mod
contrib/opentracing/go.sum
contrib/tally/go.mod
contrib/tally/go.sum
go.mod
go.sum
internal/cmd/build/go.mod
internal/cmd/build/go.sum
internal/internal_workflow.go
internal/workflow.go
workflow/workflow.go

These experimental packages are now available in the Go standard library.
1. `golang.org/x/exp/slices` -> `slices` (https://go.dev/doc/go1.21#slices)
2. `golang.org/x/exp/constraints` -> `cmp` (https://go.dev/doc/go1.21#cmp)
Part of the effort for https://github.com/temporalio/temporal/pull/6366
```
$ go test ./...
?   	go.temporal.io/sdk/activity	[no test files]
?   	go.temporal.io/sdk/client	[no test files]
ok  	go.temporal.io/sdk/converter	0.036s
ok  	go.temporal.io/sdk/interceptor	0.066s
?   	go.temporal.io/sdk/internal/cmd/dummy	[no test files]
?   	go.temporal.io/sdk/internal/cmd/tools/copyright	[no test files]
?   	go.temporal.io/sdk/internal/cmd/tools/doclink	[no test files]
?   	go.temporal.io/sdk/internal/common/retry	[no test files]
? …
```

Replace `golang.org/x/exp` with stdlib

---

internal/workflow_testsuite.go

Followup to #1802, this API was missed.

Rename operationID to token in TestWorkflowEnvironment

---

internal/workflow_testsuite.go

Added a note that SetOnActivityHeartbeatListener may be called concurrently
Users have noted that this can occasionally hit a data race issue. Wasn't able to repro, so adding a note of this to the SDK for now.
1. Closes #908  

Add note that SetOnActivityHeartbeatListener may be called concurrently

---

internal/internal_workflow_testsuite.go
internal/nexus_operations.go
test/nexus_test.go

- Propagate operation timeout to the handler via header.
- Handle operation complete-before-start.

Catchup tasks for Nexus features in the test env

---

test/integration_test.go
test/test_utils_test.go

Moved `SetStickyWorkflowCacheSize` from `IntegrationTestSuite` to a more global spot, so all test suites set this config. 
test suites in the same package are run in the same process, so a test suite that wasn't setting this cache size was causing the cache size in `IntegrationTestSuite` to be incorrect.
Still not exactly sure why this was suddenly hit with 1.24, maybe optimizations highlighted existing race condition between cleanup of one testsuite and the starting of the next testsuite.
1. Closes #1827

SetStickyWorkflowCacheSize for all testsuites

---

.github/workflows/ci.yml
internal/cmd/build/main.go
internal/internal_nexus_task_handler.go
test/nexus_test.go

Temporarily using the pre-release CLI for testing.

Translate relevant errors to non retryable internal Nexus handler errors

---

internal/internal_command_state_machine.go
internal/internal_event_handlers.go
test/integration_test.go
test/workflow_test.go

**before**
> [TMPRL1100] unknown command CommandType: Timer, ID: 8, possible causes are nondeterministic workflow definition code or incompatible change in the workflow definition
**after**
> [TMPRL1100] During replay, a matching Timer command was expected in history event position 8. However, the replayed code did not produce that. Possible causes are nondeterministic workflow definition code, or an incompatible change in the workflow definition.

More user-friendly NDE error message

---

internal/client.go
internal/internal_workflow_client.go
internal/internal_workflow_execution_options.go
temporalnexus/operation.go

Add `OnConflictOptions` to `StartWorkflowOptions`, and set it for Nexus `WorkflowRunOperation`.
Tests are done in https://github.com/temporalio/sdk-go/pull/1828
Enabling attaching callbacks to running Nexus workflows.
1. Closes 

[Nexus] Set OnConflictOptions for WorkflowRunOperation

---

internal/internal_worker_deployment_client.go
internal/internal_worker_deployment_client_test.go

A nil Google protobuf for a timestamp returns with `AsTime()` a year 1970, making IsZero() false, since 
Go `time.Time` expects year 1.
This PR checks for nil timestamps and returns `time.Time{}` for them in the new versioning API. 
1. Closes 
#1846 
A unit-test added.

Versioning: Fix AsTime() for a nil proto timestamp

---

temporalnexus/operation.go
test/nexus_test.go

Block using conflict policy `UseExisting` for Nexus `WorkflowRunOperation`.
Returning a non-retryable internal error at this moment.
1. Closes 

Block using conflict policy UseExisting for Nexus WorkflowRunOperation

---

internal/log/memory_logger.go
test/nexus_test.go

Added additional test assertions for labels on metrics and logs when using `temporalnexus.GetMetricsHandler` or `temporalnexus.GetLogger`
Closes https://github.com/temporalio/sdk-go/issues/1545

Add assertions for labels on Nexus metrics and logs

---

contrib/datadog/go.mod
contrib/datadog/go.sum
contrib/opentelemetry/go.mod
contrib/opentelemetry/go.sum
contrib/opentracing/go.mod
contrib/opentracing/go.sum
contrib/resourcetuner/go.mod
contrib/resourcetuner/go.sum
contrib/tally/go.mod
contrib/tally/go.sum
go.mod
go.sum
internal/cmd/build/go.mod
internal/cmd/build/go.sum
internal/grpc_dialer_test.go
internal/internal_schedule_client.go
internal/internal_task_handlers_test.go
internal/internal_task_pollers.go
internal/internal_worker.go
internal/internal_workers_test.go
internal/internal_workflow_client.go
internal/session.go
test/deployment_test.go
test/go.mod
test/go.sum
test/integration_test.go
test/test_utils_test.go
test/worker_deployment_test.go
test/worker_versioning_test.go

Replace all usages of `github.com/pborman/uuid` to `github.com/google/uuid`.
Currently we have two UUID packages as dependencies:
https://github.com/temporalio/sdk-go/blob/9ce2508da67137e56e0bb9ba04e1ded5d5fcdab5/go.mod#L13
https://github.com/temporalio/sdk-go/blob/9ce2508da67137e56e0bb9ba04e1ded5d5fcdab5/go.mod#L28
The `github.com/pborman/uuid` package is no longer actively maintained (last release in 2019), so we should switch to the newer `github.com/google/uuid`.
Additionally, `github.com/pborman/uuid` already relies on `github.com/google/uuid` internally, so it makes sense to use `github.com/google/uuid` directly.
```
go test ./...
?   	go.temporal.io/sdk/activity	[no test files]
?   	go.temporal.io/sdk/client	[no test files]
ok  	go.temporal.io/sdk/converter …
```

Replace `github.com/pborman/uuid` with `github.com/google/uuid`

---

client/client.go
internal/client.go

Added WorkflowExecutionAlreadyStarted as an error type, and information on when it can be returned
Accuracy and clarity
1. Closes #1856

Doc: Add WorkflowExecutionAlreadyStarted error type to ExecuteWorkflow description

---

internal/workflow.go
test/nexus_test.go

Using `%q` to quote vars in error message.
Replace `reflect.Type.Name()` with `reflect.Type.String()`: it returns the type name with prefixed with package name (`Name()` can be empty).
It's more clear when the variable is an empty string.
1. Closes 

Better Nexus error message

---

internal/tuning.go
test/worker_tuner_test.go

Fix a bug where resource based slot supplier was looking at a stale issued slots number while trying to reserve
Could cause it to be stuck failing to reserve
1. Closes https://github.com/temporalio/sdk-go/issues/1868
Added test

Fix possibly failing to reserve slots due to stale issued number

---

internal/client.go

Make it more clear that WorkflowIDReuse/ConflictPolicy relies on WorkflowExecutionErrorWhenAlreadyStarted
Clarity
1. Closes #1857
comment only change

Doc: Add clarity to WorkflowIDReuse/ConflictPolicy's dependence on WorkflowExecutionErrorWhenAlreadyStarted

---

client/client.go
contrib/opentelemetry/handler.go
converter/grpc_interceptor.go
internal/activity.go
internal/client.go
internal/deployment_client.go
internal/error.go
internal/failure_converter.go
internal/internal_versioning_client.go
internal/internal_worker.go
internal/internal_workflow_client.go
internal/internal_workflow_execution_options.go
internal/schedule_client.go
internal/worker.go
internal/worker_deployment_client.go
internal/worker_version_sets.go
internal/workflow.go
internal/workflow_testsuite.go
worker/worker.go
workflow/workflow.go

Added blank lines before "Optional", "default", and "note" lines for clarity.
This was already happening in some place and not others, so also just converging on consistency.
for clarity when rendered in IDE
1. Closes 

Doc: Add blank lines before "Optional", "default", and "note" lines for clarity

---

internal/internal_command_state_machine.go
internal/internal_event_handlers.go
internal/workflow.go
test/nexus_test.go

Add summary to Nexus operation
closes https://github.com/temporalio/sdk-go/issues/1861

Add summary to Nexus operation

---

converter/grpc_interceptor.go

NewFailureGRPCClientInterceptor already has this note, adding the same note to NewPayloadCodecGRPCClientInterceptor.
Clarity
1. Closes #1886
doc only change

Doc: Add note about NewFailureGRPCClientInterceptor before NewPayloadCodecGRPCClientInterceptor

---

.github/workflows/ci.yml
internal/checksum.go
internal/checksum_legacy.go
internal/internal_worker.go

Switch from using `md5` to `sha256` to in `initBinaryChecksumLocked` so the Go SDK will work with `fips140` mode. I also added this to our CI when we connect to Temporal cloud over TLS
see also https://go.dev/doc/security/fips140
closes https://github.com/temporalio/sdk-go/issues/1887

Add FIPs to CI

---

converter/codec.go
converter/codec_test.go
converter/composite_data_converter.go
converter/data_converter.go
converter/value.go
test/activity_test.go
test/integration_test.go
test/workflow_test.go

Added new RawValue type and add support in codec and composite data converter.
SDKs need to support a payload wrapper called "raw value" that is just a payload but is passed through the conversion stage (but still applies to codec).
1. Closes #1231 
Added unit tests for both codec and composite data converter, and an integration test that pass a payload to and from a workflow and activity
No

Add RawValue support

---

internal/cmd/build/main.go
internal/internal_task_handlers_test.go
test/integration_test.go
test/test_utils_test.go

Disable some know flaky tests. Increase some timeouts to reduce flakes
We have an issue to track https://github.com/temporalio/sdk-go/issues/1650 that we should prioritize next sprint

Disable some know flaky tests

---

internal/internal_schedule_client.go
test/integration_test.go

Make sure schedule Update treats CatchupWindow properly. When we create a schedule we treat a `CatchupWindow=0` as unset, so we pass `nil` which tells the server to use the default value. On update we forgot to convert `CatchupWindow=0` causing the server to use the min. value of `10s` instead.
https://github.com/temporalio/sdk-go/blob/31c4c30812adcd53554f08dfc5ca917df718ceae/internal/internal_schedule_client.go#L124

Make sure schedule Update treats CatchupWindow properly

---

client/client.go
internal/client.go

This PR changes the capitalization of `WorkflowID` to `WorkflowId` in the comments of the example code for `ListWorkflow`
I copied the example code to use in a query like so:
```go
temporalClient.ListWorkflow(context.Background(), &workflowservice.ListWorkflowExecutionsRequest{
Namespace: TemporalNamespace,
Query:     fmt.Sprintf("(WorkflowID = '%s' or WorkflowID = '%s')", workflow1, workflow2),
})
```
And was greeted with the following error:
`invalid query: invalid expression: column name 'WorkflowID' is not a valid search attribute`
Changing `WorkflowID` to `WorkflowId` fixed the issue, so I'm opening this PR so others after me don't fall into the same mistake.
- Ran a `ListWorkflow` query with the updated example code.
1. Any docs updates needed?
I don't think …

Fix `WorkflowId` being wrongly capitalized on example comments

---

internal/internal_workflow_client.go
internal/internal_workflow_client_test.go

This change:
- Removes comment that contradicts behavior
- Add documentation comment to make the functions behavior and dependency to `HasNext` clear.
- Adds test to ensure that and breaking changes to this behavior is caught
While I was exploring the documentation for the get history calls at work, I was trying to figure out what happens with the iterator if `HasNext()` is false but the `Next()` function was called, and I noticed that there was this line where the comment contradicted it.
Added unit test.
2. Any docs updates needed?
I don't think so

Update documentation for `Next` history iterator

---

internal/internal_task_handlers.go
internal/internal_task_handlers_test.go
internal/internal_task_pollers.go
internal/internal_worker.go
internal/internal_worker_base.go
internal/internal_worker_test.go
internal/internal_workers_test.go
internal/internal_workflow_testsuite.go
worker/worker.go

Add worker shutdown cause to context. This will help users tell why their activity/local activity context was cancelled. Before this PR when an activity/local activity was shutting down at the end of the shutdown process the SDK would cancel the context, but users couldn't distinguish this cancel vs other reasons the cancel may be cancelled.

Add worker shutdown cause to context

---

internal/client.go

Clarify ReusePolicy / ConflictPolicy / WorkflowExecutionErrorWhenAlreadyStarted docstrings

---

.github/workflows/docker/dynamic-config-custom.yaml
activity/activity.go
client/client.go
internal/activity.go
internal/activity_test.go
internal/cmd/build/main.go
internal/internal_task_handlers.go
internal/internal_task_handlers_test.go
internal/internal_task_pollers.go
test/activity_test.go
test/integration_test.go
test/workflow_test.go

Add support for activity pause. Makes use of `context.Cause` to tell users why exactly their Activity was cancelled 
closes: https://github.com/temporalio/sdk-go/issues/1899

Add support for activity pause

---

internal/workflow_testsuite.go
internal/workflow_testsuite_test.go

If any of the OnAccept/OnReject/OnCompile callbacks aren't passed in, avoid call them to avoid throwing a nil pointer error.
Previously, if any of the OnAccept/OnReject/OnCompile callbacks weren't passed in, a nil pointer error was thrown, without any clear indicator where the error was being thrown. This should improve uer experience when writing UpdateWorkflow tests
1. Closes  #1860
Added test

TestUpdateCallback UX improvement

---

internal/error.go
internal/failure_converter.go
internal/nexus_operations.go
internal/workflow.go
temporalnexus/operation.go
test/nexus_test.go

Remove deprecated nexus APIs we deprecated before GA. This is a breaking change, but these APIs were deprecated before we went GA, at the time we deprecated them with the intention to remove to give users time to migrate.

Remove deprecated nexus APIs

---

contrib/datadog/go.mod
contrib/datadog/go.sum
contrib/envconfig/go.mod
contrib/envconfig/go.sum
contrib/opentelemetry/go.mod
contrib/opentelemetry/go.sum
contrib/opentracing/go.mod
contrib/opentracing/go.sum
contrib/resourcetuner/go.mod
contrib/resourcetuner/go.sum
contrib/tally/go.mod
contrib/tally/go.sum
go.mod
go.sum
internal/cmd/build/go.mod
internal/cmd/build/go.sum
temporalnexus/link_converter.go
temporalnexus/link_converter_test.go
test/go.mod
test/go.sum

Support for `RequestIdReference` in `Link`.
Support encoding/decoding `RequestIdReference` in `Link`.
1. Closes 

Support for RequestIdReference in Link

---

temporalnexus/link_converter.go
temporalnexus/link_converter_test.go

Encode the event type short string instead of the long string (eg: `WorkflowExecutionStarted` instead of `EVENT_TYPE_WORKFLOW_EXECUTION_STARTED`).
The parser accepts both.
1. Closes 

Encode the event type short string in the links

---

internal/client.go
internal/cmd/build/main.go
internal/internal_workflow_client.go
internal/internal_workflow_client_test.go
temporalnexus/operation.go
test/nexus_test.go

Introduce `StartWorkflowResponseInfo` to `StartWorkflowOptions`.
Handle links from `ExecuteWorkflow` in Nexus `WorkflowRunOperation`.
Be able to pass information from `StartWorkflowExecutionResponse` to `ExecuteWorkflow` call through `StartWorkflowOptions`.
Use the link from the server instead of generating one in `WorkflowRunOperation`.
1. Closes 

Handle links from ExecuteWorkflow in Nexus WorkflowRunOperation

---

internal/workflow.go

Improve docs on `NexusOperationCancellationTypeTryCancel `to clarify if the cancellation may not be delivered if the workflow completes before it is delivered.

Improve docs on NexusOperationCancellationTypeTryCancel

---

internal/worker_version_sets.go
internal/workflow.go
temporal/build_id_versioning.go
workflow/workflow_options.go

A few more spots where old versioning approaches should've been deprecated

Deprecate versioning intents

---

client/client.go
internal/worker_version_sets.go
internal/worker_versioning_rules.go
internal/workflow.go
mocks/Client.go
temporal/build_id_versioning.go
workflow/workflow_options.go

Deprecated more of the penultimate versioning API surface
1. Closes 

Deprecate more old versioning APIs

---

internal/common/metrics/handler.go

This explicitly states how WithTags should work with existing tags on the handler.
Documentation only for the metrics handler interface.
I had implemented a custom handler and had a hard time figuring out why some tags I needed for alerting were missing. See [slack thread](https://temporalio.slack.com/archives/CTDTU3J4T/p1749727637878739).
1. Closes
Not needed
Not sure as I don't remember seeing this in the documentation. Honestly I figured it out by looking at how the uber-go/tally package implements it and asking on slack. I think having it in the metrics handler interface is good enough but let me know if you also want it included somewhere in the documentation.

Clarify WithTags behaviour in metrics handler

---

converter/codec.go
converter/codec_test.go

Returns error is codec `encode` method error in ToPayload
If codec failed to encode data, the error was silent and the non-encoded payload was return. An error management is missing because an error was expected in this case.
1. Closes https://github.com/temporalio/sdk-go/issues/1999
2. How was this tested: unit test
3. Any docs updates needed? No

Fix data converter ToPayload error management

---

internal/cmd/build/main.go
testsuite/devserver.go
testsuite/devserver_test.go

Added the ability to pass SearchAttributes into dev server.
Found out we weren't testing `testsuite/` tests in our unit tests, fixed that issue in this PR as well
SDK parity
1. Closes #1523 
new test

Accept search attributes for dev server

---

internal/internal_worker_base.go

Make poller scaling log trace since it is quite noisy, but can be useful to debug poller scaling decisions.

Make poller scaling log trace

---

contrib/envconfig/client_config.go

Changed the check in `client_config.go` from:
```
} else if c.ServerCACertPath == "" {
return nil, fmt.Errorf("cannot have server CA cert path with data")
}
```
to 
```
} else if c.ServerCACertPath != "" {
return nil, fmt.Errorf("cannot have server CA cert path with data")
}
```
The current check was causing the error to be thrown incorrectly when CA cert data was provided but CA cert path was NOT.

Fix CA cert config validation
